### ISSUE TITLE
Video submission form issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#100]
- Academic disciplines must be optional
- Get rid of optional metadata (move author fields up but remove the rest)

**Comment by monika-aashe** [comment]
- Maybe change "author" to say "video creator"

**Comment by jamstooks** [comment]
We probably want to get the author field handled first: #73

**Comment by monika-aashe** [comment]
Closing this ticket, since these issues are covered in other tickets. #73 and #85.
