### ISSUE TITLE
Submission Confirmation page

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#101]
A few changes to the page that shows up after a user submits a resource:
- Current Text: "YOUR RESOURCE WAS SUBMITTED AND IS REVIEWED BY OUR TEAM SOON."
- Change to, "Thank you for submitting a resource for consideration! It will be reviewed by our team, and you should receive a follow-up email within 48 hours."

**Comment by jamstooks** [comment]
Again: [django-block-content](https://github.com/AASHE/django-block-content). It's already implemented on the homepage.
