### ISSUE TITLE
Export IRC Academic Programs database content into CSV

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#103]
In preparation for exporting the old IRC content into the new Hub: 

1. Please send a CSV file of the IRC Academic Programs database (http://www.aashe.org/resources/academic-programs/) to monika@aashe.org. 

2. Please create a second CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Academic Programs (http://aashe-hub-dev.herokuapp.com/browse/types/academicprogram/) as an example to generate this file. 

Considerations: 
- How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator? 
- Need to ensure that major changes to submission forms are done before completing step 2 above.
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by charris2015** [comment]
I've sent the csv file containing the academic programs to Monika. I've also formatted the fields according to the layout within the hub. The only fields that I couldn't include were keywords and the sustainability topics. These fields were not apart of the original content type.

**Comment by jamstooks** [comment]
@monika-aashe let us know if you have any questions or if this is good to go...

**Comment by jamstooks** [comment]
@charris2015 looks like `academic_programs_academicprogram`

**Comment by monika-aashe** [comment]
@charris2015 - a few issues with this as well:
- There are some missing entries - there are 1,472 on the website but only 1,330 in this export. See breakdown below. 
- This export is missing the "Description" field, and we need this for the Hub. Can you please add this? 
- The special character issue is happening again: e.g. "Master‰Ûªs" instead of "Master's". Can you resolve this here and for any future exports? 
Thanks!

**Comment by charris2015** [comment]
Hey @monika-aashe ,

I've exported this again with the description field and the extra entries. I'm sending you the file via gmail.

**Comment by monika-aashe** [comment]
Hey Chris, it doesn't look like I received anything yet.

On Tue, Jan 12, 2016 at 3:30 PM, charris2015 <notifications@github.com>
wrote:

> Hey @monika-aashe <https://github.com/monika-aashe> ,
>
> I've exported this again with the description field and the extra entries.
> I'm sending you the file via gmail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/103#issuecomment-171045206>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by charris2015** [comment]
@monika-aashe you should have it in your inbox now

**Comment by monika-aashe** [comment]
Any updates on when the updated list will be ready? The last export you sent had about 150 programs missing, but you did fix the issue with the Discipline, Program Type, and Institution name showing as IDs instead of titles. 

Here is the list of fields needed for the export:
- Make sure there are 1,472 entries (rows)
- Program Name
- Program Type
- Institution
- Other institutions (open text field)
- Program description
- Homepage
- Duration
- Year Founded
- Distance ed
- Program commitment
- Discipline
- Blog
- LinkedIn
- Facebook
-Twitter

Feel free to include some of the other fields if it's easier. Thanks

**Comment by monika-aashe** [comment]
Hey @charris2015 - is it still possible to send me this list today? I'm hoping to get started on it this weekend. Thanks!
