### ISSUE TITLE
Export IRC Case Studies database content into CSV

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#104]
In preparation for exporting the old IRC content into the new Hub:

1. Please send a CSV file of the IRC Case Studies database (http://www.aashe.org/resources/case-studies) to monika@aashe.org.

2. Please create a second CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Case Studies  (http://aashe-hub-dev.herokuapp.com/browse/types/casestudy/) as an example to generate this file.

Considerations:
- How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator?
- Need to ensure that major changes to submission forms are done before completing step 2 above.
- Is it possible to automatically migrate over the uploaded files? If so, we need to change the file pathways (change http://www.aashe.org/files/resources/student-research/2009/nac_leed_brochure.pdf to http://www.aashe.org/files/hub/case-study/2009/nac_leed_brochure.pdf)
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by charris2015** [comment]
I've sent the case studies export in a csv file to Monika

**Comment by jamstooks** [comment]
@monika-aashe let us know if you have any questions or if this can be closed.

**Comment by monika-aashe** [comment]
Will do. Haven't looked at this one yet. Should we leave these open until the files I'm updating are successfully imported into the Hub (in lieu of creating new cases for that)?

**Comment by monika-aashe** [comment]
@charris2015 
Finally got a chance to review the Case Studies export. There are a few issues so hopefully these are fairly easy to resolve and you can resend with the following improvements.

- 24 missing case studies - According to the Case Studies website, there are 279 case studies, however this file only has 255. Can you find the missing ones and add them in?
- Special characters - Is there a way to fix the special character issue? Example: "Philadelphiaäó»s" instead of "Philadelphia's"
- Multiple authors - some case studies include three or more authors (here's an example with four: http://www.aashe.org/resources/case-studies/biogas-systems-anaerobic-digestion-sustainability-education-and-and-research-). However the export you sent only includes up to 2 authors. Can you add in the remaining author columns? (the case study form has 3 author field entries, plus one "additional authors" field)
- Image files - most case studies include images - you can upload up to three. However it appears that these files are not included in the export. Can you add them in?

**Comment by charris2015** [comment]
Hey Monika, 

I've made the changes to the case studies export. I've sent the file to your gmail. Let me know if I need to make any changes, if not, we can resolve this ticket.

-Chris H.

**Comment by jamstooks** [comment]
@monika-aashe and @charris2015 - it might make sense to reassign these to Monika when you've completed your part, Chris. That way we can reuse the issue for export *and* import;

**Comment by monika-aashe** [comment]
@charris2015 

Something is wrong with the latest Case Studies export you sent me on Jan. 8. The content doesn't match the column headings and there are weird line breaks everywhere. When you please re-run, please ensure that all of the following are met: 

- There is a total of 279 case studies, each on it's own row.
- Special characters are fixed. Example: "Philadelphiaäó»s" instead of "Philadelphia's"
- Make sure all authors are included - some case studies include three or more authors (here's an example with four: http://www.aashe.org/resources/case-studies/biogas-systems-anaerobic-digestion-sustainability-education-and-and-research-). The first export you sent only included up to 2 authors. 
- Image files - most case studies include images - please include links to all of the images. 

Here is the list of fields that need to be in the export:
Title
Organization Name
Post Date
Keywords
Content Type
Disciplines
Project Overview
Background
Project Goals & Objectives
Project Implementation
Timeline
Financing
Project Results and Realized Benefits
Lessons Learned
URL field 1
URL field 2
URL field 3...
File link 1
File link 2
File link 3...
Image file 1
Image file 2
Image file 3...
First author (separate columns for first name, last name, title, department, organization, email)
Second author (separate columns for first name, last name, title, department, organization, email)
Third author (separate columns for first name, last name, title, department, organization, email)
Additional authors (single text field)

**Comment by monika-aashe** [comment]
@charris2015 - please include the submitter's User ID in the export if possible. Thanks.
