### ISSUE TITLE
Export IRC Conference Presentations database content into CSV

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#105]
In preparation for exporting the old IRC content into the new Hub:

1. Please send MULTIPLE CSV files of the IRC Conference Presentations databases to monika@aashe.org. These should include the following:
   - AASHE 2015 presentations index - No public link yet
   - AASHE 2014 presentations index - http://www.aashe.org/events/conference/2014-presentation-index
   - AASHE 2013 presentations index - http://www.aashe.org/events/conference/2013-presentation-index
   - AASHE 2010-12 presentations database - http://www.aashe.org/resources/conference/search
   - AASHE 2008 presentations database - http://www2.aashe.org/conf2008/keywords.php

2. Please create a second CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Conference Presentations  (http://aashe-hub-dev.herokuapp.com/browse/types/presentation/) as an example to generate this file.

Considerations:
- How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator?
- Need to ensure that major changes to submission forms are done before completing step 2 above.
- Is it possible to automatically migrate over the uploaded files? If so, we need to change the file pathways (change http://www.aashe.org/files/resources/student-research/2009/nac_leed_brochure.pdf to http://www.aashe.org/files/hub/case-study/2009/nac_leed_brochure.pdf)
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by jamstooks** [comment]
In the exports, please include the full url for each file... that means including the http://...

**Comment by jamstooks** [comment]
remaining conferences are

- [ ] 2008
- [ ] 2015

**Comment by charris2015** [comment]
@monika-aashe I've sent the 2008 and 2015 case studies Let me know if I need to make any changes.

-Chris H.

**Comment by monika-aashe** [comment]
This list is done and ready for import. What's the best format for the file (csv or Excel) and who should I send to?
