### ISSUE TITLE
Export IRC Publications content into CSV

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#107]
In preparation for exporting the old IRC content into the new Hub:

1. Please indicate whether resources on either of the following pages can be exported into a CSV file (If not, these will have to be imported into the Hub manually.):
   - Publications on Campus Sustainability - http://www.aashe.org/resources/publications-campus-sustainability
   - Publications from AASHE - http://www.aashe.org/resources/publications-aashe

2. Please create a CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Publications  (http://aashe-hub-dev.herokuapp.com/browse/types/publication/) as an example to generate this file.

Considerations:
- How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator?
- Need to ensure that major changes to submission forms are done before completing step 2 above.
- Is it possible to automatically migrate over the uploaded files? If so, we need to change the file pathways (change http://www.aashe.org/files/resources/student-research/2009/nac_leed_brochure.pdf to http://www.aashe.org/files/hub/case-study/2009/nac_leed_brochure.pdf)
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by jamstooks** [comment]
@charris2015  this looks like just a parse of the html on http://www.aashe.org/resources/publications-campus-sustainability

With the others from the second link (http://www.aashe.org/resources/publications-aashe), find those that aren't simply html pages stored in drupal. those that are flat HTML we don't really make sense to parse.

Converting from HTML to CSV works sometimes, but if the HTML is variable, then it doesn't make sense and we'll have to do things manually.

**Comment by charris2015** [comment]
hey @monika-aashe I've sent a spreadsheet of all the publications content from http://www.aashe.org/resources/publications-campus-sustainability organized by category. still working on the export for http://www.aashe.org/resources/publications-aashe but will be sending those shortly.

-Chris

**Comment by charris2015** [comment]
Hey @monika-aashe ,

I've sent an export containing the additional exports. The content is broken up by title, so each different publication fills it's own column.

-Chris

**Comment by monika-aashe** [comment]
Hey @charris2015  
I just realized we also need to fold all of the student research resources into the publications database. I will also need an export of the following - there are 198 total resource entries: http://www.aashe.org/resources/student-research

Please include all of the information provided in these pages, including publication date, uploaded files, images, etc. Thanks in advance!

**Comment by monika-aashe** [comment]
Hey @charris2015 - Any updates on this? Here is the list of fields needed for this export:
- Make sure there are 198 total entries 
- Title
- Type of Paper
- Institution
- Other Organizations
- Disciplines
- Admin Depts.
- Keywords
- Date (year and month)
- Abstract
- File upload
- Supplemental Materials 1
- Supplemental Materials 2
- Supplemental Materials 3...
- First Author (first name, last name)
- Second Author (first name, last name)
- Third Author (first name, last name)
- Additional Authors (text field)
