### ISSUE TITLE
Export IRC Research Centers & Institutes database content into CSV

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#108]
In preparation for exporting the old IRC content into the new Hub: 

1. Please send a CSV file of the IRC Research Centers & Institutes database (http://www.aashe.org/resources/academic-centers-sustainability/) to monika@aashe.org. 

2. Please create a second CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Research Centers & Institutes (http://aashe-hub-dev.herokuapp.com/browse/types/center/) as an example to generate this file. 

Considerations: 
- How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator? 
- Need to ensure that major changes to submission forms are done before completing step 2 above.
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by jamstooks** [comment]
This sounds like `education_academiccenter`

**Comment by charris2015** [comment]
I've sent the export for this database to Monika.

**Comment by charris2015** [comment]
Hey Monika, let me know if you want to close this ticket.

**Comment by monika-aashe** [comment]
Hey Chris. I'm thinking of leaving these types of tickets open until after we have successful migration (so I don't have to submit a similar ticket). @jamstooks , is there a benefit to submitting an issue for the migrating in of the lists, or is it okay for me to edit the issues already here?

**Comment by monika-aashe** [comment]
@charris2015 - Should I proceed even if there is no institution name column (just institution id). If this is what you need for the import, then I can probably proceed with what you sent.

**Comment by charris2015** [comment]
@monika-aashe unfortunately this export doesn't contain a field for institution name. @jamstooks I only have the information from the ISS which has the aashe_id and the salesforce_id in connection with the name of the institution. Would you happen to have a document containing the organization_id (in this export) that corresponds to an organization name?

**Comment by jamstooks** [comment]
`account_num` in the ISS db

**Comment by charris2015** [comment]
hey @monika-aashe,

I've sent an updated research center and institutes export with organization_id matching to a column containing the organization name.

**Comment by monika-aashe** [comment]
This list is done and ready for import. What's the best format for the file (csv or Excel) and who should I send to?
