### ISSUE TITLE
Create Migration CSV file for bulk adding Videos

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#109]
There is no IRC file that aligns with the Videos content type. However, we have videos in various places on our website (particularly webinars), so it would be useful to have a bulk upload.

Please create a CSV or Excel file showing exactly how the new Hub fields should be displayed in the csv that will be used to be imported into the Hub. Please use the current Hub content for Videos (http://aashe-hub-dev.herokuapp.com/browse/types/video/) as an example to generate this file.

Considerations:

How to display multiple organizations, topics, keywords, etc. - single column or separate column for each - if single column, what kind of separator?
Need to ensure that major changes to submission forms are done first.

**Comment by jamstooks** [comment]
@monika-aashe do you still need this? It seems like you have this solved with the other content types...

**Comment by monika-aashe** [comment]
Yeah, we can close this. I will probably just add the video files into the Hub production server manually rather than try to import a file - there will only be a few anyway.
