### ISSUE TITLE
The website field does not appear with a resource

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#114]
This applies to the following content types:

- Research Centers & Institutes
- Course Materials
- Outreach Materials
- Tools
- Publications

See comment below for detail on website field requirements.

**Comment by monika-aashe** [comment]
Website Fields by Content Type:
REQUIRED:
- Academic Programs
- Research Centers & Institutes
- Videos

CONDITIONALLY REQUIRED (either website or upload must be provided)
- Publications
- Course Materials
- Tools
- Outreach Materials

OPTIONAL:
- Case Studies

REMOVED ENTIRELY:
- Conference Presentations
- Photos

**Comment by jamstooks** [comment]
Is this referring to the published resource or to the form? I believe both are in good shape now.

**Comment by monika-aashe** [comment]
I believe it was on the submission forms - I think this is addressed now, but I haven't gone through and tested all forms again yet.
