### ISSUE TITLE
Calendar widget isn't optimal

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#116]
In some cases, only the year or month and year are available. It would be better to have Year | Month | Day - three separate fields all in a row, and only the year is required.

Currently this seems to apply to Conference Presentations and Publications.

**Comment by jamstooks** [comment]
# @monika-aashe @juliandsmith

This is a bit tricky for two reasons:

1. The way we store the date in the database
1. Our ability to order by date later

Ideally, we'd like to store all these fields as the same `date`object on the backend. That way the database can properly order them and understand their meaning. A database can understand a `date`, like `2015-12-1`, but when you break it up as year-only or year and month, then the database can only really understand those as integers and it's virtually impossible to order by `date` objects and integers together.

So, this leaves us with two options:

## Optimal Solution

Figure out a complicated way to store the dates as `date` objects, even if the day and or month wasn't provided and display them appropriately. For example 12/2015 would be stored as 2015-12-1 on the backend, but be displayed as Dec 2015 to the users. This will require some complex logic and a fair bit of work, but not necessarily not worth doing. I think it would be fun.

## Potential Workaround

Encourage our users to submit Jan 1st if they don't know the month or day, or the 1st of a month, if they don't know the precise date.

# @rerb and @bartTC:

I'm trying to think of the best way to implement the first solution (I haven't found an existing package yet). 

Basically, I think we'd have to create a custom ModelField, `VagueDateField` that was actually a front for four fields in the database [DateField, BooleanField (year), BooleanField (month), BooleanField (day)]. The default values for an empty day and month could be set on the field. A model might use it like so:

    class MyModel(models.Model):
        my_date_field = VagueDateField(day_fallback='1', month_fallback='1')
        # by setting the fallback values I've indicated that those fields aren't required

Then, this would have a custom `__repr__` and/or `__str__` methods that would display the date using the BooleanFields for reference. There might be some fancy footwork involved for things like:

    MyModel.objects.order_by('my_date_field')

We'd then create a custom form field and widget, `VagueDateField` that displayed this as three drop-downs: day, month, and year. Day and Month drop-downs would be optional if their fallbacks have set values.

Do either of you know of an existing solution for this? Have any suggestions about this approach?

This is a pretty complicated solution and I could see it being a bit of a rabbit hole. But, it definitely seems like a useful pattern that makes sense and could be shared. Plus, it'd be fun.

*Potential Pitfalls*

- migrations - support for django migrations might take some effort
- ordering - I have *no idea* how this gets implemented... it might be easy, but it might not.
- some date-formatting filters like [date](https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#date) and [naturalday](https://docs.djangoproject.com/en/1.8/ref/contrib/humanize/#naturalday) may not work as expected

Here are a few examples that are old and I think miss the mark a bit:
 - [django-flexibledatefield](https://github.com/JordanReiter/django-flexibledatefield) - uses a single PositiveIntegerField and doesn't have tests and has a text field as input instead of the drop-downs.
 - [django-yearlessdate](https://github.com/seddonym/django-yearlessdate) - just a form field, we want years.

**Comment by rerb** [comment]
Speaking as a wet rag, I'll say that this sounds like a lot of extra
complexity for little in return.  Somebody's got to guess the month and day
if they're not provided and we want to store the data as dates, so might
better be the user than us.  Might help text like, "Choose your best guess
if you don't know the exact date" be enough?


On Tue, Dec 1, 2015 at 12:19 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> @monika-aashe <https://github.com/monika-aashe> @juliandsmith
> <https://github.com/juliandsmith>
>
> This is a bit tricky for two reasons:
>
>    1. The way we store the date in the database
>    2. Our ability to order by date later
>
> Ideally, we'd like to store all these fields as the same dateobject on
> the backend. That way the database can properly order them and understand
> their meaning. A database can understand a date, like 2015-12-1, but when
> you break it up as year-only or year and month, then the database can only
> really understand those as integers and it's virtually impossible to order
> by date objects and integers together.
>
> So, this leaves us with two options:
> Optimal Solution
>
> Figure out a complicated way to store the dates as date objects, even if
> the day and or month wasn't provided and display them appropriately. For
> example 12/2015 would be stored as 2015-12-1 on the backend, but be
> displayed as Dec 2015 to the users. This will require some complex logic
> and a fair bit of work, but not necessarily not worth doing. I think it
> would be fun.
> Potential Workaround
>
> Encourage our users to submit Jan 1st if they don't know the month or day,
> or the 1st of a month, if they don't know the precise date.
> @rerb <https://github.com/rerb> and @bartTC <https://github.com/bartTC>:
>
> I'm trying to think of the best way to implement the first solution (I
> haven't found an existing package yet).
>
> Basically, I think we'd have to create a custom ModelField, VagueDateField
> that was actually a front for four fields in the database [DateField,
> BooleanField (year), BooleanField (month), BooleanField (day)]. The default
> values for an empty day and month could be set on the field. A model might
> use it like so:
>
> class MyModel(models.Model):
>     my_date_field = VagueDateField(day_fallback='1', month_fallback='1')
>     # by setting the fallback values I've indicated that those fields aren't required
>
> Then, this would have a custom __repr__ and/or __str__ methods that would
> display the date using the BooleanFields for reference. There might be some
> fancy footwork involved for things like:
>
> MyModel.objects.order_by('my_date_field')
>
> We'd then create a custom form field and widget, VagueDateField that
> displayed this as three drop-downs: day, month, and year. Day and Month
> drop-downs would be optional if their fallbacks have set values.
>
> Do either of you know of an existing solution for this? Have any
> suggestions about this approach?
>
> This is a pretty complicated solution and I could see it being a bit of a
> rabbit hole. But, it definitely seems like a useful pattern that makes
> sense and could be shared. Plus, it'd be fun.
>
> *Potential Pitfalls*
>
>    - migrations - support for django migrations might take some effort
>    - ordering - I have *no idea* how this gets implemented... it might be
>    easy, but it might not.
>    - some date-formatting filters like date
>    <https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#date>
>    and naturalday
>    <https://docs.djangoproject.com/en/1.8/ref/contrib/humanize/#naturalday>
>    may not work as expected
>
> Here are a few examples that are old and I think miss the mark a bit:
>
>    - django-flexibledatefield
>    <https://github.com/JordanReiter/django-flexibledatefield> - uses a
>    single PositiveIntegerField and doesn't have tests and has a text field as
>    input instead of the drop-downs.
>    - django-yearlessdate <https://github.com/seddonym/django-yearlessdate>
>    - just a form field, we want years.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/116#issuecomment-161038116>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

<http://www.aashe.org>
------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
I'd be okay with the help-text workaround. I'll add to tomorrow's meeting agenda to see if Julian agrees. Speaking of which, since Bob is getting more involved in the project implementation, would it make sense for him to start joining the calls? @jamstooks @rerb

**Comment by bartTC** [comment]
Thats the approach I'd have in mind too @jamstooks 
I think thats the better way for now @rerb.

> four fields in the database `[DateField, BooleanField (year), BooleanField (month), BooleanField (day)]`. 

I think only three fields are necessary, since the year is mandatory. It's a `forms.Multiwidget`. We always store a full date in the database, which we use to order, but always display based on the additional Booleanfields. I don't see issues with migration, nor ordering. It's just a problem of the template output. 

But yes, what @rerb says, I wonder if this is an actual issue and it's so often people can't remember an exact date (or don't want to guess).

**Comment by monika-aashe** [comment]
There's one other issue pertaining to date that I found. Suppose you are going to enter an older publication or conference presentation (e.g. 2002). Right now, it appears that you have to scroll through each month to get to the correct date (12 clicks per month per year adds up to a lot of clicks!) I know there is a short-cut where you can manually type in the date, so we should probably add that to the helptext unless there is another workaround.

**Comment by jamstooks** [comment]
@rerb - I think you're right... although it'd be a cool project (I'm surprised it doesn't already exist). We'll see what Julian says on the call.

@bartTC - Good point. I guess I was thinking there might a flexible option to have the year be the current year or something. Your suggestion of the Multiwidget seems useful, but we'd probably still want a custom model field to obscure the boolean fields from the model definition and handle printing of the field.

@monika-aashe - I don't think we need two developers on the calls. I think it makes more sense for Bob to spend his time on issues over meetings.

**Comment by jamstooks** [comment]
@monika-aashe - that widget may support another button for scrolling by year, right now it just has:

    <  >

but we could add extra buttons that scroll in 12-month increments:

    <<  <  >  >>

That feature might be available. I've created another ticket for that request #117.

**Comment by jamstooks** [comment]
Ok, so as much as I'd like to create this `vague-date-field` app, I don't think we have time for this right now and should default to the help text option. Bob suggested this:

> "Choose your best guess if you don't know the exact date"

Would you like to go with something like that? Maybe this is something we can come back to down the road...

**Comment by monika-aashe** [comment]
@juliandsmith - I'm okay with making this 1d if you are

**Comment by juliandsmith** [comment]
I'm hesitant about pushing this one off because I think it impacts many of the publications we'll be importing. Changing it after launch seems like it could create some complications between resources submitted before and after the change too. What do you think @jamstooks?

**Comment by monika-aashe** [comment]
I don't think it matters for imports, if we don't know the date, we would enter it as 12/1/15, which is how it would be stored if someone only entered month and year anyway, right?

**Comment by juliandsmith** [comment]
I guess so, but if we don't have the functionality Ben was proposing, the system won't know that we didn't have the full date so it would show 1/1/15 for resources that we wanted to show up only as 2015. This obviously isn't the end of the world but there are a lot of publications for which we don't have the exact date. I really don't like the imprecision of it but I like delaying the launch even less so I guess I'm okay to move later.

**Comment by monika-aashe** [comment]
Oh, right. I think Ben said there's a way to do mass edits though?

**Comment by monika-aashe** [comment]
Decided to postpone. Can add logic "if you don't know the month and year, enter January 1; if you don't know the exact date but know the month and year, enter the first day of the month"

**Comment by dodget** [comment]
Wow, what a thread. After three years, can we still say this is something that we are concerned with? Enough to devote our precious moments to?

**Comment by juliandsmith** [comment]
LOL. Reading through this thread made me nostalgic. At this point, I'm okay to close this and move on.

**Comment by monika-aashe** [comment]
Same here. I don't think it has been problematic. We already implemented the help-text solution: 

"Enter the date when this resource was created, founded, published, or presented. If you don't know the exact date, choose the first day of the month. Use January 1 if you only know the year. You can use the calendar widget or type in a date in YYYY-MM-DD format."
