### ISSUE TITLE
Aligning Bulletin topics in RSS feed

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#119]
Need to align Bulletin Stories to Hub topics, and only those that match will be displayed in the RSS feed for that particular topic in the Hub. 

DECISION: We will update the Bulletin topics to match the Hub. Will require some work from Crystal and Bob.

**Comment by monika-aashe** [comment]
Plan B: In the event that we're unable to make the topics in the Bulletin identical, here's how the alignment should work:
Decision on alignment of Bulletin Categories with Hub Topics:
Alignment will mirror perfectly for all except the following: 
Dining Services -> Food & Dining
Coordination Planning & Governance -> Coordination & Planning
Assessments & Ratings -> Coordination & Planning
Funding -> Investment
Campus Sustainability in the Media -> Coordination & Planning
Policy & Legislation -> Public Engagement

**Comment by monika-aashe** [comment]
This was pulled from a related ticket, #57

**Comment by rerb** [comment]
Posts recategorized.
