### ISSUE TITLE
Submission Form Field Chronology

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#120]
There should be a consistent chronological order of fields that follows the following pattern on all submission forms. This should be:

1. Title
2. Description (called "Description or Abstract" for Conf. Pres. and Publication; "Project Overview" for case studies; "Caption or Description" for Photographs) 
3. Organization(s) 
   * -------- break (horizontal line)
4. sustainability topic
5. academic discipline
6. office or department
7. keywords
   * -------- break (horizontal line)
8. Author Info (if relevant)
   * -------- break (horizontal line)
9. Unique fields per content type (only some content types)
   * -------- break (horizontal line)
10. Website (include everywhere but Conf. Pres., Photographs)
11. Image/document upload (only some content types)
12. Affirmation of ownership (only some content types)
   * -------- break (horizontal line)

See revised summary tab for more info (rows 23-26): https://docs.google.com/spreadsheets/d/1ADsnCZXKU1lhA4GHc2xhsY5ddLRi7kgvYJLSTHZKlmw/edit#gid=935008516

**Comment by monika-aashe** [comment]
Separated from #73

**Comment by jamstooks** [comment]
Fixed in this commit: 12765b054e701a637a357a1c51e28cb03d370f77. Will come over in a pull request that includes #73.
