### ISSUE TITLE
Redirecting old IRC URLs to new Hub URLs

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#123]
We need to to unpublish all old IRC webpages that have Hub-related Content. For example:

http://www.aashe.org/resources redirects to hub.aashe.org
http://www.aashe.org/resources/case-studies redirects to hub.aashe.org/browse/types/casestudy/

Issues: 
- need to use the actual urls (not dev site)
- need to figure out how to organize those resources that aren't in the Hub and are still live on the IRC site

**Comment by jamstooks** [comment]
I think it might be worth narrowing these down even more... ideally, each individual link should have a new link in the hub. That will really help transfer the page rank. Is there a way we could collect all of these in a spreadsheet or something?

**Comment by jamstooks** [comment]
@monika-aashe is this list something you or someone else on programs can help collect?

**Comment by monika-aashe** [comment]
Here is the redirect file as of now:
https://docs.google.com/spreadsheets/d/1h7BMrjE3AMBFtAv0PWg8MpZJ8Xf8TZFWse8Xr-KGVtw/edit#gid=0

We are keeping resources.aashe.org for now since there is still a lot of valuable content there.

**Comment by monika-aashe** [comment]
Would be great to have the "submit an academic program" redirect done ASAP. I'm getting submissions, and then having to transfer them to the Hub manually. 

http://www.aashe.org/resources/academic-programs/add/

**Comment by monika-aashe** [comment]
Here are the top priorities for redirects - we want to ensure folks aren't going to the wrong place to submit for AASHE Awards, and we are still getting frequent Academic Program adds under the wrong page:
"submit an academic program" - change 
- Academic Program Submission - change http://www.aashe.org/resources/academic-programs/add/ to http://hub.aashe.org/submit-resource/academicprogram/
- Submit Student Research - change http://www.aashe.org/resources/student-research/submission-form to http://hub.aashe.org/submit-resource/publication/
- Submit a Case Study - change http://www.aashe.org/resources/case-studies/submit to http://hub.aashe.org/submit-resource/casestudy/

**Comment by jamstooks** [comment]
Submission forms:

- [x] Academic Programs
- [x] Student Research
- [x] Case Studies

- [ ] All others

**Comment by monika-aashe** [comment]
Looks like the redirects are making a pretty huge impact!
<img width="1016" alt="screen shot 2016-04-14 at 9 15 33 pm" src="https://cloud.githubusercontent.com/assets/15214797/14548621/7c228070-0286-11e6-81c3-301d37cbc772.png">

<img width="1020" alt="screen shot 2016-04-14 at 9 18 02 pm" src="https://cloud.githubusercontent.com/assets/15214797/14548625/82790eee-0286-11e6-91f6-a012b8683fff.png">

**Comment by jamstooks** [comment]
So I've been working on the conference presentation redirects and noticed something. I assume this is deliberate, but it looks like these used to be public, but aren't anymore.

 - [An old listing page](http://www.aashe.org/resources/conference/search?keys=&field_stars_category_value%5B%5D=306&field_session_materials_list=All)
 - [An old presentation page](http://www.aashe.org/resources/conference/sustainable-course-sustainability-0)
 - [The current listing page with warnings](http://hub.aashe.org/browse/types/presentation/) (if you're not logged in)

In the context of redirecting individual pages, this means that a lot of pages that are indexed by google will now redirect to pages that require login. This isn't the end of the world, but I thought I'd raise the point and see if y'all had thoughts on this...

**Comment by juliandsmith** [comment]
All of these links redirect to the Hub now but I think you are referring to the fact that conference presentations used to be public but aren't anymore. As you guessed, this is intentional and is part of the effort to enhance member value. 

Unfortunately, it does mean that a lot of individual pages that were indexed by Google won't be anymore but I'm not sure there's much we can do about this.

**Comment by jamstooks** [comment]
Ok, well then I'm going to leave these as is then. We might as well consolidate the page rank in the index page at this point.

**Comment by jessicaaasheaashe** [comment]
Does this mean I can now delete these from the Drupal site?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, Apr 15, 2016 at 3:58 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> Closed #123 <https://github.com/AASHE/hub/issues/123>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/123#event-629440830>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Hey, there is one redirect that shouldn't exist:

On the [Resource Center Home Page](http://www.aashe.org/resources), The link to Dining Services should still take you to http://www.aashe.org/resources/dining-services, but it instead redirects to [Case Studies filtered by Food & Dining](http://hub.aashe.org/browse/types/casestudy/?search=&topics=food-dining&content_type=casestudy&country=). 

Can this go back to the original link?
