### ISSUE TITLE
Add "edit this resource" link to resource pages when logged in with admin account

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#128]
Add a direct link to edit a resource on the individual resource pages when logged in as user with editing privileges. 

The intent of this change is to make it easier to make quick fixes when browsing the Hub. Right now, you have to log into the admin side of the site and find the resource to make changes.

**Comment by jamstooks** [comment]
Done. See example here:

https://aashe-hub-dev.herokuapp.com/browse/photograph/76/Test-Photos-from-Ben
