### ISSUE TITLE
Update colors to use Brand Guidelines

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#129]
Login/Membership Required buttons are an orangey color that is not within our brand guidelines.  Suggest changing color to fit with brand guidelines.

We'd like to see the AASHE light green for these buttons and accents (Web: CEDC45). Please share with Jessica when a prototype is available in case the color needs to be switched.

**Comment by jamstooks** [comment]
See page 13 or the [Brand Book](https://drive.google.com/a/aashe.org/file/d/0B5SGLet-uzyTOTFCaURFUHh3RkU/view)

**Comment by jamstooks** [comment]
I think there might be an argument for breaking away from the brand guidelines with error notifications. We have talked about extending our color palette during our new website design, but if I'm held to using just this handful of colors to fit all our needs (beyond just general theming), we're going to be **very** limited. Orange is a generally recognized "error case" color...
