### ISSUE TITLE
Search and filter of ALL resources

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#133]
Is there a way to browse and filter on all resources in the Hub? It seems like you have to either select a topic or content type and then browse, or use the search to get a sample. It would be great if there was a way to generate a list of all current Hub resources (e.g. type "all resources" in search) to allow folks to filter on the entire Hub.

**Comment by jamstooks** [comment]
Depending on complexity and time, this issue may get pushed back a phase... per a discussion with @juliandsmith . It may not, but I thought I'd make not here so we can plan.

**Comment by juliandsmith** [comment]
Just a note that searching for "*" does not (currently at least) produce a full list of everything in the Hub but leaving the search box completely empty and clicking go seems to do the trick. Right now, "*" returns 341 results while leaving the search box blank generates 518 results. Leaving the search box blank it actually more intuitive than searching for * so this seems fine to me. I just wanted to note this in case it is an indication of something not working as intended.
