### ISSUE TITLE
Change location of helptext.

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#135]
For all helptext, we would like to move the text to be between the field title and the field content box. Right now it appears below the content box. This is not ideal for two reasons: 1) folks may not read it until after they add their content; 2) It is not always obvious whether the helptext applies to the field above or below. 

Example: https://aashe-hub-dev.herokuapp.com/submit-resource/casestudy/

**Comment by jamstooks** [comment]
Changed in 33fe117b20ff280237441f66c1a8ce3c5f708222. Pull-request to come.
