### ISSUE TITLE
Change "Membership required" text

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#136]
We'd like to change the text, "You can register for membership here" to "Not a Member? Join Here."

<img width="1158" alt="screen shot 2015-12-04 at 3 23 16 pm" src="https://cloud.githubusercontent.com/assets/15214797/11667513/1e989906-9dc0-11e5-946c-779bc2bffc4c.png">

**Comment by jamstooks** [comment]
Who ya gonna call? [django-block-content](https://github.com/AASHE/django-block-content)... example on homepage.
