### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#137]
Hub pages don't seem to have a favicon currently. We should add the generic AASHE favicon we use on our main site.

**Comment by juliandsmith** [comment]
Reopening because I'm not seeing the Favicon in either Chrome or Firefox and Ben said the code should be up-to-date.

**Comment by baronvonvaderham** [comment]
Sorry, I wrongly assumed the tag was already in there and the file was just missing. Fixed the tag in base.html. 2041dbaaaa00b9a6c0cc9f037c1a77cc7f61b507

Pushed up to heroku instance. Also needed to run a collectstatic to find the new image. Seems to be working now.
