### ISSUE TITLE
On behalf of a single browse view...

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#139]
We have several browse views that are essentially the same. For example:

**Browse Curriculum Toolkit, filtering on Academic Program**
[/browse/topics/curriculum/?content_type=academicprogram](https://aashe-hub-dev.herokuapp.com/browse/topics/curriculum/?content_type=academicprogram)

**Browse Academic Program, filtering on Curriculum**
[/browse/types/academicprogram/?content_type=academicprogram](https://aashe-hub-dev.herokuapp.com/browse/types/academicprogram/?content_type=academicprogram)

**Search (if we were to remove the requirement for a search keyword)**
[/browse/?search=test&topics=curriculum&content_type=academicprogram](https://aashe-hub-dev.herokuapp.com/browse/?search=test&topics=curriculum&content_type=academicprogram)

Is it worth consolidating these at all? Here's what I've got for pros/cons right now:

**Pros**
- reduce the number of views to maintain and update going forward
- might improve user experience
  - allows users to quickly switch between topics or content types
  - in some pages the content-type and topic filters aren't there (consistency issue)

**Cons**
- This might take away from the toolkit pages

Anyway, would love your feedback, @monika-aashe @juliandsmith @peltonc

**Comment by bartTC** [comment]
Those 3 views are backend-wise just one view. Just rendered with a different template.

And we already have exactly the same filter form for each view. For the topics view we hide the topic selector field in CSS: https://github.com/AASHE/hub/blob/master/hub/static/scss/base.scss#L249-L257 Same for content type. 

The search term isn't required too, but we enforce it here: https://github.com/AASHE/hub/blob/master/hub/apps/browse/views.py#L77-L85 If you'd remove that then /browse/ would simply show everything. 

By the way, you can achieve the same if you search for `*` now: http://aashe-hub-dev.herokuapp.com/browse/?search=*

**Comment by monika-aashe** [comment]
Whatever we decide, we need to ensure that we can custom-add sponsors to sustainability topics and/or content types.

**Comment by monika-aashe** [comment]
Moving to bike rack.

**Comment by dodget** [comment]
This seems to be a stale conversation. Closing.
