### ISSUE TITLE
Checking "I am an author" defaults to blank instead of "AASHE"

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#141]
This is happening for Monika and Julian when logged in as AASHE staff. Also happening when Monika logs in under miurbanski@yahoo.com (For this one, the organization should either be blank, or show up as Frostburg State University).

**Comment by monika-aashe** [comment]
1/9/16 update: Now, the author field shows up as blank instead of AT Still. Could be because AASHE no longer shows up in the dropdown (see latest comment under #

**Comment by jamstooks** [comment]
Hey, @rerb - any idea how we can get AASHE into the list of orgs in the ISS even if SF forces it to have the `exclude_from_website` flag? Could we simply add an exception for that `account_num`?

**Comment by rerb** [comment]
@jamstooks - I wonder where else `exclude_from_website` is used?

If we hard-code AASHE to be `exclude_from_website = False` in the ISS sync, any other system that uses `exclude_from_website` (Drupal?) will misbehave.

The other option is to flip the bit closer to the Hub.  Maybe add an option to the `sync_iss_organizations` management command?  

What would be a good name for that option?

**Comment by rerb** [comment]
@monika-aashe - Where did the "I am author" checkbox go?  I can't see it.

**Comment by monika-aashe** [comment]
It should be on the submission forms - here's an example: https://aashe-hub-dev.herokuapp.com/submit-resource/publication/

And screenshot (blue button):
<img width="817" alt="screen shot 2016-02-01 at 3 06 47 pm" src="https://cloud.githubusercontent.com/assets/15214797/12729588/903b2852-c8f5-11e5-94d8-dbd217c59569.png">

**Comment by rerb** [comment]
Ahh, I thought it was supposed to be on every type of submission -- when I
didn't see it on the first couple I looked at I got confused.

Thanks!

On Mon, Feb 1, 2016 at 3:08 PM, monika-aashe <notifications@github.com>
wrote:

> It should be on the submission forms - here's an example:
> https://aashe-hub-dev.herokuapp.com/submit-resource/publication/
>
> And screenshot (blue button):
> [image: screen shot 2016-02-01 at 3 06 47 pm]
> <https://cloud.githubusercontent.com/assets/15214797/12729588/903b2852-c8f5-11e5-94d8-dbd217c59569.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/141#issuecomment-178165873>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals and 
reviewers now open <https://ww4.aievolution.com/ash1601>!

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Oh right, it's only  on some of the submission forms!

**Comment by rerb** [comment]
@monika-aashe would you check this out and see if it's working (pre-filling "AASHE") for you now?  It's not working for me, but I think my Drupal data might be messed up.  Hoping it works for others now.

**Comment by monika-aashe** [comment]
It's still blank for me.

**Comment by monika-aashe** [comment]
FYI, since AASHE can now be selected from the dropdown, we have a workaround. While it would be nice for AASHE to automatically autopopulate when staff are submitting a resource, we can simply add the AASHE in later. I'm fine with delaying this fix until a later milestone.

**Comment by rerb** [comment]
Is it acceptable if the organization appears as "AASHE (PA)"?

**Comment by dodget** [comment]
I believe this works in production. Closing.

**Comment by monika-aashe** [comment]
Yep, I think it was resolved when we switched to Membersuite.
