### ISSUE TITLE
ISS data export with org name and org ID

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#142]
Monika needs a a list of all organizations in our ISS database (campuses, businesses, all other orgs) by full name - I can get the campus list in Salesforce but not a list that also includes businesses and other orgs. 
- Also need list of all organizations names with the 3- or 4-digit organization ids - two column layout.  

Excel or csv would be perfect. Names and IDs are most important, but it's okay if there's additional info such as org type, etc.

**Comment by charris2015** [comment]
Hey @monika-aashe,

I've sent you a spreadsheet containing the org id's and the org names.

-Chris

**Comment by monika-aashe** [comment]
Thanks Chris,
This looks incomplete - what I need is a list that has every institution and organization that is in our ISS database. There should be thousands instead of 167. Also, there are a few duplicates (Arizona State is listed 4 times). 

Can you please resend?

Thanks!
Monika
