### ISSUE TITLE
Filter labels: make "Sort" the same font as "Filters".

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#148]
Pulled from #38.

**Comment by dodget** [comment]
This actually appears complicated.
The `sort by` function was built as a "filter." So it has `Filter` as its parent just like any of the other options in the filter form, and what we see is the form that is generated.
To get the requested change is doable, but will take quite a bit of work. Is the time investment vs benefit tipped the right way? I don't think so.

**Comment by juliandsmith** [comment]
Ok, let's skip it. I'll close this one. Thanks!
