### ISSUE TITLE
Admin: Bulk actions

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#15]
Mass set/unset of 
  - [x] ~~Favorites~~ No longer needed, they are now part of Topics.
  - [ ] Published
  - [ ] Permission

**Comment by monika-aashe** [comment]
@jamstooks  Not sure what this is referring to, moving to 1c.

**Comment by monika-aashe** [comment]
I think this has been addressed. It's the bulk action feature in admin: 
<img width="495" alt="screen shot 2016-03-02 at 12 38 44 am" src="https://cloud.githubusercontent.com/assets/15214797/13451681/3661d52a-e00f-11e5-9c32-778d8254d14a.png">
