### ISSUE TITLE
Special Character "&" not displaying correctly in Bulletin RSS feed

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#150]
Related to #119 - 
Thanks for fixing the RSS feed for the Bulletin! It looks like the feed does not display the "&" character correctly. In the following link, (http://aashe-hub-dev.herokuapp.com/browse/topics/research/), one of the stories is listed as "U Virginia Completes Nitrogen &Amp; Carbon Footprint Food Study" - the "&Amp;" should simply be "&". 

I didn't see other special characters that are displaying incorrectly.

**Comment by rerb** [comment]
Fixed in https://github.com/AASHE/hub/commit/684ff35f3696a5de746b4aff67acc27fe0deee6a.
