### ISSUE TITLE
Fix country field in test_filter

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#151]
https://github.com/AASHE/hub/blob/2ff0ac7930030e397fd6220db34d7d4063dc23ce/hub/tests/test_filter.py#L43-L46

**Comment by monika-aashe** [comment]
@jamstooks - is this going to make it possible for individuals to select multiple countries? Right now, it's only possible to select one country at a time.

**Comment by jamstooks** [comment]
This was tied to a larger issue of importing `GenericFilterSet` in browse/views.py. The `__init__` methods on many of the filters access the database. I've moved the `import` into the view and that has fixed the issue.
