### ISSUE TITLE
Temporary access to Hub request form

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#154]
The team has agreed to the following language: "AASHE wishes to encourage research that advances sustainability in higher education, even among institutions that are not yet AASHE members. For this reason, students or faculty members conducting sustainability research who do not currently have access to the Hub can request temporary access by filling out the Hub Access Request form."

We'd like to implement a temporary access form that can be linked to our public Hub documents. The form should be modeled after the STARS data displays access form: https://stars.aashe.org/cfm/dd-access/

The form should encourage support for AASHE membership in some way (e.g. request submitter to send a letter to an administrator or executive requesting AASHE membership or, acknowledgement that "AASHE may mention this request in periodic membership inquiries to administrators at your organization"). Ideally, M&M will get copied automatically (membership@aashe.org) on any such requests.  

The project team will discuss again to decide on what fields to include in the form.

**Comment by monika-aashe** [comment]
The form has been checked by Julian and M&M and is ready to go: https://docs.google.com/document/d/1wdjyR_snBsDSCf2vzf64fpKC3S_oGivp2_bGPmbKzJM/edit

**Comment by monika-aashe** [comment]
Goal is to have this implemented by 6/24/16 so we can give NREL access to the Hub.

**Comment by jamstooks** [comment]
I've created the functionality that lets you grant a specific user temporary access. That can be done [though the admin](https://hub.aashe.org/_ad/access/temporaryuser/) now.

I haven't created the form yet, but that got me thinking about it. Would we want to create a more generic form for access to various member resources? I'm picturing a google form where people request access to STARS data displays and the Hub...

I'm happy to create the form though, I was just thinking that a google form would be quicker and easier and might be able to serve multiple purposes...

**Comment by monika-aashe** [comment]
The form can exist anywhere, but it would be pretty important to enable automatic notification to resources@aashe.org whenever someone submits a temporary access request. I don't have much background with Google forms so I'm not sure if that's possible?

**Comment by juliandsmith** [comment]
Yes, Google forms can be set up to have [email notification](https://productforums.google.com/forum/#!topic/docs/BM5DMUvY7nE). I like the idea of saving Ben some time and putting it in a format that is easy for programs staff to modify/manage without having to bug IT!

**Comment by jamstooks** [comment]
Ok, once this form is ready can you let me know where to link from? Do we need another page, or could there simply be another link at the bottom that goes directly to the google form?

**Comment by monika-aashe** [comment]
So the form can be accessed [here](https://docs.google.com/a/aashe.org/forms/d/1oqkF0LteNsSPwEiL3dO_-FGa54BxPQP0aGMggAJQRRo/viewform)

I also added some info about it to the [About page](https://hub.aashe.org/about/). If you all think it would help, we can also add a link to "Request Access" in the footer.

**Comment by jamstooks** [comment]
This looks great! Thanks :)
