### ISSUE TITLE
Author fields and "I am an author" improvements

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#158]
The issue is that by default, there is one empty field whenever author is a required field. However the majority of submitters are the authors, so they can simply select "I am an author" to auto-populate. The problem is, unless they first clear the blank author field with the minus sign, clicking "I am an author" will auto-populate the last field instead of the first. However only the first field is required, so this shows up as an error when submitting. 

Here is a screenshot:
<img width="785" alt="screen shot 2016-01-08 at 11 51 23 am" src="https://cloud.githubusercontent.com/assets/15214797/12203744/949323d2-b5fe-11e5-8296-e3fcd8081cfa.png">

Suggestion: For all content types that require at least one author, lets remove the initial blank author field. 

Related suggestions - while not necessary, these would be big improvements:
- Can we update the title "Authors" to "Author(s)" to make it clear that only one is needed and/or required? (All Content Types)
- Can we move the "I am an author" button up above the text fields? (perhaps to the right of Author(s) with red *) This would ensure that folks see it before entering in all of their data. It's such an awesome, useful feature, but right now, it is kind of hidden at the very end.

**Comment by monika-aashe** [comment]
More feedback from Crystal. I am an author feature is a bit confusing. The "check" icon makes it seem like this is always checked. Can we do away with this icon or change it to a pencil icon? 

Crystal's recommendation is to make the "I am an author" option appear once you expand the box, kind of like "use same address as billing address" does on shipping form.

**Comment by jamstooks** [comment]
How about a "+" (plus) icon and something like "I am an Author, add me" for the text? Or "Add me as an Author?"

I don't like the click once to expand and then again to populate option for two reason: multiple clicks and it adds a lot of complexity to the code...

**Comment by jamstooks** [comment]
I've added the + icon, which should help. I'm going to leave the rest for now to see if we get more feedback during out review period.

**Comment by monika-aashe** [comment]
This is much less confusing, thanks! I think additional refinements can come when we soft-launch if we find the feature is confusing to others or not being used correctly. Thanks!
