### ISSUE TITLE
No Reverse Match error when trying to submit Research Center or Institute

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#163]
Not able to submit Research Center & Institute form due to NoReverse Match error. 
http://aashe-hub-dev.herokuapp.com/submit-resource/center/

**Comment by monika-aashe** [comment]
While the new centers do show up in admin for approval and can be approved, when they are approved, a similar error shows up when you try to view it. http://aashe-hub-dev.herokuapp.com/browse/center/77/test

**Comment by juliandsmith** [comment]
Same problems occurred when submitting a new outreach material, FYI.

**Comment by jamstooks** [comment]
Ok, this is fixed and the url has been updated to:
http://aashe-hub-dev.herokuapp.com/browse/centerandinstitute/77/test
