### ISSUE TITLE
Fix typo on Submit a Resource Page and make editable

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#166]
On Submit a Resource (http://aashe-hub-dev.herokuapp.com/submit-resource/), "Guidelines" is misspelled and is instead "Guidlines for submitting resources"

Make easily editable by staff if possible. We will eventually add a hyperlink to a submission guidelines document.

**Comment by jamstooks** [comment]
This sounds like a job for... django-block-content! :)

**Comment by monika-aashe** [comment]
Thanks for making editable! Is it possible to edit and incorporate a URL in that edit? Specific code for example? This particular blurb needs to link to something like this: https://docs.google.com/document/d/1xvN4WlfwOqfsdSlw5P6A3xE4nWszbXeQ7zR59g3FL0s/edit

**Comment by baronvonvaderham** [comment]
You would have to confirm with Ben, but I do believe editing the block 
content supports markdown.

**Comment by monika-aashe** [comment]
I can confirm that it works :+1:
