### ISSUE TITLE
Topic icon: fa-balance-scale

### ISSUE THREAD

**Issue by peltonc** [AASHE/hub#168]
Unable to get fa-balance-scale to display as a topic icon:
http://fortawesome.github.io/Font-Awesome/icon/balance-scale/

**Comment by jamstooks** [comment]
are you setting the value to "fa fa-balance-scale" ? you need that extra "fa" in there.

**Comment by monika-aashe** [comment]
That is what it's set to right now, but still no scales. http://aashe-hub-dev.herokuapp.com/admin/metadata/sustainabilitytopic/6/

**Comment by jamstooks** [comment]
Ok, I'm seeing the issue. [fa-balance-scale](http://fortawesome.github.io/Font-Awesome/icon/balance-scale/) was created in Font Awesome version 4.4 and [Unity v1.8 uses 4.2](http://htmlstream.com/preview/unify-v1.8/shortcode_icon_fa.html)

I'll work on updating to [Unity 1.9](http://htmlstream.com/preview/unify-v1.9/shortcode_icon_fa.html) to get this in there.

**Comment by jamstooks** [comment]
Ok, I've updated the theme, so it's in there now;
