### ISSUE TITLE
There's an hourly scheduled job to rebuild the search index -- suppose we want to remove this before we go into production?

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#176]

**Comment by jamstooks** [comment]
I was wondering about this. How heavy is that process? Would it make sense to go to a real-time haystack signal processor to update the index instead of rebuild it?

**Comment by rerb** [comment]
I guess I assumed the hub was doing real-time updates to the index, since
that's what the bulletin is doing. I thought that this scheduled job was
just something for during development to pick up changes in the search
templates or something.

Don't know how heavy the process is, but I know it deletes the existing
index before rebuilding it -- do we need to worry about searches that might
occur when the index is gone or rebuilding?

On Tue, Jan 19, 2016 at 1:38 AM, Benjamin W Stookey <
notifications@github.com> wrote:

> I was wondering about this. How heavy is that process? Would it make sense
> to go to a real-time haystack signal processor to update the index instead
> of rebuild it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/176#issuecomment-172755543>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals and 
reviewers now open <https://ww4.aievolution.com/ash1601>!

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment]
I think you're right, we should go with the real-time updates. Since you have experience with this, would you mind giving this a go?

I'm thinking the signal should only happen after a resource is approved (marked as published). See the `ContentType.save` method for example. I'm hoping this is pretty easy...

**Comment by jamstooks** [comment]
Hey, @rerb. Any idea why I can't change the [AASHE Account in Salesforce](https://na7.salesforce.com/001A0000004PZl9/d?retURL=%2F001A0000004PZl9&nooverride=1) to uncheck `exclude from website`.

**Comment by rerb** [comment]
Has this always been checked?  Maybe there's a workflow rule that checks it
for AASHE.

On Tue, Jan 19, 2016 at 2:52 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> Hey, @rerb <https://github.com/rerb>. Any idea why I can't change the AASHE
> Account in Salesforce
> <https://na7.salesforce.com/001A0000004PZl9/d?retURL=%2F001A0000004PZl9&nooverride=1>
> to uncheck exclude from website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/176#issuecomment-172966334>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals and 
reviewers now open <https://ww4.aievolution.com/ash1601>!

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
> I'm thinking the signal should only happen after a resource is approved (marked as published). See the ContentType.save method for example. I'm hoping this is pretty easy..

Default Haystack realtime signal processor listens for save and delete on all models, then updates index if the model's searchable.  Rather than write our own signal processor to only handle ContentType objects, let's use the provided solution.  The overhead shouldn't be bad in such a small-number-of-concurrent-users and small-number-of-writes-to-reads app like the Hub, and we don't have to spend any more of our complexity budget.

Anyway, that's what I did.  :-)   Re-open and disagree and I can write a custom signal processor.

**Comment by jamstooks** [comment]
Hey @rerb, I don't think this is working... see #197.

**Comment by rerb** [comment]
Created a new Academic Program and it got indexed correctly.  Maybe we needed to rebuild the index after turning on the signal processors and we didn't do that.

Working now.
