### ISSUE TITLE
Add featured resources for each topic

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#183]
Each topic should have at least a couple featured resources to show off this feature.

**Comment by juliandsmith** [comment]
Every topic has at least one featured resource now and most have at least two. The following topics only have one featured resource however: Public Engagement, Purchasing, Diversity & Affordability. 

I have some ideas for Purchasing and Diversity & Affordability that I'm going to try to get to, but I'd welcome assistance in finding other featured resources in any of these categories.

**Comment by peltonc** [comment]
Hi Julian,

How would you feel about these as featured resources?

Public Engagement
Town Gown Sustainability: How to Develop a Vibrant Partnership
<http://hub.aashe.org/browse/presentation/9364/town-gown-sustainability-how-to-develop-a-vibrant-partnership>
Partnerships for Developing Community Sustainability Indicators
<http://hub.aashe.org/browse/presentation/9531/partnerships-for-developing-community-sustainability-indicators>

Purchasing
GSA Green Procurement Compilation <http://www.gsa.gov/portal/content/198257>
Challenge the Label <http://www.isealalliance.org/challenge>(ISEAL)

Diversity & Affordability
College Affordability and Transparency Center
<http://hub.aashe.org/_ad/content/tool/14578/>


On Wed, Mar 30, 2016 at 1:12 PM, juliandsmith <notifications@github.com>
wrote:

> Every topic has at least one featured resource now and most have at least
> two. The following topics only have one featured resource however: Public
> Engagement, Purchasing, Diversity & Affordability.
>
> I have some ideas for Purchasing and Diversity & Affordability that I'm
> going to try to get to, but I'd welcome assistance in finding other
> featured resources in any of these categories.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/183#issuecomment-203401290>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by juliandsmith** [comment]
I tend not to like featuring conference presentations (because how valuable can a powerpoint really be?) but I haven't found anything better so I'm good with these. ISEAL seems good but maybe feature SPLC's guidance instead of GSA? 

The College Affordability and Transparency Center seems like a tool more for prospective students than for our primary constituents. Demos has a [bunch of publications](http://www.demos.org/publications?field_related_issues_nid=856) that I think would be good but I haven't had time to fully review and decide which one to feature. I'd like to find a better diversity resource too, ideally.

**Comment by juliandsmith** [comment]
This seems to be complete now so I'm closing this ticket.
