### ISSUE TITLE
Make links noticeable in Content Type descriptions

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#187]
Currently, they only display as links if you hover over the text.

Example: https://aashe-hub-dev.herokuapp.com/submit-resource/casestudy/ 
The words, "Awards program" should be linked in "All case studies are automatically entered into AASHE’s annual Awards program."

**Comment by juliandsmith** [comment]
This problem also appears to affect links that are included within a list. For example, most of the links on the STARS data pages appear as regular text unless one hovers over them: http://hub.aashe.org/browse/topics/campus-engagement/#stars-panel
