### ISSUE TITLE
There are logical duplicates in the Countries list

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#189]
E.g., US and United States of America.

**Comment by rerb** [comment]
See also Mexico and Australia.

**Comment by rerb** [comment]
@monika-aashe You commented on ticket https://github.com/AASHE/hub/issues/46,

> Relevant to Country filter: Because Salesforce allows you to type in the country, there are several duplicates: Examples include "United States of America", "Mexico", and "Australia".

I can't find these duplicates.  Can you tell me where you see them?  I looked in the user interface and the database and don't see any dupes.

**Comment by monika-aashe** [comment]
@rerb - The duplicates don't show up anymore. I think the issue was fixed when #46 got closed.

**Comment by rerb** [comment]
Excellent!

On Tue, Feb 2, 2016 at 1:04 PM, monika-aashe <notifications@github.com>
wrote:

> @rerb <https://github.com/rerb> - The duplicates don't show up anymore. I
> think the issue was fixed when #46
> <https://github.com/AASHE/hub/issues/46> got closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/189#issuecomment-178725408>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals and 
reviewers now open <https://ww4.aievolution.com/ash1601>!

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
