### ISSUE TITLE
Add content type dashboards for data analysis

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#190]
Add a member-accessible dashboard tab for data analysis associated with each content type. This dashboard tab (which would be structured the same way as the tabs associated with each topic) would include several standard data views for every content type:
- a bar chart showing the number of resources in that content type by topic/discipline/department with users able to toggle between topic/discipline/department via a drop down. Ideally, the chart would be clickable (i.e., clicking a topic would take the user to the list of resources matching the content type and topic/discipline/department).
- a line graph showing the total number of resources posted under that content type over time
- a map showing a pin associated with each organization associated with a resource of that content type. Ideally, this map would also be clickable and zoomable (e.g., http://www.aashe.org/resources/academic-programs/map/)

Content type specific data views (e.g., a bar chart showing the number of academic programs in each program type) will likely be added later so the page should be designed with this flexibility in mind.

**Comment by jamstooks** [comment]
Cool. I like this!

**Comment by monika-aashe** [comment]
@juliandsmith - I moved this to 1g but then realized #295 is what Scott is currently working on. Is there anything that needs to be revised on this ticket and put back in the inbox or bikerack? Or should we just close this ticket?

**Comment by juliandsmith** [comment]
I think we can just close it. If we want to add more features at a later date, we'll need to create separate tickets for that anyway.
