### ISSUE TITLE
Add Markdown formatting buttons to case study form

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#193]
Add formatting buttons that add correct Markdown code for basic text formatting (e.g., bold, italic, link, lists) to the case study text boxes (like the GitHub issues submission text boxes). 

If this is not possible, at least add a "Styling with Markdown is supported" help text with a link to instructions for using Markdown code.

**Comment by juliandsmith** [comment]
Note that markdown code doesn't actually appear to be in place currently. I tried using it [this description](http://hub.aashe.org/browse/publication/8707/Environmental-Literacy-and-Sustainability-as-Core-Requirements-Success-Stories-and-Models) but the bullets remain as /*.

**Comment by peltonc** [comment]
Hey Julian,

It works
<http://hub.aashe.org/browse/publication/8707/Environmental-Literacy-and-Sustainability-as-Core-Requirements-Success-Stories-and-Models>,
but I found that you have to use a hard return to separate the first
bulleted item from the line before it.

Chris Pelton
STARS Program Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | chris.pelton@aashe.org | +1 (859) 648-0063

On Thu, Feb 25, 2016 at 3:53 PM, juliandsmith <notifications@github.com>
wrote:

> Note that markdown code doesn't actually appear to be in place currently.
> I tried using it this description
> <http://hub.aashe.org/browse/publication/8707/Environmental-Literacy-and-Sustainability-as-Core-Requirements-Success-Stories-and-Models>
> but the bullets remain as /*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/193#issuecomment-188850949>.
>

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by juliandsmith** [comment]
Moving this to high priority after just spending 30 mins manually adding formatting an old case study submission. Without good and clear formatting, submissions end up being very difficult to read, which is frustrating to those who take the time to submit and means few people will actually use the material that was submitted.

**Comment by jamstooks** [comment]
Note: https://simplemde.com/

**Comment by jamstooks** [comment]
I've added this to all input fields that are text areas. I thought it would be confusing if it wasn't available in all of them.

**Comment by juliandsmith** [comment]
This new text box is awesome! It is already making my life much easier on the submission side (I no longer have to manually create each bullet in a list!). 

I'm reopenning because I'd like to add buttons for bold and italics as well. I have cause use bold pretty regularly (e.g. when submitting the abstract for any article in the International Journal of Sustainability in Higher Education [like this](http://www.emeraldinsight.com/doi/abs/10.1108/14676370710817165)) and I can see valid reasons for other submitters to use it when preparing case studies.
