### ISSUE TITLE
Need a bigger, clearer AASHE logo for page header

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#196]
From where?  Andrea, maybe?

**Comment by juliandsmith** [comment]
Have you tried this one?: https://drive.google.com/open?id=0B5SGLet-uzyTR3UyWWREMldFbkk

**Comment by rerb** [comment]
Monster logo!  

I can shrink this PNG down and I think it'll be clearer than the image we're using now, but wonder about making it bigger -- do we want to maintain the same size logo on all sites?  What do you think, @jamstooks ?

**Comment by rerb** [comment]
Actually, this logo, when shrunken to the size that's currently on the site (150px x 119px) is just as blurry as the one we're using now.  :(  See attached image.
![aashe_rgb_150x119px](https://cloud.githubusercontent.com/assets/609008/13326422/c9fccd72-dbb3-11e5-8968-b5238d10f98a.png)

**Comment by juliandsmith** [comment]
Closing because we've been using the blurry logo for years now at this point and it doesn't appear there is an easy fix.
