### ISSUE TITLE
Search only indexing 6 items

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#197]
Searching for "*" is supposed to return all of the submitted materials. Currently, it only returns 6 results, which is far less than the total number of items in the Hub. Using the search box also seems to search across only these 6 items.  Browsing by topic or content type still seems to work and return all relevant resources that meet the search criteria.

I don't have any filters currently activated and, just in case old filters were sticking, I tried refreshing, logging out, using a different browser, etc.. The problem persisted in all cases.

**Comment by jamstooks** [comment]
Hi @juliandsmith, I've updated the search index manually and reopened a #176 to ensure that this gets fixed. There are now [43 results](https://aashe-hub-dev.herokuapp.com/browse/?search=*).

**Comment by monika-aashe** [comment]
Is this the same as #133?
