### ISSUE TITLE
Bug in how quotation mark character is displayed in Title fields.

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#198]
The bad news... content with quotation mark (") shows up wonky, but it only seems to be the beginning quote. See test submission: http://aashe-hub-dev.herokuapp.com/browse/academicprogram/111/Special-character-test-quotes-apostrophes-colon-question-slash-parenthesis-bracket-hyphen-asterisk

The good news... Virtually all other "special characters" look fine in the test.

**Comment by jamstooks** [comment]
Are you referring to this part of the title

> &Quot;quotes"

Does that mean that " was converted to `&Quot;`? Do you know if it was a smart quote, copied from word? Otherwise it's very strange that one would get converted and the other wouldn't...

**Comment by monika-aashe** [comment]
Yeah, my guess is the error only shows up if there is a space before the quote instead of text. It wasn't a smart-quote - I just typed it in on the text.

**Comment by monika-aashe** [comment]
I just did a test and no longer see this coming up as an issue. Closing for now, but if anyone comes across this issue, we can reopen.
