### ISSUE TITLE
Hyperlinks don't always show in About and Submission Guidelines

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#199]
These documents are currently linked in the Hub as Google Docs. To look more professional, and due to the fact that they will be edited periodically, we'd like to add these as editable pages within the Hub that follow the same look and feel. 

About the Hub (linked in the Intro text on Hub home page below icons - https://docs.google.com/document/d/1wpjUHn7bphLtbcTaxZotDvQSoHa4wzU_0WPUegDdtS4/edit

Submission Guidelines (linked on the Submit a Resource page below the icons) - https://docs.google.com/document/d/1xvN4WlfwOqfsdSlw5P6A3xE4nWszbXeQ7zR59g3FL0s/edit

**Comment by jamstooks** [comment]
These are active, but still have two outstanding issues:
- [ ] needs tests
- [ ] visited links appear in black, so they can't be distinguished from plain text

**Comment by monika-aashe** [comment]
Quick question: Will there be an "Edit" option for these pages, so that I can make changes myself rather than submit changes to IT support?

**Comment by jamstooks** [comment]
I should be able to add one. In the interim, you can edit them in the admin under [flatpages](https://aashe-hub-dev.herokuapp.com/admin/flatpages/flatpage/).

**Comment by monika-aashe** [comment]
Update: Main issue to fix is that some hyperlinks don't show up as links until hover-over.

**Comment by monika-aashe** [comment]
Closing this ticket because the hyperlinks appear to show up correctly.
