### ISSUE TITLE
Conference Presentations list ready for import

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#200]
Here is the link to the Google sheet: https://docs.google.com/spreadsheets/d/11Z3sH6_JcM36RIQ6xilU6wA19VssrgGmGQwwpA8mz0w/edit#gid=0

There are a total of 3,572 entries.

A few comments:
- Included the 5-digit account id for every organization (including author orgs). You shouldn't have any issues with match-ups
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format. There should be no issue with spelling 
- Ran function to remove any leading/lagging spaces or doubles spaces for every field.
- Tags are in a single column, separated by comma-space ", ". I did a maximum of 5 tags for any given resource, so if it's easier, I can separate out into 5 columns pretty quickly

Possible issue: In some cases, fields that are required (see green headings) are not filled in. These include:
- First Author name - about 177 cases
- Uploaded file - about 2,250 cases - over half of the resources - Note: On one of our calls, we decided to include all conference presentations, not just those that provided files).

**Comment by jamstooks** [comment]
These are currently importing (1348 and counting). There were 26 presentations that had errors with the organization(s) they were associated with in the import. Either, the org name didn't match the ID provided or the ID wasn't found at all. I've highlighted those rows in the [spreadsheet](https://docs.google.com/spreadsheets/d/11Z3sH6_JcM36RIQ6xilU6wA19VssrgGmGQwwpA8mz0w/edit#gid=0) in orange so we can work with those separately.

**Comment by jamstooks** [comment]
I'm thinking we can push this issue back a milestone or two and deal with those 26 later. Does that sound reasonable?

**Comment by juliandsmith** [comment]
I'm okay with dealing with these 26 later. 

However, the academic discipline and office or department fields don't seem to have come through in the current import. There aren't a huge number of presentations that have been categorized in these ways, but the ones I checked all seem to be missing those fields. (Offices don't show up in the public view yet so I checked in the backend to confirm that this field was blank rather than just hidden).

**Comment by jamstooks** [comment]
I ran another import last night and these fields are up now. I still need to get the offices to show up, but that's another ticket (#207).

**Comment by monika-aashe** [comment]
Thanks Ben! This still excludes the 26 with issues, right?

On Fri, Feb 26, 2016 at 9:48 AM, Benjamin W Stookey <
notifications@github.com> wrote:

> I ran another import last night and these fields are up now. I still need
> to get the offices to show up, but that's another ticket (#207
> <https://github.com/AASHE/hub/issues/207>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/200#issuecomment-189309961>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment]
It does... we might need to do them manually :(

**Comment by monika-aashe** [comment]
I figured out the issues with the conference presentation import:

1) Most of the issues had to do with including organizations that are classified as "not eligible for membership in Salesforce" these must not get included in the ISS. 
- Portland Community College, Rock Creek Campus gets reassigned to parent, Portland Community College
- University of British Columbia Okanagan gets reassigned to parent, University of British Columbia
- College of Saint Benedict & Saint John's University gets reassigned to one or the other
- University of Toronto Scarborough gets reassigned to parent, University of Toronto
- Pierce College Fort Steilacoom gets reassigned to parent, Pierce College District 11
- Cascades Fine Papers Group gets reassigned to parent, Cascades Tissue Group

Issue 2) Some organizations were listed as "Exclude Account from AASHE Website". I changed this to unchecked in Salesforce for the following (but they weren't yet in the Hub dropdowns on 3/12):
- Hackman Consulting Group
- Center for Diversity & the Environment

3) There was one instance where the wrong id number was displayed (Green Mountain College's id was listed as 16525 instead of 16524).

All issues are fixed and can now be found in the following import file: https://docs.google.com/spreadsheets/d/187l7tg_nhu7iOK8uEM7eTJECnL_R-PiBI28N4oYpRPk/edit#gid=0

**Comment by juliandsmith** [comment]
I'm confused. Why can't UBC Okanagan and UT Scarborough be listed as institutions? I think they are fairly independent from the main campus. Do we have a policy on when to allow an a separate institution or not?

**Comment by monika-aashe** [comment]
Not so sure about a policy per se, but the fact that they are listed as
"not eligible for membership" in Salesforce is why there was an error in
trying to get them imported.

If we decide to update the info in Salesforce instead, I can re-do the
list.



On Sun, Mar 13, 2016 at 1:29 AM, juliandsmith <notifications@github.com>
wrote:

> I'm confused. Why can't UBC Okanagan and UT Scarborough be listed as
> institutions? I think they are fairly independent from the main campus. Do
> we have a policy on when to allow an a separate institution or not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/200#issuecomment-195891678>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 
Attend the Sustainability Officers Retreat 
<http://www.aashe.org/events/workshops/2016/Sustainability-Officers-Retreat> at 
the University of British Columbia Okanagan Campus on July 27 - 29. 
Applications are due by April 15.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
Talk with Margueritte before flipping that "not eligible for membership" bit.  I think there are billing issues here.

Re: Pierce College Fort Steilacoom; Fort Steilacoom was an insane asylum in the post-Civil War era.  They call it Western State Hostpital now.  Fanny Farmer was a patient/resident/victim.  Ask me how I know.  _I dare you!_

**Comment by monika-aashe** [comment]
okay, @rerb , how do you know???

**Comment by rerb** [comment]
Oh heck, such a mundane answer to such a leading question, I was hoping no
one asked.  Then again, implying first-hand knowledge of a mental asylum
isn't the sort of rumor one might advisedly start about oneself.  I read
about Steiliacoom in a book about Sarah Canary.

On Sun, Mar 13, 2016 at 10:48 PM, monika-aashe <notifications@github.com>
wrote:

> okay, @rerb <https://github.com/rerb> , how do you know???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/200#issuecomment-196114775>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Attend the Sustainability Officers Retreat 
<http://www.aashe.org/events/workshops/2016/Sustainability-Officers-Retreat> at 
the University of British Columbia Okanagan Campus on July 27 - 29. 
Applications are due by April 15.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
List is ready for re-import, unless it is better to simply add manually.
https://docs.google.com/spreadsheets/d/187l7tg_nhu7iOK8uEM7eTJECnL_R-PiBI28N4oYpRPk/edit#gid=0

**Comment by jamstooks** [comment]
I've run the import, but there was an issue with the last one. Here's the output for row 26:

> Org not found: Rutgers, the State University of New Jersey, Camden Campus (18059.0)
> Org name doesn't match db:
> Northwestern University != Rutgers, the State University of New Jersey, Camden Campus
> Author Org not found: Rutgers, the State University of New Jersey, Camden Campus (18059.0)
> Author Org name doesn't match db:
> Northwestern University != Rutgers, the State University of New Jersey, Camden Campus

**Comment by monika-aashe** [comment]
Since Rutgers - Camden Campus is a subsidiary of Rutgers main campus (New Brunswick), I updated to that institution.

**Comment by jamstooks** [comment]
I ran the import for that row. We should be good now.
