### ISSUE TITLE
Research Centers & Institutes list ready for import

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#201]
Here is the link to the Google sheet: https://docs.google.com/spreadsheets/d/1-S-xLPFKPOSjs9WxcTz77Evlu7SfUMGGYidB3x1lfxg/edit#gid=0

There are a total of 204 entries.

A few comments:
- Included the 5-digit account id for every organization (including author orgs). You shouldn't have any issues with match-ups
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format. There should be no issue with spelling 
- Tags are in a single column, separated by comma-space ", ". I did a maximum of 5 tags for any given resource, so if it's easier, I can separate out into 5 columns pretty quickly
- All required fields have valid content.
- All URLs have been checked (January 2016)

**Comment by juliandsmith** [comment]
Sustainability topics don't appear to have been included in the most recent import. All of them are supposed to be in the research topic but none show up: http://aashe-hub-stage.herokuapp.com/browse/types/centerandinstitute/?search=&topics=research&content_type=centerandinstitute&country=
