### ISSUE TITLE
Course Materials list ready for import

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#202]
Here is the link to the Google sheet: 

There are a total of 13 entries.

A few comments:
- Included the 5-digit account id for every organization (including author orgs). You shouldn't have any issues with match-ups
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format. There should be no issue with spelling 
- Tags are in a single column, separated by comma-space ", ". I did a maximum of 5 tags for any given resource, so if it's easier, I can separate out into 5 columns pretty quickly
- All required fields have valid content.

**Comment by jamstooks** [comment]
https://drive.google.com/open?id=1eH3gw-QJlbnOLE4nQEfaevqD28LtZiOd4c_oOC-RkxQ

**Comment by juliandsmith** [comment]
Sustainability topics don't seem to have come through on the most recent import. Based on Monika's spreadsheet, they should all be in the curriculum topic but none are categorized that way: http://aashe-hub-stage.herokuapp.com/browse/types/material/?search=&topics=curriculum&content_type=material&country=
