### ISSUE TITLE
Publications list ready for import

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#203]
Here is the link to the Google sheet: https://docs.google.com/spreadsheets/d/1VxCKT8g6t_6iqytXy7syRFbU0oqCCQCPGM2gCm53l4o/edit#gid=0

There are a total of 444 entries.

A few comments:

- Included the 5-digit account id for every organization (including author orgs). You shouldn't have any issues with match-ups
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format. There should be no issue with spelling
- Ran function to remove any leading/lagging spaces or doubles spaces for every field.
- Tags are in a single column, separated by comma-space ", ". I did a maximum of 5 tags for any given resource, so if it's easier, I can separate out into 5 columns pretty quickly
- All required fields are filled in completely

**Comment by jamstooks** [comment]
@monika-aashe I have a working import for these that appears to be working smoothly. I'll do some more quality control, but it's looking promising. I did notice that about 50 of the presentations are not tied to any organizations... is that an issue?

**Comment by monika-aashe** [comment]
Thanks @jamstooks - yeah, for some authors, I wasn't able to identify their organization. I think it's okay though, since the author or isn't required.

**Comment by jamstooks** [comment]
Ok, these are updating as we speak (250 so far). I've put up a _stage_ server. Feel free to check them out here:

http://aashe-hub-stage.herokuapp.com/browse/types/publication/

**Comment by monika-aashe** [comment]
Cool, thanks! The immediate issue that comes up is the default 10 resources per page display (there are 37 pages coming up). We should probably update to show 50 per page like in the IRC. The good news is that there is already a ticket for that - #134

At what point will you move this to a production server? After the exports?

**Comment by jamstooks** [comment]
I saw that issue.

This will eventually morph into the production server... and be available at hub.aashe.org once I get a few more imports done. I'll add a ticket.

**Comment by juliandsmith** [comment]
It doesn't look like publication type is coming through on any of these but that's kind of an important field. It is in Monika's sheet as column AA "Type of Material" but the "Type of Material" field in the Hub shows up as empty for every publication that I checked.

**Comment by monika-aashe** [comment]
Good catch, Julian. I just checked the Heroku dev server, and it looks like it was left off there as well: Here's an example: https://aashe-hub-dev.herokuapp.com/browse/publication/12/Going-Beyond-Green-The-Why-and-How-of-Integrating-Sustainability-Into-the-Marketing-Curriculum

Is it fixable without rerunning the import?

**Comment by juliandsmith** [comment]
Also, line breaks from Monika's sheet aren't carrying though which is creating giant text blocks. For example: http://aashe-hub-stage.herokuapp.com/browse/publication/316/green-labs-at-emory-university 

Sorry if you've already caught these issues. I'm just super excited about this and I'm enjoying browsing around.

**Comment by juliandsmith** [comment]
Looks like there are actually 2 separate problems with publication type. The first is that when a publication type is submitted it doesn't appear anywhere on the publication page, as indicated from Monika's example, which is classified as a journal. The second problem is that the publication type from Monika's spreadsheet wasn't included in the import (try editing any of the publications to see this - the type field is empty. 

I will submit a separate ticket about having the publication type appear on the publication page. My concern here is that the publication type data we have doesn't seem to be included in the import.

**Comment by jamstooks** [comment]
Ok, cool. Thanks for reviewing. I can tweak the import and quickly re-run it to do the following:

- [ ] ensure newlines get brought in
- [ ] fix the import to include the type of material

Thanks for adding another ticket to display the material type.

**Comment by jamstooks** [comment]
Ok, I ran another import. The only one with wonky formatting is this one:

The Impact of Carbon Sequestration at California State Polytechnic University, Pomona

but we should be able to fix that manually...

**Comment by juliandsmith** [comment]
I just noticed one other issue with the import: for some reason, publications that were connected with AASHE in Monika's spreadsheet aren't connected with AASHE in the Hub. Monika's spreadsheet had 77 publications with AASHE listed as "Organization 1" but there are currently no publications associated with AASHE in the Hub at all right now: http://aashe-hub-stage.herokuapp.com/browse/?search=*&organizations=20096&country=

Here's a specific example of a resource that should be associated with AASHE, but isn't: http://aashe-hub-stage.herokuapp.com/browse/publication/602/sustainable-procurement-toolkit

**Comment by jamstooks** [comment]
Thanks for pointing that out, @juliandsmith. I was excluding AASHE temporarily early on and forgot to update the code. I've fixed it, but will run that code when I run another import here shortly...
