### ISSUE TITLE
Set email environmental variables in aashe-hub-stage config

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#204]
Here's the list, from settings/base.py:

```python
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.filebased.EmailBackend')
EMAIL_FILE_PATH = os.environ.get(
    'EMAIL_FILE_PATH', '/tmp/hub-email-messages')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', True)
EMAIL_HOST = os.environ.get('EMAIL_HOST', None)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', None)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', None)
EMAIL_PORT = os.environ.get('EMAIL_PORT', None)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', None)
EMAIL_REPLY_TO = os.environ.get('EMAIL_REPLY_TO', None)
```

**Comment by monika-aashe** [comment]
Does it matter if it's on the dev site versus the new hub.aashe.org site that Ben will create once he starts migrating in the old IRC data? We need this to work on the hub.aashe.org production site (it's fine if it also works on the dev site)

**Comment by rerb** [comment]
I think it would be better to have only the production site actually
sending emails.

On Tue, Feb 16, 2016 at 3:30 PM, monika-aashe <notifications@github.com>
wrote:

> Does it matter if it's on the dev site versus the new hub.aashe.org site
> that Ben will create once he starts migrating in the old IRC data? We need
> this to work on the hub.aashe.org production site (it's fine if it also
> works on the dev site)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/204#issuecomment-184863863>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals & reviewers 
extended until Feb. 22! Submit your proposal today 
<https://ww4.aievolution.com/ash1601>!


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Soft launch was today and we already have about a dozen new resources! Now that we have a production site, it would be great to prioritize this so that the emails start going out.

**Comment by rerb** [comment]
Monika -

I think I've got the email configured, but haven't tested it since it's a production database.  I've added myself to the resources@aashe.org group so when a message gets posted I'll see it.  

Of course, if the configuration is incorrect, I won't see a message.  If you notice new resources submitted after now -- 5.21pm EST -- that don't generate a message, please let me know and I'll investigate.

**Comment by monika-aashe** [comment]
Thanks Bob! I haven't seen anything come through yet, but I'll keep you
posted. FYI, this is an account that is managed through Salesforce, in case
that makes a difference.

Monika

On Thu, Feb 25, 2016 at 5:22 PM, Robert Erb <notifications@github.com>
wrote:

> Monika -
>
> I think I've got the email configured, but haven't tested it since it's a
> production database. I've added myself to the resources@aashe.org group
> so when a message gets posted I'll see it.
>
> Of course, if the configuration is incorrect, I won't see a message. If
> you notice new resources submitted after now -- 5.21pm EST -- that don't
> generate a message, please let me know and I'll investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/204#issuecomment-189010981>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
OK, emails flowing.

(EMAIL_BACKEND wasn't defined on Heroku, and then the Gmail "allow less secure apps" switch needed to be flipped.)

**Comment by monika-aashe** [comment]
Yes! Just tested both accept and decline. Everything seems to be working fine and I received all of the emails. Thanks Bob!

**Comment by monika-aashe** [comment]
Reopening due to small issue: The URL is not displaying properly in the approved resource email. May be due to the switch to hub.aashe.org? 

Dear Julian,

Thank you for contributing to AASHE’s Campus Sustainability Hub! The following resource has been approved and is now accessible through the Hub.

Resource title: UCLA Men's Basketball Sustainability
Content type: Videos
Submitter name: Julian Dautremont-Smith
Link to resource: :///browse/video/12318/UCLA-Mens-Basketball-Sustainability

If you have questions about this or other resources in the Hub, please don’t hesitate to let us know by emailing resources@aashe.org. Thank you again for your contribution and interest in the Campus Sustainability Hub!

All the best, 
The AASHE Programs Team

**Comment by rerb** [comment]
Unable to reproduce.  Suspect Julian's message didn't have scheme or host in the URL because he was getting errors because Searchly.com was having trouble.

Here's what I get when I try to reproduce:

> Dear Robert,
>
> Thank you for contributing to AASHE’s Campus Sustainability Hub! The following resource has been approved and is now accessible through the Hub.
>
> Resource title: Test Video From Bob
> Content type: Videos
> Submitter name: Robert Erb
> Link to resource: http://hub.aashe.org/browse/video/12326/Test-Video-from-Bob
> If you have questions about this or other resources in the Hub, please don’t hesitate to let us know by emailing resources@aashe.org. Thank you again for your contribution and interest in the Campus Sustainability Hub!
> 
> All the best, 
> The AASHE Programs Team
>
>
> Attend the Sustainability Officers Retreat at the University of British Columbia Okanagan Campus on July 27 - 29. Applications are due by April 15.


Connect with us:   Website | Facebook | Twitter | LinkedIn

**Comment by monika-aashe** [comment]
Okay that makes sense cause I remember it working before - thanks!
