### ISSUE TITLE
Search/browse pagination tool shows every available page of results

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#208]
Now that more items are in the system, the search results pagination tool lists every possible page of results: 
![image](https://cloud.githubusercontent.com/assets/15839046/13199250/37a3676a-d7ee-11e5-9e55-e01745a209dc.png)

This list will grow incredibly long as more resources are added. To avoid this, switch to a cleaner pagination system that only shows 10 pages at a time (as on the AASHE Bulletin site):
![image](https://cloud.githubusercontent.com/assets/15839046/13199267/b231184c-d7ee-11e5-82cb-845602dbe690.png)

**Comment by monika-aashe** [comment]
Related to #134
