### ISSUE TITLE
Special character "&" not displaying correctly in resource titles

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#209]
Although Monika was able to get & to display correctly on the dev server (http://aashe-hub-dev.herokuapp.com/browse/academicprogram/111/Special-character-test-quotes-apostrophes-colon-question-slash-parenthesis-bracket-hyphen-asterisk)

However, in many resources on the staging server, it shows up as "&Amp;" instead of just "&": [example 1](http://aashe-hub-stage.herokuapp.com/browse/publication/724/measuring-managing-and-visualizing-building-energy-consumption-carbon-emissions), [example 2](http://aashe-hub-stage.herokuapp.com/browse/publication/763/rethinking-heating-ventilation-air-conditioning-hvac-in-harvard-universitys-river-houses-engineering-sciences-96-final-report), and [example 3](http://aashe-hub-stage.herokuapp.com/browse/publication/607/fair-trade-procurement-on-campus-summary-of-resources-links). 

It appears correctly as just & on the admin side so I was unable to fix this manually. Note that & also seems to appear correctly in at least some of the other fields like topics and organization names.

**Comment by monika-aashe** [comment]
I believe the issue is restricted to the resource title.

**Comment by juliandsmith** [comment]
Sorry to reopen, but this is still a problem with titles of featured resources. For example:
![image](https://cloud.githubusercontent.com/assets/15839046/13494540/e83299c0-e112-11e5-9308-064acc99cd2c.png)

I'm okay to wait until after launch to fix if necessary.

**Comment by juliandsmith** [comment]
This also appears to still be an issue with titles of resources in the "New Resources" feed on the topical toolkit pages:
![image](https://cloud.githubusercontent.com/assets/15839046/13601225/81e32a52-e4fc-11e5-810c-c0d10eff510d.png)
