### ISSUE TITLE
404/500 page

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#21]

**Comment by bartTC** [comment]
I've added two simple pages, but they need better wording, and maybe some sort of call to action:
 
http://aashe-hub-dev.herokuapp.com/404
http://aashe-hub-dev.herokuapp.com/500

**Comment by monika-aashe** [comment]
What is the difference between 404 and 500 error? Is there a reason why we don't use the same message?

**Comment by bartTC** [comment]
A 404 Page error is a page that does not exist. Because the URL was wrong, or the page simply no longer exists.

A 500 Page error is an internal server error. It should never happen. But can. It's a software error that needs to be fixed. In that case you get notified via email about this problem.

**Comment by monika-aashe** [comment]
Gotcha, very helpful. In that case, here are my recommendations but @jamstooks , we may have something standard on the AASHE server that we can go with instead.

404 error: 404 Page not found. 
We're sorry but the page you requested is no longer available. To request updates, please email resources@aashe.org.

500 error. Internal server error.
We're sorry but the page you requested is currently unavailable. We have been notified of this error and are working to resolve it.

**Comment by monika-aashe** [comment]
See also issue mentioned in #65 
Check that 500 error emails are setup. Or something else is in place to catch exception on the site, like Sentry. Added by Martin.

**Comment by jamstooks** [comment]
These error pages are in place.
