### ISSUE TITLE
File uploads are saved on dev version of AWS

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#215]
The direct URLs of uploaded files indicate that they are being saved on a dev version of AWS. For example: https://aashe-hub-dev.s3.amazonaws.com/uploads/Rowe_2002_-_Environmental_Literacy_and_Sustainability_as_Core_Requirements.pdf

It would be optimal if the file URLs could just appear to be on hub.aashe.org but if it has to include amazonaws.com in the URL, we should at least remove "dev" from the link.

**Comment by jamstooks** [comment]
Since we've already soft-launched, I'm going to move this to 1c.

**Comment by monika-aashe** [comment]
Is this a fix that can be done without re-importing the migrated files?

**Comment by jamstooks** [comment]
This was effectively solved by #124. However, there is still a bit of cleanup to do, so I've created another ticket for 1d: #261.
