### ISSUE TITLE
Author info, Links, Files, Images missing in Admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#216]
All of the standard fields for author info, links, files, and images is missing in the admin. Here are a few examples: 
http://hub.aashe.org/admin/content/presentation/8625/
http://hub.aashe.org/admin/content/video/8715/
http://hub.aashe.org/admin/content/outreachmaterial/8712/

It looks like I'm unable to review this information in admin, but if approved, it does appear to carry over (example): http://hub.aashe.org/browse/video/8715/AASHE-USGBC-NWF-and-Second-Nature-Announcement

**Comment by jamstooks** [comment]
Fixed;
