### ISSUE TITLE
Add file upload option to video content type

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#217]
Based on Daita's feedback. She will be uploading AASHE webinars to the Hub, so it makes sense to also upload PPT presentations and such.

**Comment by monika-aashe** [comment]
She also requested changing to "Videos & Webinars" but this part is decision needed.

**Comment by juliandsmith** [comment]
Making high priority because we need this to be able to share AASHE's webinars via the Hub (which could otherwise get lost when we switch over to the new website). Also Monika mentioned on the webinar that this is something we'd be adding in the next few weeks.

**Comment by monika-aashe** [comment]
The workaround is that instead of uploading files, we can link to the uploaded PDFs on the webinar archive page - see [example](http://hub.aashe.org/browse/video/12350/AASHE-Award-Winner-Webinar-Series-Student-Leadership-for-Campus-and-Community-Sustainability). The main piece that is high priority is retitling to "Videos & Webinars" so it's clear. But that can be done relatively quickly. 

I did get at least two resources from Deb McNamara that were submitted as Conference Presentations, but didn't approve them because we will be adding the archived files later. 

So I think we can move forward with adding the webinars even if the file upload options isn't in yet. Let me know what you think @juliandsmith

**Comment by jamstooks** [comment]
My concern with the upload option is that we'll have to add some file-type validation. I don't want people uploading the raw videos.

**Comment by juliandsmith** [comment]
This approach could  work in the short term, but I think those links will all break when we move to the new website. We'd have to redo them all in ~5 months.

As a result, I think it would be more efficient to just add the upload fields first (with the file type validation that Ben suggests) and upload them directly to the Hub.

**Comment by monika-aashe** [comment]
Should we consider a separate "Webinars" content type?

**Comment by juliandsmith** [comment]
I'm not sure I see the value of separating webinars out into their own content type (or even calling them out separately as above). Perhaps this should be topic for discussion on the next team call?

**Comment by monika-aashe** [comment]
Will add to the agenda. My main rationale for listing Webinars separately is that they are not always recorded, and sometimes only presentation slides are available. In such instances, where else would they fit?

**Comment by monika-aashe** [comment]
Consensus: Rename "Videos" to "Videos & Webinars", along with adding the file upload option for the submission form.
