### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#218]
Duplicate tags seem to have been created during the import process:
![image](https://cloud.githubusercontent.com/assets/15839046/13333865/2132f0c6-dbd7-11e5-9f96-65b1626852d1.png)

To reduce confusion and make sure that all items with the same tag are linked, I'd like to consolidate these so that there is only one tag option per word or phrase.

**Comment by monika-aashe** [comment]
Is it possible that the duplicates are occurring because of a lagging space? I know in the import files, I included all topics in a single column as such "bottled water, triple bottom line, STARS".
