### ISSUE TITLE
Create a Google account for user "Hub Notifier"

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#219]
This is the account the Hub will use to send email.  

Email address should be 'hub_notifier@aashe.org'.

Pretty high priority.  (Will set Hub to user 'STARS Notifier' account for now.)

@charris2015 can you set up the account, pick a good password, then 1-to-1 IM me the password on HipChat?

Thought I had sufficient perms to create accounts but it appears I don't.

**Comment by charris2015** [comment]
Hey Bob,

I've created the email account hub_notifier@aashe.org. The password is >uq+W4T$e?9f3d?p.

**Comment by rerb** [comment]
Thanks, Chris.  Excellent password.

On Wed, Mar 2, 2016 at 5:12 PM, charris2015 <notifications@github.com>
wrote:

> Hey Bob,
>
> I've created the email account hub_notifier@aashe.org. The password is
> >uq+W4T$e?9f3d?p.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/219#issuecomment-191456313>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
