### ISSUE TITLE
Fixes to featured resource selection tool

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#221]
I started working on adding featured resources (ticket #183) and I discovered that the tool to select featured resources is virtually unusable at our current scale.

I'm trying to add our [2015 staffing survey](http://hub.aashe.org/browse/publication/1232/2015-higher-education-sustainability-staffing-survey) as a featured resource in the "Coordination & Planning" topic. The problem is that there is no search function! I actually have to find the resource I want to feature within the list of 927 resources in the "Coordination & Planning" topic. I can filter slightly to get only recent things, but that doesn't help me much here since everything was submitted at one time. To make matters worse, the pagination tool only lets me browse the first 10 pages of results, which means I can't even browse the full list of "Coordination & Planning" resources to find the staffing survey (and it doesn't seem to be in the first 10 pages of "Coordination & Planning" resources).

I'm not sure what the best fix is here (starting over with a simple text box that we edit might be easier) so I'm marking this as decision needed. I'm also going to move this and #183 to be post-launch improvements. It doesn't seem critical that we launch with the featured resources menu in place.

**Comment by peltonc** [comment]
There is a workaround. Open another tab/window and find the resource you
want through regular search on the Hub:

http://hub.aashe.org/browse/publication/1232/2015-higher-education-sustainability-staffing-survey

Copy the 4-digit number in the URL (in this case, 1232) and paste it into
the favorites search box and save. That seems to do the trick.

On Thu, Feb 25, 2016 at 10:09 PM, juliandsmith <notifications@github.com>
wrote:

> I started working on adding featured resources (ticket #183
> <https://github.com/AASHE/hub/issues/183>) and I discovered that the tool
> to select featured resources is virtually unusable at our current scale.
>
> I'm trying to add our 2015 staffing survey
> <http://hub.aashe.org/browse/publication/1232/2015-higher-education-sustainability-staffing-survey>
> as a featured resource in the "Coordination & Planning" topic. The problem
> is that there is no search function! I actually have to find the resource
> you want to feature within the list of 927 resources in the "Coordination &
> Planning" topic. I can filter slightly to get only recent things for
> example, but that doesn't help me much here since everything was submitted
> at one time. To make matters worse, the pagination tool only lets me browse
> the first 10 pages of results, which means I can't even browse the full
> list of "Coordination & Planning" resources to find the staffing survey (it
> doesn't seem to be in the first 10 pages of "Coordination & Planning"
> resources).
>
> I'm not sure what the best fix is so I'm marking this as discussion
> needed. I'm also going to move this and #183
> <https://github.com/AASHE/hub/issues/183> to be post-launch improvements.
> It doesn't seem critical that we launch with the featured resources menu in
> place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/221>.
>

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by juliandsmith** [comment]
Nice! Perhaps we can complete #183 before launch then. I would still like to improve the selection tool but it seems significantly less important now.

**Comment by monika-aashe** [comment]
Lets definitely discuss on next call. It looks like there is a related closed case about this - #64 but the solution wasn't yet implemented, so we may need to reopen it.

**Comment by monika-aashe** [comment]
no need for fix, workaround is easy enough
