### ISSUE TITLE
Display submitter name rather than cryptic id in admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#222]
In approving resources, knowing who the submitter is is valuable. We currently only see a 4-digit id, but it would be ideal to see the name and/or email address.

**Comment by monika-aashe** [comment]
If this isn't doable before launch, At minimum, it would be good to get a list of users emails and ids (though this would get outdated after public launch)

**Comment by dodget** [comment]
Should I resolve this on the 25th of this month to mark the two-year anniversary of this issue? :)

**Comment by dodget** [comment]
@monika-aashe - Would you prefer name, email, or both to be displayed?

**Comment by monika-aashe** [comment]
Given a choice I would go with both, but I will take whichever is simplest to include. Thanks!
