### ISSUE TITLE
Set up GoogleAnalytics for the Hub

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#225]
The Hub does not currently appear in AASHE's Google Analytics account. Now that we are having people visit the site, I'd like to be able to track visits and see what pages are most popular.

**Comment by jamstooks** [comment]
Hey @baronvonvaderham - would you mind using the same tool you used for the SCMD on this?

**Comment by baronvonvaderham** [comment]
Yeah, I can throw it on there on Friday, shouldn't take long at all.

**Comment by baronvonvaderham** [comment]
PR #234
