### ISSUE TITLE
Login as non-member generating errors

### ISSUE THREAD

**Issue by peltonc** [AASHE/hub#226]
See attachment
[ProgrammingError at _login_.pdf](https://github.com/AASHE/hub/files/151009/ProgrammingError.at._login_.pdf)

**Comment by juliandsmith** [comment]
This is happening for member login too:
![image](https://cloud.githubusercontent.com/assets/15839046/13397080/3e6ee2de-dec6-11e5-9540-7f5b5663c1c7.png)

**Comment by monika-aashe** [comment]
I just logged out to test and now can't log back in. Listed as prio-high.
