### ISSUE TITLE
Allow non-logged in access to search pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#230]
Currently, users must be logged in to view search pages (except Academic programs). Because we'll be setting up redirects from existing open access pages on the main site and want the page rank to carry over, we need to make these search views accessible without login. 

This will also help us in selling the Hub since it will allow non-members to get a sense of what we have in the Hub. These users still shouldn't be able to access most individual resource pages as these are typically member only.

**Comment by jamstooks** [comment]
Just to clarify:
- All browse/search views are visible to users who aren't logged in.
- You must be logged in, but don't have to be a member, to submit a resource.
- Resource detail pages require login (by a member) if they are member-only

Questions:
- If a resource isn't member only, can it be accessed without logging in or should someone still create an account (I'm leaning toward not requiring authentication)?
- What about Academic Programs? Should these all be publicly visible without login?

**Comment by juliandsmith** [comment]
Your clarifications seem correct. 

Academic programs should not require login at all as the primary target is prospective students and we want to bring them in via SEO. 

For all other resources, member-only should be the default. However, we want keep the ability to change the permissions for these resources manually via admin. We will likely want to be able to make some other resources open access (e.g. when required via partnership agreements or Creative Commons share alike licenses)  and occasionally log-in but not member only (e.g. for our salary survey).

**Comment by monika-aashe** [comment]
I believe that the way Martin set it up, some of this is partially controlled at the resource level - here are the 3 publishing options available in Admin (http://hub.aashe.org/admin/content/academicprogram/4616/)
- Open - no login required (all Academic Programs)
- Public - login required (some publications)
- Member - AASHE member status required (most other resources)

**Comment by jamstooks** [comment]
Thanks!

@monika-aashe so do you just set every Academic Program to "Open" manually?

**Comment by juliandsmith** [comment]
FYI - the topical toolkit page does not currently indicate which of the new resources and featured resources are member only when logged in with a non-member account:
![image](https://cloud.githubusercontent.com/assets/15839046/13478171/cb63be20-e09d-11e5-86a3-fbce370eea15.png)

Non-members may be frustrated if the click on those links expecting to be able to access things and keep getting the login required message.

**Comment by jamstooks** [comment]
Seems that that is a side effect of making these available without a login. Maybe just a little "lock" icon with a mouseover might work best, since there is limited space in that right column and it would be less intrusive in the Featured Resources area...?

**Comment by monika-aashe** [comment]
If that's doable, it seems like a good solution. I'm also okay with keeping the Toolkit page a member only option.

**Comment by jamstooks** [comment]
I went back and forth on this, but I think the toolkit page has a lot of SEO value and is worth making available... even if most (all) of the resources are member-only.

**Comment by peltonc** [comment]
I agree. Plus it seems like that would add a lot more value to sponsorship.

In addition, the first thing a new un-registered visitor is likely to click
on is a topic and without access to the toolkits, I suspect most would just
move on. And it isn't clear that a non-member is even eligible for an AASHE
account.

On Thu, Mar 3, 2016 at 5:46 AM, Benjamin W Stookey <notifications@github.com
> wrote:

> I went back and forth on this, but I think the toolkit page has a lot of
> SEO value and is worth making available... even if most (all) of the
> resources are member-only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/230#issuecomment-191593043>.
>

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment]
Just to confirm the pieces here so I can check them off:

- [ ] All browse/search views are visible to users who aren't logged in.
- [ ] You must be logged in, but don't have to be a member, to submit a resource.
- [ ] Resource detail pages require login according to their permissions
- [ ] Toolkit pages are public
- [ ] Lock icon for resources in toolkit pages
- [ ] Confirm login is not required for public resourcs
