### ISSUE TITLE
Academic Programs list ready for import

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#235]
Here is the link to the Google Sheet: 
https://docs.google.com/spreadsheets/d/13QzEnJs6yr-nS18PW8o99zT7YdMf6mGmcD5dP94KAsc/edit#gid=0

We'd like to have these added as soon as possible so the Advisory Council reviewers can start adding academic programs that aren't on the list. 

IMPORTANT - all Academic Programs must be approved as "Permission: Open - No Log-in Required" 

Also, please back-date everything to around the time that all of the other resources were imported (Feb. 25)

- There is a total of 1,314 academic programs. 
- Included the 5-digit account id for every organization.
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format. 
- Tags are in a single column, separated by comma-space ", ". 
- Required fields are marked in green. All required field info has been filled out.

**Comment by monika-aashe** [comment]
FYI: Based on what I found out about the Conference Presentation errors, I checked for the same issues on this list and made one adjustment:
- College of Saint Benedict & Saint John's University - split this into two resources, one for each. In the long term, we may want to think about counting this as a single entity since they seem to be anyway.

**Comment by monika-aashe** [comment]
Hey @jamstooks - I just added the note about "IMPORTANT - all Academic Programs must be approved as "Permission: Open - No Log-in Required" to this cause just realized these should all be open... and I'd rather not have to do it manually 1,300 times, lol. Hopefully it's not too late?

**Comment by monika-aashe** [comment]
The backdate should be February 24-26, 2015.

**Comment by jamstooks** [comment]
Ok, I so I've imported all the Academic Programs into the dev site for review before importing them into production:

https://aashe-hub-dev.herokuapp.com/browse/types/academicprogram/

A couple things...

1. Did you mean the default date should be 2016?
2. There were a few places where an organization name did not match an ID. I have marked those rows in orange in the import.

Please take a look at the import and I'll make updates if necessary.

**Comment by monika-aashe** [comment]
Yes, sorry, 2/25/16

**Comment by monika-aashe** [comment]
Thanks Ben,
- I changed all cases of "Oregon State University-Cascades" to "Oregon State University" - that's another case of the Cascades campus being listed as "Not Eligible for Membership" in Salesforce
- Can you try Pinchot University again? Their Account Number is correct (19406) according to Salesforce (https://na7.salesforce.com/001A0000004PZZ4/d?retURL=%2F001A0000004PZZ4%3FsrPos%3D0%26srKp%3D001&nooverride=1), and they're NOT listed as "Exclude from AASHE website" so I'm not sure what the issue is. It does look like these resources were imported into the Dev version though (https://aashe-hub-dev.herokuapp.com/browse/types/academicprogram/?search=&content_type=academicprogram&organizations=19406&country= ).
- Same goes for "Joint MBA & Environmental Management Program" both are in SF under those same IDs, so I'm not sure what the issue is. This did get imported under the dev version (https://aashe-hub-dev.herokuapp.com/browse/academicprogram/1061/joint-mba-environmental-management-program)
- Why is "MS in Design & Urban Ecologies" from The New School marked in blue? This did import into the dev site and the ID is correct: https://aashe-hub-dev.herokuapp.com/browse/academicprogram/1303/ms-in-design-urban-ecologies
- Saint Joseph's College - this is a legit error - I updated to "Saint Joseph's College - IN" which is what it's called in SF and the ID number was changed to 18130

**Comment by jamstooks** [comment]
Sorry about that, I needed to run an update with the ISS. That, and the fixes you made have fixed all the errors. I re-ran the import. I'll run it on production tomorrow after you can confirm that it's looking good...

**Comment by jamstooks** [comment]
Oh, the Blue row had a link that was too long, but there were a bunch of bogus GET attributes that are sometimes tacked on by google searches, so I was able to remove them. I marked it for my own reference during the process.

**Comment by monika-aashe** [comment]
The Academic Programs look good too. I checked the dates and spot-checked that the tags are correct.
