### ISSUE TITLE
Allow filtering by discipline and link discipline labels

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#237]
Discipline is one of the most relevant ways to filter more academic type resources like academic programs, research centers, and course materials. Indeed, an AC member specifically asked about the ability to browse a list of academic programs in business. Add a filter for discipline on all search pages.

Once this is complete, discipline labels on the resource detail pages should also be linked to a search page with everything in that discipline label.

**Comment by juliandsmith** [comment]
Moved to high priority as this is necessary for being able to browse the Academic Programs by discipline, an important functionality that we were offering in the original Academic Programs database that the Hub is replacing.

**Comment by baronvonvaderham** [comment]
Fix deployed 6/23 with pull request 342
