### ISSUE TITLE
Case Studies list ready to import

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#239]
Here is the link to the Google Sheet: 
https://docs.google.com/spreadsheets/d/1g0xfkJvjwCPyArQ4eYluCWq-SaukSq-HuBjFnMI3Oew/edit#gid=0

This is the LAST IMPORT FILE (along with Academic Programs, which is also ready for import) - If possible, please import before public launch (but Academic Programs is higher priority).

- There is a total of 275 Case Studies
- Included the 5-digit account id for every organization. Checked against common errors from previous imports.
- Did some tests to ensure that Sustainability Topic, Academic Disciplines, Offices, Tags are typed in consistent format.
- Tags are in a single column, separated by comma-space ", ".
- Required fields are marked in green. All required field info has been filled out.

Some considerations:
1) For the submitter info, if possible, please use the first author email to identify submitters. If this is time-consuming, feel free to default all to monika@aashe.org.
2) Please upload to include the Date Submitted (see last column) - due to the nature of this resource and based on feedback we recently received, it would be good to show the actual dates these were created in the IRC.

**Comment by jamstooks** [comment]
Just want to confirm... `consider for award` should be "no" for all of these, right?

**Comment by monika-aashe** [comment]
Yes, that is fine.

**Comment by jamstooks** [comment]
These are importing now and should be complete by morning. There were no errors with matching organizations, so hopefully it all goes through correctly. Please let me know if it looks good to you...

**Comment by monika-aashe** [comment]
Everything looks good, the published dates look okay and the tags are all good. I think this is good to move to the production server!
