### ISSUE TITLE
Tag for "IT" does not show up in front-end and admin dropdowns

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#252]
There are over 50 resources with this tag and it's used to identify apps, software, computer technologies, etc: http://hub.aashe.org/browse/?tagfilter=it 

However, typing "IT" or "it" in the front-end or admin does not pull up any results. I suspect it has to do with the fact that it is a two-word tag. The only way to get to this tag in the front-end is by clicking on it from an existing resource.

Easiest solution might be to make the tag work for this or other two word tags - however, another option would be to rename these resources to "online technology" or something along those lines and avoid using two-word tags in the future.

**Comment by jamstooks** [comment]
Right now we only start the search when 3 characters have been entered. This prevents doing a lot of unnecessary queries on the database for tags. I can set it to 2 pretty easily, I think.

**Comment by monika-aashe** [comment]
Since it won't be a big issue, lets set to start search when 2 characters are entered.

**Comment by jamstooks** [comment]
Upon further discussion. I think two-character tags are generally a bad idea. If there is an acronym that is two characters, it really makes sense to write out the two words, as in "Information Technology."

**Comment by monika-aashe** [comment]
I agree Ben. I actually updated "IT" to "information technology" once the tag moderation was implemented, so this is fine to keep closed and forget about.
