### ISSUE TITLE
Create a process for editing resource URLs

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#254]
If there is a spelling mistake in the title of the original submission, this mistake carries through to the URL that is automatically assigned to each resource. Programs staff can fix the spelling mistake in the title, but  we currently don't have the ability to fix the URL. As a result, we have URLs like this:
http://hub.aashe.org/browse/publication/1248/cimate-change-resiliency-campus-microgrid-feasibility-study

I'm not sure if we want to give regular staff the ability to edit URLs via admin but we need some process to fix this kind of thing.

**Comment by jamstooks** [comment]
This should be as easy as adding the slug field to the admin.

**Comment by monika-aashe** [comment]
The slug field is in admin. Ready to close?

**Comment by baronvonvaderham** [comment]
Yeah this was merged and deployed, so I'm gonna go ahead and close it.
