### ISSUE TITLE
& not handled correctly in breadcrumbs

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#257]
![screen shot 2016-03-25 at 1 00 17 am](https://cloud.githubusercontent.com/assets/585436/14039747/18852b60-f225-11e5-81de-5ef47de33b45.png)

**Comment by monika-aashe** [comment]
FYI, the &amp; issue also comes up in the Toolkit under "Featured Resources" and "New Resources" - we had pushed it off to 1d (#209) but if fixing all at once is easier, I wanted to add a note.
