### ISSUE TITLE
Delete from Drupal any IRC resources that have been replaced in the Hub

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#263]
After redirects have been established ( #123 ), we'll need to go into Drupal and delete pages that are now in the Hub. Jessica believes we are getting higher quotes for the website redesign because of the number of pages we appear to have in Drupal. Deleting these pages from Drupal will make the website redesign easier and may lower our costs.

**Comment by jamstooks** [comment]
I'm going to close this, since we already have a vendor and there is no real need to remove these pages... redirects are fine. Our time is more valuable elsewhere.
