### ISSUE TITLE
Set up SSL certificates

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#266]
If you do a search for "Campus Sustainability Hub" in Google, and click on our link, you get a warning, and the page displays incorrectly. This is due to display of "https" instead of "http"

Warning:
<img width="636" alt="screen shot 2016-03-29 at 9 45 03 am" src="https://cloud.githubusercontent.com/assets/15214797/14110217/90a1c902-f593-11e5-81f2-9cd52d405744.png">

After bi-passing the warning:
<img width="525" alt="screen shot 2016-03-29 at 9 45 26 am" src="https://cloud.githubusercontent.com/assets/15214797/14110275/bd51198a-f593-11e5-9258-99abfa6f5ff2.png">

**Comment by monika-aashe** [comment]
FYI, I just discovered that clicking on "Hub" at the top left hand corner of the site, when already on the Hub site, results in the same error.

**Comment by jamstooks** [comment]
Certificates are in place! I still have two things I need to do:

1. [ ] force the redirect from http to https. I think I can use [this app](https://github.com/rdegges/django-sslify) for that.
1. [ ] set up a renewal schedule for the certificates (they are only 90 day certs)
