### ISSUE TITLE
Fix log-in redirects

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#267]
Based on feedback from AC member, Caroline Savage

Users that aren't logged in can browse resources but can't view detail. When they do eventually log in to view detail, the path redirects to the AASHE profile page. Ideally, we would allow them to access the last active page (so they don't have to start back where they started with their search and filters).

**Comment by juliandsmith** [comment]
I have experienced this issue on our main aashe.org site, but I just tested the Hub a few times and it seemed to work exactly as it should. When a non logged in user opens a member-only resource, they see a login box. When they log in, they see that resource (not their AASHE profile page). Can anyone else replicate the problem?

**Comment by monika-aashe** [comment]
You're right, I wasn't able to replicate the problem either. Maybe I'll follow-up with Caroline to see if this is what she meant. In reading her comment, it looks like the other issue she experienced was the fact that about half of the time, she is logged in to the site, and the other half, she has to log in. Maybe that was the main issue. I'll find out.

**Comment by monika-aashe** [comment]
closing for now
