### ISSUE TITLE
Integrate advertisements into the Hub

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#269]
To supplement sponsor option (may also be quicker source of revenue.

**Comment by monika-aashe** [comment]
Jessica will follow up with advertising partners on possible next steps.

**Comment by juliandsmith** [comment]
Based on a conversation with Multiview, Jessica and I are recommending that a space for ads be added to the topical toolkit pages in a box above the New Resources column and parallel to the Introduction box.

**Comment by monika-aashe** [comment]
Code from Jessica:


<script type="text/javascript">var p="http",d="static";if(document.location.protocol=="https:"){p+="s";d="engine";}var z=document.createElement("script");z.type="text/javascript";z.async=true;z.src=p+"://"+d+".multiview.com/ados.js";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(z,s);</script>
<script type="text/javascript">
var ados = ados || {};
ados.run = ados.run || [];
ados.run.push(function() {
/* load placement for account: Multiview, site: AASHEweb - Assoc. for the Advancement Sustainability Higher Education - MultiWeb, size: 300x250 - Medium Rectangle, zone: AASHEweb - 300x250 - Curriculum Hub Page*/
ados_add_placement(4466, 53631, "mvCurriculumBox", 5).setZone(158711);
ados_setDomain('engine.multiview.com');
ados_load();
});</script>
<div id="mvCurriculumBox" style="text-align:center;"></div>

**Comment by jamstooks** [comment]
Here's the code from Multiview, which I've added to the [curriculum toolkit](https://hub.aashe.org/browse/topics/curriculum/):

    

    <script type="text/javascript">var p="http",d="static";if(document.location.protocol=="https:"){p+="s";d="engine";}var z=document.createElement("script");z.type="text/javascript";z.async=true;z.src=p+"://"+d+".multiview.com/ados.js";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(z,s);</script>
    <script type="text/javascript">
    var ados = ados || {};
    ados.run = ados.run || [];
    ados.run.push(function() {
    /* load placement for account: Multiview, site: AASHEweb - Assoc. for the Advancement Sustainability Higher Education - MultiWeb, size: 300x250 - Medium Rectangle, zone: AASHEweb - 300x250 - Curriculum Hub Page*/
    ados_add_placement(4466, 53631, "mvCurriculumBox", 5).setZone(158711);
    ados_setDomain('engine.multiview.com');
    ados_load();
    });</script>
    <div id="mvCurriculumBox" style="text-align:center;"></div>

This is fine for now, but I'd like to move to a more generic solution... maybe adding an `mv_key` value to each topic, that would represent the "mvCurriculumBox" value. Then we could dynamically control which toolkits get ads. I won't know how much has to change until I get code for another resource, so I'll wait until then.
