### ISSUE TITLE
LOGIN_REDIRECT_URL doesn't seem to have effect

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#27]
When I log in, I'm not redirected to "/" I just see the log-in form again.

**Comment by jamstooks** [comment]
Having the user's email in the logout link might also be useful to help a user know that they are logged in and who they are logged in as... like:

logout, user@domain.xyz

**Comment by bartTC** [comment]
Fixed the redirect. Created a new ticket for the email in logout: #66
