### ISSUE TITLE
Research consequences of removing an organization in SF

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#273]
Will this cause a foreign key issue on orphaned resources?

**Comment by monika-aashe** [comment]
This happened with Yale University. This used to be a duplicate issue in Salesforce, and then Chris H. deleted the dupe. However, there was one resource associated with the duped account. As a result, both Yale Universities show up in the Hub, even after I reassigned the resource to the appropriate account.

**Comment by monika-aashe** [comment]
Closing for now
