### ISSUE TITLE
Search isn't working properly

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#275]
There is a resource in the Hub entitled "[A Call for Climate Leadership: Progress and Opportunities in Addressing the Defining Challenge of Our Time](http://hub.aashe.org/browse/publication/1548/a-call-for-climate-leadership-progress-and-opportunities-in-addressing-the-defining-challenge-of-our-time)". Strangely, it doesn't appear in the search results for either [Call for Climate Leadership](http://hub.aashe.org/browse/?search=Call+for+Climate+Leadership) or ["climate leadership"]("climate leadership"). This resource was added in late Feb. so I don't think it is an issue of needing time to index the materials.

Similarly, [searching for gigawatt](http://hub.aashe.org/browse/?search=gigawatt) doesn't return the [Green Gigawatt Partnership](http://hub.aashe.org/browse/tool/14568/Green-Gigawatt-Partnership) even though the word gigawatt appears in the title, description, and link associated with this resource.

**Comment by juliandsmith** [comment]
@rerb I know Ben is out through the end of the week so if there is any way you could look into this today, I'd appreciate it. I hate to say it, but getting this fixed is worth delaying STARS 2.1. We're actively pushing people to the Hub right now and have been promoting advanced search as a key benefit so it's really important that we get this working again.

**Comment by rerb** [comment]
Will do.

**Comment by rerb** [comment]
Huh, where's my comment from earlier?  About an hour ago, I replied, "Will do."

Well, I done.  Search is working again.  It was an issue with the index, as before.  

Will update with more details about what went wrong and how we might prevent it in the future coming.

**Comment by juliandsmith** [comment]
Phew! Thanks for fixing this so quickly Bob!!

**Comment by rerb** [comment]
There are two issues with this failed index rebuild.  1) Why did it happen?  2) Why weren't alarms raised?

I think I've solved the second -- the error reporter we're using was set to send a notification on the first appearance of an error, not on every occurrence.  This error happened a few weeks ago for the first time, so when it reappeared this morning, no notification was sent.  I've reconfigured the error reporter to raise an error every time the index rebuild fails like this.

The first issue is harder.  A more important question might be, when the index rebuilds, how do we retry/recover?  I'm looking into that now.

**Comment by juliandsmith** [comment]
Reopening because this indexing problem seems to have reemerged. Searching for [gigawatt](http://hub.aashe.org/browse/?search=gigawatt) again returns zero results. 

I discovered this because searching for "recreation" didn't include a resource titled [Campus Recreation: Bold Partners in Sustainability](http://hub.aashe.org/browse/presentation/11005/campus-recreation-bold-partners-in-sustainability).

**Comment by rerb** [comment]
Fixed again.

**Comment by rerb** [comment]
Looping @jamstooks in so he'll know what I did.

I set the Haystack TIMEOUT to 30s -- it was at its default, 10s.  The same change solved search problems we had on the bulletin way back when.  Hoping it fixes this one, too.

**Comment by juliandsmith** [comment]
Sadly, search seems to be broken again. [Searching for gigawatt](http://hub.aashe.org/browse/?search=gigawatt) returns zero results. I'm wondering if perhaps something is going wrong every time we add or edit a resource (I did both this morning)?

@rerb Are the notifications you set up working at least?

**Comment by rerb** [comment]
Yes, I was notified early this morning and working the problem beginning at 4am.  

Unfortunately, a flight, a van adventure, a trip to a rehab center, and is side-trip to a supermarket kept me from finishing until just now.

The index rebuild was timing out, as before, despite the greater timeout setting.  Setting it to 5m seems to be enough -- the index rebuilt successfully with a 5m timeout.

**Comment by juliandsmith** [comment]
Thanks Bob! Seems like you've been busy today. Sorry to have added one more thing to your plate. Anyway, I really appreciate you fixing it so quickly.

**Comment by rerb** [comment]
No worries, @juliandsmith -- I made it sound more dramatic than it was. ;-)  Good news is that the notifications worked, so I knew about the problem before you.  Better news is that the timeout is now 5m rather than 30s, so I think we're safe in thinking this problem has been solved.  For now.

**Comment by juliandsmith** [comment]
Reopening because search seems broken again. Searching for [gigawatt](https://hub.aashe.org/browse/?search=gigawatt) returns zero results. 

Is there something we can do besides extending the timeout to stop this from happening?

**Comment by jamstooks** [comment]
There was an issue with our provider. I'll give them one more shot before we move away from them. In the meantime, I've changed our process so that we only _update_ the search index every hour and don't completely _rebuild_ it, which should prevent complete crashes of the search functionality if there is a temporary issue.

**Comment by juliandsmith** [comment]
Search keeps timing out for me now, even though the rest of the site seems to work. I'm wondering if this is related to the fix we just implemented. Here's the non-specific error message I get: 
![image](https://cloud.githubusercontent.com/assets/15839046/15517456/c672f91c-21c5-11e6-974b-a98875d0296f.png)

**Comment by jamstooks** [comment]
Thinking we can safely close this after this fix. I haven't seen any errors in week... @juliandsmith have you experienced any further errors?

**Comment by juliandsmith** [comment]
I haven't experienced any issues recently (though I also haven't been as active in using it) so perhaps it is fixed for good now. I will close it.

**Comment by monika-aashe** [comment]
If we continue to get search errors, would it be best to submit an IT support ticket instead of reopening this?

**Comment by jamstooks** [comment]
Thanks, @monika-aashe. Yes, I think that's a good idea...
