### ISSUE TITLE
Add "Provide Feedback" to Footer of Hub under "Submission Guidelines

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#278]
While we can edit the content on the left side through admin edit controls, it doesn't allow us to edit the info on the right. 

A "Provide Feedback" link would probably be most appropriate right under "About" and "Submission Guidelines". I'd like to highlight the opportunity to provide feedback during Wednesday's Hub webinar, so it'd be great to have this in place by then.

Here is the link:
https://www.surveymonkey.com/r/aashe_hub

**Comment by jessicaaasheaashe** [comment]
Do you mean to add this to the footer?  I think that is a great idea!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Mon, Apr 11, 2016 at 1:49 PM, monika-aashe <notifications@github.com>
wrote:

> While we can edit the content on the left side through admin edit
> controls, it doesn't allow us to edit the info on the right.
>
> A "Provide Feedback" link would probably be most appropriate right under
> "About" and "Submission Guidelines". I'd like to highlight the opportunity
> to provide feedback during Wednesday's Hub webinar, so it'd be great to
> have this in place by then.
>
> Here is the link:
> https://www.surveymonkey.com/r/aashe_hub
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/278>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Yes, so the link to the survey would appear here right below Submission Guidelines:
<img width="1117" alt="screen shot 2016-04-11 at 1 58 33 pm" src="https://cloud.githubusercontent.com/assets/15214797/14437055/872d4748-ffed-11e5-9124-33abed76c89a.png">

We haven't really been promoting the survey (which may be why we've gotten no responses). This may help a bit.
