### ISSUE TITLE
Moderation of Hub Tags

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#279]
Two issues:
1) There is no validation step for tags - they show up as "approved" as soon as they are submitted, instead of after the resource is approved in admin. For example, I created a test resource and a brand new tag for "prevailing wage". I submitted the resource and didn't approve it. However, it now appears as a dropdown option. 
<img width="306" alt="screen shot 2016-04-12 at 4 36 39 pm" src="https://cloud.githubusercontent.com/assets/15214797/14474883/20cc2132-00cd-11e6-8fd8-92c5cb64cfce.png">
The bigger issue: Even if I edit a tag in admin, the original tag still shows up as a dropdown option on the front-end (I changed "small group discussion" to "group discussion" for two submitted resources yesterday, but now they both show up in the dropdown). This is more a nuisance than a major issue now, but there is the opportunity for abuse that could be worrisome.

2) There is no way to edit tags that have already been added. For example, we'd like to edit the tag, "canada" to be "Canada". Is there a way to allow staff to do this, or do we have to ask IT for these types of requests? It would be really sweet if we could run a report to see the number of resources that each tag has associated with it, then delete anything that has zero.

**Comment by jamstooks** [comment]
I've added a moderation tool to the admin:

https://hub.aashe.org/_ad/content/_tagulous_contenttype_keywords/

I think updating the auto-complete to check every tag for published resources would be too heavy a query to make the auto-complete be very user friendly, but I was able to limit it to those with a count of at least 1 resource. I think the risk is low if we can now moderate the tags.

When you go to delete a tag, you'll see a warning, which you safely ignore. Django's just confirming it can delete the tag and the relationship of the tag to any resources that may be tagged with it.

**Comment by monika-aashe** [comment]
Thanks Ben, I think there might be an issue with the limit of 1 resource moderation change. I tried submitting a test resource with the tag "bogus tag" and didn't get a warning. Even after deleting the tag from the resource, it still shows up in auto completion: 
<img width="285" alt="screen shot 2016-06-27 at 7 53 01 pm" src="https://cloud.githubusercontent.com/assets/15214797/16399490/cf3d75a4-3ca0-11e6-9c2c-a717f1a88c21.png"> - this is despite the fact that it doesn't show up in the admin moderation page.  

After deleting the whole resource in Admin, "bogus tag" still shows up in auto-completion.

**Comment by monika-aashe** [comment]
I'm guessing this might be related to site caching, this morning, the "bogus tag" tag is no longer there. Thanks!
