### ISSUE TITLE
Default ordering of search results

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#280]
When no search query has been entered (as in [browse all](http://hub.aashe.org/browse/?search=), browse by content type, browse by topic), results should be default ordered with most recent resources appearing first. 

This will ensure that the default results stay fresh and new resources are featured.

**Comment by juliandsmith** [comment]
Clarification: the default sort should be based on the "Date Posted" field (i.e., the date something was added to the Hub), not the date an item was published or created. For example, if a publication from 2007 was just posted to the Hub, it would still appear at the top of the default browse results (until it is displaced by even more recent submissions).

**Comment by baronvonvaderham** [comment]
I've managed to implement this in the code, but I've run into a snag: Most content types don't actually have/require this date created field. If I sort in this way, those without dates appear first, with the correctly sorted items with a date created at the end. I can confirm sorting's working correctly, if I invert it to be in ascending order, those items with dates appear at the top, but with the oldest item appearing first.

I thought I should get some feedback here to see how you'd like to proceed. I feel like sorting this way doesn't accomplish anything in a world where almost nothing has this data to sort by (and if someone does put it on their submission, it's doomed to go to the end of the list).

**Comment by baronvonvaderham** [comment]
Unless you mean "Date Published" referring to the date it was approved and published to the Hub. I just did a ticket about making these labels more uniform, but we kind of use different names for them all over the place in here.

**Comment by juliandsmith** [comment]
Not sure if you resolved this on the call yesterday, but the intention was to organize by date posted in the Hub (which all resources should have) rather than the date created/published field. There is a comment above from Apr 14 that tries to clarify this.

**Comment by baronvonvaderham** [comment]
Yes I got it straightened out, just confusion over nomenclature.
