### ISSUE TITLE
Update Search logic - apostrophes, #times term is mentioned, plurals and roots

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#281]
For any search query, we want to prioritize the following fields, so that if the term or a related term appears in one of these fields, the resource will appear higher in the list:
- Title
- Tag(s)

See most recent comments for the current asks (3/22/17)

**Comment by monika-aashe** [comment]
Also, if possible, it would be great to update to ensure that a search recognizes root words and partial words. 
- Partial words - the word "bibliometric" appears in the titles of two publications, but a search for the phrase "biblio" brings up nothing. This would be useful 
- Root words - e.g., if the word "assessed" appears in a resource, it also comes up in a search for "assessment"

**Comment by monika-aashe** [comment]
Another example: Cryptosporidium
If you don't know how it's spelled so you misspell it, no results, is there misspell logic that can be applied. 

A search for the root, "sporidium" also brings no results but should.

**Comment by jamstooks** [comment]
Ok, so I've been going through some slight calibrations here. This has taken a bit of tweaking, but here's how it works right now:

Say we have two resources. One has "Pizza" in the title and the other has "Pizza" multiple times in the content:

One:
> title: "Pizza Toppings" description: "Pepperoni, Cheese, Tomatoes"

Two:
> title: "Food I like"  description: "Pizza, cheese. Did I mention pizza? Pizza!"

Without any weighting to the _title_ the second one would show up first in search results. There might even be arguments for that being the correct order. With the weights tweaked in favor of the title right now, the first one will show up first in the results.

Anyway, to ensure that I'm calibrating the weighting of fields to your expectations, could you provide me with 3-5 example resources and the order they should show up for a specific search term. If you would like to add more fields beyond title and description, like keywords, that's fine too. They can be completely contrived, and don't need to be based on actual resources.

Additionally, we don't currently have the ability to do those root words or to handle misspellings. The root words might have some unexpected consequences anyway, like searching for "metric system" could produce many results about "biometric" or "bibliometric" which aren't necessarily relevant.

**Comment by jamstooks** [comment]
@monika-aashe @juliandsmith - do y'all have time to provide some feedback here? Is this something you want to discuss on our next Hub call?

**Comment by monika-aashe** [comment]
My thinking is that if the word shows up in the title, tags or is in the description multiple times, it should all be more highly ranked in search. Maybe 3 or more mentions in the descriptive text = 1 mention in Title or 1 mention in tags? If it is only mentioned once in the descriptive text, it should be ranked much lower. 

Too bad about the root word issues. Is there a way to program some of the more major issues one off? For example:

- Search for "diverse" also pulls up "diversity", but not "diversified" since this often relates to finance/investment
- Same for any word that is plural or has a different tense (committee/committees; officer/officers) - This in particular seems like a common issue for standard search, so I wonder if someone else has a solution for this somewhere. 
- I'm happy to discuss on an upcoming call if it would help.

**Comment by jamstooks** [comment]
Ok, cool. So we're looking at a 3-1 ratio or something. I think I can get close to that.

I didn't realize our search wasn't handling plurals. I'm surprised.

Plurals and stemming are different than root words and should definitely be something this system can handle. I'll look into it.

**Comment by jamstooks** [comment]
Note, I think I'll go with [snowball](https://wellfire.co/learn/custom-haystack-elasticsearch-backend/)

**Comment by juliandsmith** [comment]
I'm reviewing the member survey results and there's a few complaints about search not working well. So, I wanted to dig into this a bit and try to provide an example of what I think people are talking about so that we can make sure the solution we are implementing addresses the problem.  The image below shows the results from searching for bottled water and is an example of the kind of search results that I think are raising questions for people.

As you can see from the list, we have a lot of relevant resources directly relevant to this keyword, but there are also a number of high ranking results that don't seem to fit. For example, the second result is "Brown's- A California Cafe", a case study about a cafe at UC Berkeley. The case study does mention that not selling bottled beverages in a few places, but bottled water clearly isn't the focus of this resource. Similarly, the 5th result "Hawaii Pacific University Earth Week,April 18-22, 2016" doesn't appear to have much to do with bottled water at all (it was a tag for some reason, but I just removed it). Likewise, the 10th result, "Health Promotion: a vehicle for partnerships," is a presentation that includes a single mention of bottled water. It makes people think our search doesn't work right when these three appear above resources that, to the reader, seem obviously more relevant. 

Working further down the list, you can see that the 50th result is "Just Tap It: Reducing Bottled Water Consumption at Muhlenberg College," which based on the title seems directly relevant to the search query and yet appears below the 4 immediately above it ("The Environmental Caucus: Breaking Down Silos to Promote Sustainability at Northern Arizona University" "Harvard Green Office Program" "Implementation of a Student Sustainability Fund at Missouri State University" and "Green Living Certification: Rewarding Residents for Environmentally Friendly Lifestyles"). 

It will be helpful to compare these results to results for bottled water after you implement a fix. 

![image](https://cloud.githubusercontent.com/assets/15839046/17462445/44742b16-5c7b-11e6-9706-f6bb5459e039.png)

**Comment by juliandsmith** [comment]
Here's an even worse example that I'm posting for later comparison. Searching for solar panels brings up a ton of resources that, based on the title and teaser text don't see very relevant at all:

![image](https://cloud.githubusercontent.com/assets/15839046/17462565/4609c3e2-5c7f-11e6-9002-adb7470bcb7b.png)

**Comment by jamstooks** [comment]
- [ ] handle apostrophes

**Comment by monika-aashe** [comment]
Need to also ensure that entering words in quotation marks (e.g. "general education") only brings up results with the "general education" string; as per #353

**Comment by monika-aashe** [comment]
Ensure that number of times a search phrase comes up in resource description is related to how high up in the results list the resource appears.

**Comment by monika-aashe** [comment]
Also, would be good to get clarity on how the search handles plurals, stemming and root words in terms of what goes into search results.

**Comment by monika-aashe** [comment]
We closed #289 , but that doesn't appear to be addressed yet either.

**Comment by monika-aashe** [comment]
Bob will deploy search fixes, then we'll decide if contractor is needed.

**Comment by unbracketed** [comment]
Notes from discovery / debugging:

The production ElasticSearch logs contain many repeated entries like:
```
2017-12-13T14:41:30+00:00 {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {null_value=1.0, name=boost}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {null_value=1.0, name=boost}]"},"status":400}

2017-12-13T14:41:30+00:00 {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"haystack"}],"type":"index_already_exists_exception","reason":"already exists","index":"haystack"},"status":400}

2017-12-13T13:41:17+00:00 {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {name=boost, null_value=1.0}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {name=boost, null_value=1.0}]"},"status":400}

2017-12-13T13:41:17+00:00 {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"haystack"}],"type":"index_already_exists_exception","reason":"already exists","index":"haystack"},"status":400}

2017-12-13T12:41:42+00:00 {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {name=boost, null_value=1.0}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [_boost : {name=boost, null_value=1.0}]"},"status":400}

2017-12-13T12:41:42+00:00 {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"haystack"}],"type":"index_already_exists_exception","reason":"already exists","index":"haystack"},"status":400}
```

**Comment by dodget** [comment]
Ok, so after some testing in staging, here is what I've found.

Searching the word 'Institute' returns around 700 results.

Searching the phrase 'Institute of' sometimes crashes, and sometimes returns close to 7,000 results.

Searching the phrase 'Institute of Environment' always crashes. 

The crashes produce the following error:

```
2018-03-08T20:08:10.630811+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/browse/?search=Institute+of+Environment" host=aashe-hub-stage.herokuapp.com request_id=0cf4c7c4-5368-4a89-92d7-970f40d78c6e fwd="209.6.208.216" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
```

This error indicates that the server reached its 30 second timeout. We'll need to figure out how to speed up the process, or simplify it.

**Comment by dodget** [comment]
@juliandsmith - I think I've come up with a satisfactory fix to the search logic. I have the branch deployed to staging, and you can test here:

https://aashe-hub-stage.herokuapp.com/

Basically, the search logic before would take a phrase like 'Institute of' and would return any resource with the word 'institute,' or any resource with the word 'of.' That would make the query take too long. Any search with words like 'the,' 'a,' 'is,' 'of' would return lists that are way too long to process in 30 seconds or less.

So, I changed some simple parameters so the search would return resources where all words are present. If you search 'Institute of', that means 'Institute' AND 'of' need to be present in a resource for it to be returned. It looks like the search is still accurate, and it appears to be much faster.

Let me know what you think, and if you'd like the change deployed!
