### ISSUE TITLE
Align date created/published fields and create standard filter for Year Created

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#284]
Currently, all resources in the Hub are labeled with according to "Date Posted", which provides the basis for the "Year Posted" filter. Because there is often a difference between the date something was added to the Hub and when it was published or created, several content types have an additional date field:
 - Conference Presentations has "Presentation Date:"
 - Publications has "Publication release date:"
 - Academic Programs has "Year Founded:"
 - Research Centers & Institutes has "Year when center or institute was founded:"

Although videos, tools, course materials, outreach materials, and photographs don't currently have a date field like this, in many cases such a field would be relevant. As users have expressed a desire to filter by date created (as opposed to the date something was posted in the Hub), we want to have a single date created field for all content types that can be more easily be used for filtering purposes.

This consolidated field should be called "Date Created/Founded" and should have the following help text: "Enter the date when this resource was created, founded, published, or presented. If you don't know the exact date, choose the first day of the month. Use January 1 if you only know the year. You can use the calendar widget or type in a date in YYYY-MM-DD format."

This field will replace the "Presentation Date," "Publication release date," "Year Founded," and "Year when center or institute was founded" fields (and data currently associated with these fields should be imported into this new field, converting year data from the last two into date data). The Date Created/Founded field should then be added to all submission forms. Ideally, this field would be autofilled with the current date for Case Studies (since in this case the creation date is identical to the submission date) but this isn't a requirement.

Once this has occurred, a "Year Created/Founded" filter should be added as a general filter (i.e., across all content types).

This ticket supersedes the request to create separate "Presentation year" and "Year Published" filters in #34 and #36. It is high priority as this functionality is necessary to support the awards judging process (which begins in June).

**Comment by monika-aashe** [comment]
Should this also be applied to the Case Studies content type? Or are we assuming that the submit date is the same as the date created in this case?

**Comment by juliandsmith** [comment]
Because the case studies are in a format that is unique to us and therefore not published elsewhere, I was thinking that the submit date and date created would be the same. It would seem odd to me to have a field asking about date created.

**Comment by monika-aashe** [comment]
Okay, that clears it up, I'll make note of this in a similar ticket, #298

**Comment by juliandsmith** [comment]
I just revised the original ticket to reflect discussion on the 4/27 Hub team call in which we decided to add the Date Created/Founded field to_all _content types.

**Comment by monika-aashe** [comment]
The only piece missing is to specify where the field will be required versus optional. Right now, this field is only required under Conference Presentations, so I'm assuming it will continue to be required there but will be an optional field everywhere else. 

This means that the filter may exclude resources where this field is blank, but I think that will be okay.

**Comment by jamstooks** [comment]
@monika-aashe, will the field remain required only for presentations?

Have you had a chance to work up the help text, @juliandsmith?

**Comment by monika-aashe** [comment]
That's what gets my vote - only required for presentations. 

I think the help text is: "Enter the date when this resource was created, founded, published, or presented. If you don't know the exact date, choose the first day of the month. Use January 1 if you only know the year. You can use the calendar widget or type in a date in YYYY-MM-DD format."

Another thought: I believe we have the ability to change the name of the field on various forms, but still ensure it is linked across all content types, right? If that's the case and it's not a ton of extra work, here are my suggestions:
- Conference Presentations: "Presentation Date"
- Publications: "Publication Release Date"
- Academic Programs/Research Centers & Institutes: "Date Founded"
- Everything else: "Date Created"

**Comment by juliandsmith** [comment]
Yes, the help text Monika included above is the best I could come up with. I also like her suggestion of using a different field name for those content types.

**Comment by jamstooks** [comment]
The date field has been added and the database migrated. I now need to

- [ ] create the filter for the date_created field

**Comment by jamstooks** [comment]
Can you help me come up with a good label for that filter? The one I have is too long:

![screen shot 2016-05-03 at 11 12 05 am](https://cloud.githubusercontent.com/assets/585436/14991734/0c8801f6-1120-11e6-8b5f-45505d325551.png)

**Comment by monika-aashe** [comment]
How about "Year created, published or presented"? We use "founded" for Research Centers and Academic Programs, but I think "created" covers that as well.

**Comment by peltonc** [comment]
It seems to me that "Year Created" might be close enough:

create
kriːˈeɪt/
*verb*

   1. *1*.
   bring (something) into existence.


On Tue, May 3, 2016 at 6:13 PM, Benjamin W Stookey <notifications@github.com
> wrote:

> Can you help me come up with a good label for that filter? The one I have
> is too long:
>
> [image: screen shot 2016-05-03 at 11 12 05 am]
> <https://cloud.githubusercontent.com/assets/585436/14991734/0c8801f6-1120-11e6-8b5f-45505d325551.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/284#issuecomment-216599822>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Since it won't impact submission forms, I'm fine with "Year Created" too.

**Comment by jamstooks** [comment]
Ok, cool. Yeah, I think the confusion about created-in-real-life and created-as-a-resource will be reduced because we have "Year Posted" just above it.

Thanks!
