### ISSUE TITLE
Add Conference Name filter

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#285]
Conference Presentation browse view should include a unique filter (i.e., only visible when browsing conference presentations) based on the "Conference Name" field. This will allow users to just see presentations associated with a certain conference.

**Comment by monika-aashe** [comment]
Similar to #393

**Comment by juliandsmith** [comment]
Moving back to inbox because this has become more important as a feature for supporting AASHE affiliates who want to use the Hub for archiving presentations.

**Comment by monika-aashe** [comment]
I feel like this is a high priority, since what's the point of asking for conference name if we can't generate a list (and this just came up again today for TRACS).
