### ISSUE TITLE
Search doesn't recognize apostrophes

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#289]
I discovered a minor bug in search - it doesn't seem to recognize apostrophes. 

For example, there is a case study entitled "[Evaluating Penn's Green Living Certification](http://hub.aashe.org/browse/publication/1265/evaluating-penns-green-living-certification-successes-and-recommendations-for-improvement)". However, [searching for "Penn's"](http://hub.aashe.org/browse/?search=penn%27s) returns zero results. 

I tried some experiments to try to understand the boundaries of the problem and other punctuation that I tried seemed to work. Apostrophes always seem to lead to zero results when used in a possessive  (e.g., ["university's"](http://hub.aashe.org/browse/?search=university%27s) returns no results but ["university 's"](http://hub.aashe.org/browse/?search=university+%27s) returns 1645 results.

**Comment by monika-aashe** [comment]
It actually doesn't capture most characters - quotation marks, hyphens, colons, etc. This is why when I search on a title that has one of these characters, using the exact title in the search including the characters, it brings up zero results.

**Comment by monika-aashe** [comment]
Not sure if this is being addressed through recent search improvements - adding to inbox for discussion

**Comment by monika-aashe** [comment]
Also related to #289

**Comment by jamstooks** [comment]
Closing this, as it will be addressed in #281.
