### ISSUE TITLE
Order organization options alphabetically

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#291]
In the organization field of submission forms and filters, organizations that include the letters that a user types are listed in dropdown format. As indicated in this image, they are ordered in a non-obvious way that can make it unnecessarily difficult users to find the organization they are seeking:
![image](https://cloud.githubusercontent.com/assets/15839046/14589997/9b0d7de4-04bd-11e6-9b7b-e5e4e80e5bd1.png)

To remedy this, matching organizations should all appear in alphabetical order.

**Comment by baronvonvaderham** [comment]
Unassigning myself for now. I'll address other tickets and circle back if Ben doesn't take it.

**Comment by jamstooks** [comment]
@baronvonvaderham - FYI: I found the `sortField` setting in the [selectize usage documentation](https://github.com/selectize/selectize.js/blob/master/docs/usage.md#data_searching).
