### ISSUE TITLE
Export Green Funds data from IRC into Google Sheet

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#296]
In preparation for round 2 of IRC to Hub exports, please send a link to a Google Sheet file of the following green fund datasets to Monika for formatting before importing into the Hub:
- Campus Sustainability Green Funds Database (154 listings) - http://www.aashe.org/resources/green-funds/
- Campus Sustainability Revolving Loan Funds (85 listings) - http://www.aashe.org/resources/campus-sustainability-revolving-loan-funds/

Note: Monika will manually add info from the following sources: 
- http://www.aashe.org/resources/mandatory-student-fees-renewable-energy-and-energy-efficiency
- http://www.aashe.org/resources/alumni-sustainability-funds

Considerations:
- Please complete files by Monday, April 25
- Please include all data fields collected through forms or included on the dataset
- Please send each list as a separate tab on the same Google sheet file).
- Please ensure that nothing is missing from the lists (see counts above).
- Please try to remove any special character issues.
- If possible, include the date and time the IRC resource was submitted and/or approved.

**Comment by charris2015** [comment]
Hey Monika, 

Here's the [folder](https://drive.google.com/a/aashe.org/folderview?id=0B-OBXNpaVv-Oc3N0WU9FU1NhZmM&usp=sharing) for the green funds data. Let me know if you have any questions.

**Comment by monika-aashe** [comment]
This is in progress, but I won't have time until late summer (after SCI is published). Need to decide whether to prioritize as task for Jade.
