### ISSUE TITLE
Admin features to Support Awards

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#298]
There are some challenges with integrating AASHE Awards with the Hub, but a few fixes under Admin may help address this:

- [Publications list in Admin](http://hub.aashe.org/_ad/content/publication/) should have "Publication Type" and "Publication Release Date" on the table view, as well as published status (can remove Notes and make title field more narrow). This will allow staff to keep track of the number of Research resources submitted/approved specific to the Awards program. 
- [Case Studies list in Admin](http://hub.aashe.org/_ad/content/casestudy/) should have Student Leadership Award status and change Date Published to Date Submitted. You can remove "Notes" and make title column more narrow. 

For the [All Resources View](http://hub.aashe.org/_ad/content/contenttype/), we do still want to include the Notes Column for now.

**Comment by monika-aashe** [comment]
An alternative (that may be easier) would be to simply add these items as filters on the pages (see right side of admin screen).

**Comment by jamstooks** [comment]
I have added these columns and added the filters. There is no date submitted field right now. I could certainly see this being useful and would be happy to add one. Do you have a suggestion for an initial value?

**Comment by monika-aashe** [comment]
@jamstooks - the date submitted field is actually "Date submitted/created/founded/presented" - this is related to #284

**Comment by jamstooks** [comment]
Ah. Ok, thanks... Incidentally, do you think we need another date field for when the resource was submitted? We don't currently store that...

**Comment by monika-aashe** [comment]
It does appear we are capturing it in Admin, but it's being called "Created" - you can see it on the [All Resources admin list](https://hub.aashe.org/_ad/content/contenttype/)

**Comment by jamstooks** [comment]
So I think these are done. Do you still want the Case Study to have the date created field displayed? It seemed in our discussion that that was least relevant for that content type...

**Comment by monika-aashe** [comment]
I think what we have now is good. Feel free to close the ticket
