### ISSUE TITLE
Search: Inconsistent results between local and Heroku ElasticSearch 

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#30]
Comparision between local dev machine and Heroku:

Local development machine, with ElasticSearch installed with Homebrew. No special settings.

```
In [11]: from haystack.query import SearchQuerySet, Raw
In [12]: SearchQuerySet().all().count()
Out[12]: 17

# 'Diver' wouldn't find diversity 
In [16]: SearchQuerySet().filter(content=Raw('diver')).count()
Out[16]: 0

# I explicitely need to add the *
In [17]: SearchQuerySet().filter(content=Raw('diver*')).count()
Out[17]: 3
```

Heroku:

```
In [2]: SearchQuerySet().all().count()
Out[2]: 17

In [3]: SearchQuerySet().filter(content=Raw('diver')).count()
Out[3]: 9

In [4]: SearchQuerySet().filter(content=Raw('diver*')).count()
Out[4]: 9
```

I think it's either a simple setting, that bloats results up on Heroku, or its related to the `EdgeNgramField` we use. This field tokenizes the search text and allows partial matching. That might not work on my local machine, and the fallback is more restrictive.

**Comment by bartTC** [comment]
Alright, the Field change fixes it and gives me the same results as locally:

https://aashe-hub-dev.herokuapp.com/browse/?search=diver
https://aashe-hub-dev.herokuapp.com/browse/?search=diver*

**Comment by jamstooks** [comment]
Nice work! :)
