### ISSUE TITLE
Embed videos in video resource pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#300]
Currently video resource pages just include a link to the video another site. To keep people on our site and enhance the user experience, embed videos directly onto the video resource detail pages, ideally between the title box and the description box.

**Comment by dodget** [comment]
@monika-aashe - Is there a preferred name for the embedded video's panel title?


<img width="905" alt="screen shot 2018-02-06 at 8 59 50 am" src="https://user-images.githubusercontent.com/12410482/35863403-8ff55e06-0b1c-11e8-8576-08a925cba9ea.png">

**Comment by monika-aashe** [comment]
Not sure what you mean, but the one you reference has the Resource Title at the top left, which I think is fine.

**Comment by dodget** [comment]
I have this working locally, and it supports Youtube and Vimeo content. Is this something that should be reviewed before I issue a Pull Request?

**Comment by monika-aashe** [comment]
Looks good to me!

**Comment by monika-aashe** [comment]
Decision: Let's embed videos only for the Videos and Webinars content type only (May decide down the road to embed videos for other content types, but they need to be embedded further down the list.

**Comment by monika-aashe** [comment]
See support ticket from Rachel

**Comment by dodget** [comment]
The fix has been deployed. Please, let me know if there are any issues. Thanks Monika and Rachel!

**Comment by dodget** [comment]
Closing, for now.
