### ISSUE TITLE
Links to files with long titles break

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#302]
I just discovered a [publication where the link to the file breaks](http://hub.aashe.org/browse/publication/1540/student-activities-climate-change-resource-guide-how-student-affairs-professionals-can-contribute-to-campus-climate-neutrality). It appears that this is due to the length of the URL because the f seems to be missing at the end of the file URL: "http://hub-media.aashe.org/uploads/0How20Student20Affairs20Professionals20Can20Contribute20to20Campus20Climate20Neutrality.pd". Sadly, merely adding an "f" to the link doesn't make the link work. 

I don't have any easy way to determine how many other publications this impacts but obviously making sure the existing links work is a high priority.

**Comment by monika-aashe** [comment]
I just fixed for the issue for this file by accessing the [original migration file](https://docs.google.com/spreadsheets/d/1VxCKT8g6t_6iqytXy7syRFbU0oqCCQCPGM2gCm53l4o/edit#gid=0) and accessing the original IRC publication. FYI, whenever I tried to save the new file I initially tried the same file name, but got an error message saying something like "Please upload a file with a file name that is fewer than 100 characters (this one has 104)". I changed the file name and had no issue. 

A user reached out with a similar issue last week and I used the same approach to fix this. 

We should probably hold off on deleting the IRC files until this is resolved (I believe Jessica is only deleting web pages, not uploaded files, right?)

**Comment by jamstooks** [comment]
Right, she's not removing uploaded files.

So any new submissions won't have the issue, because we have that catch in place. I'm bummed the migration process didn't catch the error in the same way as submissions.

In the meantime, I can write a script to list the resource files that are 100 characters long, which likely means that they have been truncated.

We'll still have to go through those and find the original file and re-upload though :(

**Comment by jessicaaasheaashe** [comment]
So far I have only deleted the Academic Programs web pages.  Should I hold off on deleting the others until this is resolved?

**Comment by jamstooks** [comment]
We're ok, @jessicaaasheaashe. Continue to remove things if you want.

**Comment by monika-aashe** [comment]
If you write the script @jamstooks , I'm happy to do the re-uploads.

**Comment by jamstooks** [comment]
Turns out, I didn't have to re-upload. There were 16 files with the issue. I just renamed the files and update the database. This is fixed and I'll add that kind of error-checking into the next imports.
