### ISSUE TITLE
Salesforce clean-up

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#303]
Lots of accounts in our Salesforce database (especially international) have missing information. This means that they are excluded from certain filter views (city/state/country, student FTE). In addition to title and website, at minimum, every account should include address (at least city, state/province, and country), and campuses must include a number under "FTE Enrollment (All Degrees)". We should also try to incorporate latitude-longitude coordinates wherever possible for future mapping features. Would be good to get an export of this data and assign someone to take care of this. 

Note: This may also be addressed during the migration process of the new AMS.

**Comment by peltonc** [comment]
All campuses also need lat/long to be included on the STARS map.

On Tue, Apr 26, 2016 at 6:51 PM, monika-aashe <notifications@github.com>
wrote:

> Lots of accounts in our Salesforce database (especially international)
> have missing information. This means that they are excluded from certain
> filter views (city/state/country, student FTE). In addition to title and
> website, at minimum, every account should include address (at least city,
> state/province, and country), and campuses must include a number under "FTE
> Enrollment (All Degrees)". Would be good to get an export of this data and
> assign someone to take care of this.
>
> Note: This may also be addressed during the migration process of the new
> AMS.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/303>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Are we looking at incorporating maps into the Hub at some point down the road?

**Comment by juliandsmith** [comment]
It's probably a way off, but I would love to have maps for many of the content types. I can see it as being especially relevant for project content types like solar installations and campus farms. It would be cool for academic programs too actually.

**Comment by monika-aashe** [comment]
That's what I figured. We may need to consider recording coordinates for non-campus orgs as well, in that case.

**Comment by jessicaaasheaashe** [comment]
Yes, we will likely need to do a "data scrub" as we migrate to the new AMS. It would be a good idea to think about all of the different attributes we want to capture in the AMS for each institution so that we can build them into the new AMS.

**Comment by monika-aashe** [comment]
Check w/ Ben whether changes made now in SF or later in new AMS automatically update in the Hub (I seem to recall a recent ticket about this that Bob implemented)

**Comment by monika-aashe** [comment]
January 2017 is when transition to new AMS will happen. Programs staff are welcome to make edits.

**Comment by monika-aashe** [comment]
Monika to request report of all organizations with resources in the Hub and will cross-reference against SF report - priority to ensure that all of these orgs have all info included. 

Probably after the conference.

**Comment by monika-aashe** [comment]
In progress with ongoing AMS maintenance - closing since not really related to Hub IT.
