### ISSUE TITLE
Redirect climate action planning wiki pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#305]
We are no longer actively maintaining or promoting the [climate action wiki](http://www.aashe.org/wiki/cool-campus-how-guide-college-and-university-climate-action-planning), so all traffic beginning with http://www.aashe.org/wiki/ should be redirected to http://hub.aashe.org/browse/publication/1444/cool-campus-a-how-to-guide-for-college-and-university-climate-action-planning, which is where the pdf version of the wiki lives.

**Comment by baronvonvaderham** [comment]
Nginx config updated
