### ISSUE TITLE
Uploaded files for 2008 Conference Presentations from IRC migration not opening 

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#306]
Several hundred uploaded files from 2008 conference presentations that were migrated from the old IRC are not opening (see [example](http://hub.aashe.org/browse/presentation/11958/teaching-sustainability-using-an-on-farm-community-supported-agriculture-framework)). While it appears to download successfully, the file format is messed up and there is an error message upon trying to open that reads something like, "There is no application set to open the document “dl (1).phpf27_Download_Poster_PPT".  

It appears that this is an issue with all of the 2008 Conference Presentations that have uploaded files. See rows 3174 through 3309 of the [Conference Presentations migration file](https://docs.google.com/spreadsheets/d/11Z3sH6_JcM36RIQ6xilU6wA19VssrgGmGQwwpA8mz0w/edit#gid=0).

**Comment by jamstooks** [comment]
I wrote a script to fix all of these and they seem to be good now.
