### ISSUE TITLE
Order of author names is *sometimes* reversed

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#308]
In research publications, the order of authors is often significant. In particular, the first author is typically the person with whom readers should contact with questions. However, [an article I submitted recently](https://hub.aashe.org/browse/publication/14866/Mobilizing-the-power-of-higher-education-to-tackle-the-grand-challenge-of-sustainability-Lessons-from-novel-initiatives) is presenting the authors in the opposite order from how I entered them (as you can see on the admin side). 

This behavior isn't universal however, as you can see from [this article](https://hub.aashe.org/browse/publication/12271/Transdisciplinary-research-in-sustainability-science-practice-principles-and-challenges), where names are presented in the same order on the public and admin sides. Any idea what is happening here? 

In any case, author names should always appear in the same order on the public and admin views. Ideally, there would be a way to easily rearrange author order via the admin view.

**Comment by juliandsmith** [comment]
It turns out that this ordering issue is actually an issue for the awards process because we require that students be the first author for student leadership awards. The reverse ordering bug identified here can make it look like students aren't the first author and therefore the submission isn't eligible. For example, [this case study](https://hub.aashe.org/browse/casestudy/14962/Zygmunt-the-electric-car) shows the first author to be the Director of the Engineering Department. It's only by checking the admin side that we can see that students were listed first.  

Anyway, I'm moving this to the awards milestone as a result.

**Comment by jamstooks** [comment]
This is fixed. It might take 12 hours to take effect on some resources due to caching.
