### ISSUE TITLE
Report of Organization Name and ID needed for migrations

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#309]
Chris,
Please run a report where I can get a list of ALL AASHE organizations (including campuses, businesses, non-profits, K-12, etc.) along with the 5-digit Salesforce organization ID. The list should look something like [this](https://docs.google.com/spreadsheets/d/14C-mfG8BCIjaWxmlYgB-A10d1JHB_-TytjLeFjENdhg/edit#gid=0). 

Reason for this request is that the most recent version is needed considering the de-duplication project from a few weeks ago (I want to avoid classifying something under one of the deleted codes).

Thanks in advance

**Comment by charris2015** [comment]
Hey Monika ,

Here's an [updated spreadsheet](https://docs.google.com/a/aashe.org/spreadsheets/d/1d6xcL_436wh0L863oleOpfbyIXL9HgifwqrueXuluOk/edit?usp=sharing) with the account names and ID's. Let me know if you have any additional requests.
