### ISSUE TITLE
Remove Duplicate Orgs in Hub

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#312]
**Duplicate Accounts**
Chatham University
- Keep the account that has [19+ associated resources](https://hub.aashe.org/browse/?search=&organizations=15760&country=)
- Delete the account that has [0 associated resources](https://hub.aashe.org/browse/?search=&organizations=91166&country=)

Emory University
- Keep the account that has [35+ associated resources](https://hub.aashe.org/browse/?search=&organizations=16287&country=)
- Delete the account that has [0 associated resources](https://hub.aashe.org/browse/?search=&organizations=91169&country=)

Minnesota Green Chemistry Forum
- Keep the account that has [1+ associated resources](https://hub.aashe.org/browse/?search=&organizations=88030&country=)
- Remove the account that has [0 associated resources](https://hub.aashe.org/browse/?search=&organizations=91326&country=)

Yale University
- Keep the account that has [53+ associated resources](https://hub.aashe.org/browse/?search=&organizations=19360&country=)
- Remove the account that has [0 associated resources](https://hub.aashe.org/browse/?search=&organizations=91171&country=)

**URL, not an Organization**
- Delete [oregonstate.edu](https://hub.aashe.org/browse/?search=&organizations=91473&country=)
- Delete [chatham.edu](https://hub.aashe.org/browse/?search=&organizations=91487&country=)
- Delete [clemson.edu](https://hub.aashe.org/browse/?search=&organizations=91598&country=)

**Comment by monika-aashe** [comment]
Closed #282 in favor of this ticket, which includes several related issues. @rerb

**Comment by rerb** [comment]
Hi, Monika.  Have the Salesforce Accounts associated with the duplicate organizations been deleted in Salesforce?

**Comment by monika-aashe** [comment]
Not yet, but we submitted an IT ticket. Here is the info:

Subject: Accounts with Partial Web URL's
MAY 04, 2016  |  04:22PM UTC 
Chris, Do you know why there are a bunch of accounts in salesforce that are partial web URLs? Here is an example: https://na7.salesforce.com/001A000001LOH61/d?retURL=%2F001A000001LOH61%3FsrPos%3D0%26srKp%3D001&nooverride=1 This one says it was created by you yesterday

MAY 04, 2016  |  08:31PM UTC 
Christopher Harris replied:
Hey Monika,
After looking into it, I found that Desk.com, our ticketing service that’s synced to Salesforce was creating new accounts in Salesforce based on some cases it received. I’ve turned off the feature that updates account information in Salesforce based on changes made in Desk. I’ll keep an eye on it in the meantime to make sure that it’s not creating additional .edu accounts. I’m also going to delete the accounts that already contain .edu in the name. Let me know if you have any additional questions.
Thanks,

**Comment by monika-aashe** [comment]
@rerb - see IT support ticket titled "Remove duped org in Salesforce" (may be assigned to Chris H or Noah). I created a [list of accounts that need to be removed](https://docs.google.com/spreadsheets/d/1d6xcL_436wh0L863oleOpfbyIXL9HgifwqrueXuluOk/edit#gid=225851832), and Noah or someone else will get to work on removing them soon. However, based on your comment related to #282, simply deleting will not get these out of the Hub. Do you have any recommendations on an efficient fix?

**Comment by rerb** [comment]
I'll delete them manually from the hub, but if I do that before they're
deleted in Salesforce, they'll just get recreated.  So they need to be
deleted in Salesforce before they're deleted in the hub.

On Fri, May 13, 2016 at 4:45 PM, monika-aashe <notifications@github.com>
wrote:

> @rerb <https://github.com/rerb> - see IT support ticket titled "Remove
> duped org in Salesforce" (may be assigned to Chris H or Noah). I created a list
> of accounts that need to be removed
> <https://docs.google.com/spreadsheets/d/1d6xcL_436wh0L863oleOpfbyIXL9HgifwqrueXuluOk/edit#gid=225851832>,
> and Noah or someone else will get to work on removing them soon. However,
> based on your comment related to #282
> <https://github.com/AASHE/hub/issues/282>, simply deleting will not get
> these out of the Hub. Do you have any recommendations on an efficient fix?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/312#issuecomment-219154676>
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Register <http://www.aashe.org/conference> and join us as we explore sustainability 
“Beyond the Campus” at the 2016 AASHE Conference & Expo 
<http://conference.aashe.org> in Baltimore, Maryland from Oct. 9 - 12.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Okay @rerb , here is the [link to the tab](https://docs.google.com/spreadsheets/d/1d6xcL_436wh0L863oleOpfbyIXL9HgifwqrueXuluOk/edit#gid=1791558613) that has a list of about 70 organizations that have to be deleted from the Hub. Noah already removed them from Salesforce. 

FYI, there's still an issue with SF automatically creating new accounts - until that is resolved, we will continue to have these issues. I'll try to keep the list updated and will provide updates.

**Comment by monika-aashe** [comment]
FYI @rerb I just finished adding 5 or so new resources to the top of the list.

**Comment by rerb** [comment]
Gone gone gone.

On Fri, May 20, 2016 at 1:58 PM, monika-aashe <notifications@github.com>
wrote:

> FYI @rerb <https://github.com/rerb> I just finished adding 5 or so new
> resources to the top of the list.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/312#issuecomment-220675820>
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Register <http://www.aashe.org/conference> and join us as we explore sustainability 
“Beyond the Campus” at the 2016 AASHE Conference & Expo 
<http://conference.aashe.org> in Baltimore, Maryland from Oct. 9 - 12.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
When new duplicate orgs show up, please don't reopen this issue.  Instead, please submit a request to itsupport to have them removed.
