### ISSUE TITLE
Revise Application error message when time-out happens

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#314]
~~A member user of the Campus Sustainability Hub gets an Application error when trying to attach images. Monika encountered this issue before when submitting a resources on a user's behalf, and it appears to be related to large file size. It would be helpful to: 
1. increase the file size capacity if possible;
2. add help text to the image upload option on every form (possibly the file uploads field too) stating, "file size of all uploaded files and images for a single resource submission should not exceed xyz";~~
3. providing a more descriptive error message than "Application Error: An error occurred in the Application and your page could not be served. Please try again in a few moments. If you are the application owner, check the logs for details".

**Comment by monika-aashe** [comment]
Here is the link to [the resource](https://hub.aashe.org/_ad/content/outreachmaterial/14819/) where I encountered this issue as well. The error occurred when I tried to upload 5 images in the submission form, so I only uploaded two images. Then I went into Admin and uploaded the remaining three images.

**Comment by monika-aashe** [comment]
Referenced in AASHE IT Support ticket titled, "Issue with uploading file to existing Hub Resource" sent on 5/26/16.

**Comment by jamstooks** [comment]
[ ] notify monika when these errors happen
[ ] update the application error page

**Comment by monika-aashe** [comment]
Two options for updating help text - more and less detailed - I wanted to check with you all to see if the edits are okay or need revision before Ben implements. @jamstooks @juliandsmith @peltonc 

Less detailed:
Server Time-out: A time-out error occurred and your submission could not be processed. Please contact resources@aashe.org for next steps in submitting your request. 

More detailed:
Server Time-out: A time-out error occurred and your submission could not be processed. Please try resubmitting with smaller uploaded files or no files. You can also email resources@aashe.org to share file attachments and connect with AASHE staff about next steps.

**Comment by monika-aashe** [comment]
We are getting angry feedback from members that are experiencing this issue. Can we please update the messaging ASAP? @jamstooks I'm fine with either of the above or a variation. Thanks!

**Comment by monika-aashe** [comment]
Hey @jamstooks , I reread that and realized how b*tchy it sounded. That was not my intention so my apologies!

**Comment by monika-aashe** [comment]
Other potential short-term solutions:
- Julian's suggestion: "I wonder if we could simply limit the number of uploaded files in the interim to made this a bit less likely at least." 
- Temporarily updating the help-text to the images and file fields in the submission forms to specify a size limit or give warning. 
- Ensuring that a timed out submission can somehow be saved without the attachment so folks don't lose content (not sure if this has been already considered or is even feasible)

**Comment by jamstooks** [comment]
I've updated our "Application Error" page. Here's the new one:

https://hub-media.aashe.org/static/error_pages/application_error.html

**Comment by jamstooks** [comment]
I've created another ticket that gets at the heart of the issue: #339

**Comment by juliandsmith** [comment]
I love the new error message but when I try to upload something with a large file, I only keep getting this type of error message from my browser: 
![image](https://cloud.githubusercontent.com/assets/15839046/15969441/20194d96-2efe-11e6-944e-4cf3aca43241.png)

**Comment by monika-aashe** [comment]
I just tried to submit a resource with a large file and I did get the revised application error that Ben created. Julian, I'm not sure why your error message was different, is this something that happens more than once? 

I also clicked "back" from the error page and was able to access the resource with the fields that I had completed previously (minus the upload files)

**Comment by juliandsmith** [comment]
Yep, I tried three times and received the error message from my browser rather than the one that Ben created. The back button thing worked though, which is great. I don't know if matters, but the file I tried to upload is was an m4v file from last year's staff retreat - it was the biggest fine I could find easily.

**Comment by monika-aashe** [comment]
[AASHE Hub Award--Ball State University_attachments.pdf](https://github.com/AASHE/hub/files/309448/AASHE.Hub.Award--Ball.State.University_attachments.pdf)

Here's the one I used, maybe it's an invalid file format so there's a different message?

**Comment by monika-aashe** [comment]
Do we still need this open since we also have #339

**Comment by jamstooks** [comment]
Yes. Thanks. Closing this in favor of #339.
