### ISSUE TITLE
Add "Unknown" option to date created filter

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#319]
Since we often don't know the creation dates for some types of resources (e.g., academic programs, research institutes), we need an unknown option as part of the filter so that users can more easily see that we have a lot of resources without dates.

**Comment by jamstooks** [comment]
Do you think people will actually want to filter out just the ones with "unknown" values? It doesn't feel like a common use-case of the filter.

If your only goal is to communicate to folks that some of these values could be empty, then I'm not sure that's the best way to do it...

**Comment by juliandsmith** [comment]
Fair point. I can't think of many cases where you'd specifically want to find programs with no date provided. The goal for me really is more around people not being too confused when there are relatively few results when using this filter. Having a box for unknown helps explain this situation fairly easily but I'm definitely open to another way of accomplishing it.

**Comment by monika-aashe** [comment]
I'd lean toward not providing this as a filter and communicating the absence of date created data another way. Maybe something to discuss.
