### ISSUE TITLE
Add redirects for old award applications

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#326]
As part of the website clean up, Jessica will be deleting all of the [Campus Sustainability Profiles](http://www.aashe.org/resources/profiles/campus-sustainability-profiles) and [Student Sustainability Leadership Stories](http://www.aashe.org/resources/student-sustainability-leadership-stories). Before she does that, we'd like to set up redirects so that anyone who tries to visit those pages doesn't get an error message. 

Specifically, any URL that begins with either http://www.aashe.org/resources/profiles/ or http://www.aashe.org/resources/awards/ should be redirected to hub.aashe.org

**Comment by baronvonvaderham** [comment]
Nginx config updated
