### ISSUE TITLE
All photograph URLs are directing to a single resource

### ISSUE THREAD

**Issue by peltonc** [AASHE/hub#327]
When clicking on any resource in the photographs content type:
https://hub.aashe.org/browse/types/photograph/

I am directed to the same resource:
https://hub.aashe.org/browse/photograph/14921/Austin-College-GreenServe-2016

The URL for each resource appears to be correct, but the content is always the same.

**Comment by juliandsmith** [comment]
Actually, ALL resources of any type (not just photographs) seem to link to the Austin College resources. This is a major bug so I hope we can fix ASAP!

**Comment by juliandsmith** [comment]
Looks like this was a result of the caching issue that Ben has been working on. Ben just turned that off and everything seems back to normal. He'll be working to figure out what went wrong before re-implementing caching.

**Comment by jamstooks** [comment]
Ok, caching is now back in place and the bug is fixed. Thanks for pointing it out! @peltonc please feel free to text me or hit me up on skype if you see something like this outside of normal working hours.
