### ISSUE TITLE
Filter: Organization Type

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#33]
The following types should be added as a filter throughout the Hub (ideally, in this order):
Doctoral/Research institution
Master's institution
Baccalaureate institution
Associate (2-year) institution
College or university system
Business
Non-profit/NGO
Government agency
K-12 school

**Comment by jamstooks** [comment]
@monika-aashe What about Special Focus and Tribal?

**Comment by monika-aashe** [comment]
Reopening due to minor issue: There is no way to uncheck a selection or select multiple. Consider making this a check box instead of dropdown to make this doable.

**Comment by monika-aashe** [comment]
Hey @jamstooks I forgot to comment about your question about tribal/special focus. We decided to not include those because these institutions also fall under one of the other categories, and because there are so few of these, so they wouldn't allow for great comparisons. There might be a case for adding a "tribal institution" keyword/tag.
