### ISSUE TITLE
Move Hub intro text up on Home pages

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#331]
Hub team decision on 5/25/16:

Move the text that reads, "The Campus Sustainability Hub is a one-stop shop for AASHE members to access toolkits and resource collections about all aspects of sustainability in higher education..." up so that it is right below the breadcrumb navigation. This should apply to the [Home - Browse Topic](https://hub.aashe.org/) and [Home - Browse Content Type](https://hub.aashe.org/#contenttypes-panel) pages only.

**Comment by baronvonvaderham** [comment]
Additionally, I removed some padding from the top of the main content block. After moving this text, there was a lot of dead space for no reason, the result of padding on multiple classes stacking together, which pushed the start of the actual content to halfway down my screen. This narrows that gap between the breadcrumbs and the title/tabs on all pages, which looks a lot cleaner.

**Comment by monika-aashe** [comment]
Are you guys in the process of changing something in the Hub? This is what
the homepage looks like right now, and I'm getting a weird "Authentication
required" box, even though I'm logged in:



​
​

On Tue, Jul 12, 2016 at 1:12 PM, Scott Johnson <notifications@github.com>
wrote:

> Closed #331 <https://github.com/AASHE/hub/issues/331>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AASHE/hub/issues/331#event-720436237>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AOgozforODdBNvZstyZC_DvdV7J7cIq-ks5qU8rvgaJpZM4ImwVJ>
> .
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 
Register <http://www.aashe.org/conference> and join us as we explore sustainability 
“Beyond the Campus” at the 2016 AASHE Conference & Expo 
<http://conference.aashe.org> in Baltimore, Maryland from Oct. 9 - 12.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
