### ISSUE TITLE
Add ability to upload large files

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#339]
To avoid timeout errors, we need a workaround for Heroku's 30 second timeout for uploading large files attached to resources.

Also need to decide on file size limitations.

**Comment by jamstooks** [comment]
This tool might work: https://github.com/bradleyg/django-s3direct

**Comment by monika-aashe** [comment]
Other potential short-term solutions:

Julian's suggestion: "I wonder if we could simply limit the number of uploaded files in the interim to made this a bit less likely at least."
Temporarily updating the help-text to the images and file fields in the submission forms to specify a size limit or give warning.
Ensuring that a timed out submission can somehow be saved without the attachment so folks don't lose content (not sure if this has been already considered or is even feasible)

**Comment by jamstooks** [comment]
@monika-aashe @peltonc @juliandsmith 

I think I have a working demo of this on the dev site. It's not perfect, but I think it will give you the general gist.

To test it, try [creating a photograph resource](https://aashe-hub-dev.herokuapp.com/submit-resource/photograph/). You'll see that when you select an image file, it will begin to upload immediately and the submit button will be disabled until the upload completes. The same functionality applies in the admin if you're adding images.

I haven't added support for files yet, but can do that shortly if you're happy with the way this works...

Let me know...

**Comment by jamstooks** [comment]
Have any of you had a chance to check this out? I'd like to commit it this week, if possible...

**Comment by monika-aashe** [comment]
I really like this fix a lot! I did get an error message (below) once the large file finished uploading and I clicked submit, but this may have to do with the fact that it's on the dev site. Thanks for the reminder!

![screen shot 2016-07-11 at 5 12 06 pm](https://cloud.githubusercontent.com/assets/15214797/16746947/c36cd068-478a-11e6-878f-6ff2c3f723de.png)

**Comment by monika-aashe** [comment]
BTW, I definitely recommend adding this function for files too.
