### ISSUE TITLE
Filters: Conference Presentation

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#34]
1. The filter for "presentation date" is missing. 
UPDATE: we decided to call the "Presentation year" 

2. The filter for "Conference Name" is missing - need to ensure this is added in metadata on Admin side so that we can add new conference names. Right now, the only options should be "AASHE" and "Other".

**Comment by monika-aashe** [comment]
Priority level for "presentation date" filter is high; priority level for "conference name" is low.

**Comment by juliandsmith** [comment]
As part of this ticket has been superseded by #284, I'm closing this ticket and adding a new one for the conference name filter for clarity.
