### ISSUE TITLE
Add links to more resources on toolkit pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#351]
When visitors come to the topical toolkits, they may not immediately notice the tab linking to the full list of resources. To help them find their way to the full list of resources, add a simple "View all" link (or button) under the lists of Featured Resources and New Resources.

**Comment by monika-aashe** [comment]
Moved to inbox to discuss. Would be nice to have a button similar to what was recently added for the Content Type landing pages. Currently, there is a hyperlink that doesn't actually take you to that page. 

Example: https://hub.aashe.org/browse/topics/curriculum/#resources-panel
