### ISSUE TITLE
Search should interpret quotation marks and return different results when these are used

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#353]
When a search query is included in quotation marks, Google and other search tools that our users are familiar with typically return only those results that use the exact text contained within the quotation marks.  As a result, searching for "faculty learning communities" will return much narrower list results than searching for faculty learning communities. In contrast, the Hub search tool seems to largely ignore quotation marks. As a result, searching for these terms returns almost the same number of results, the vast majority of which never use use the term "faculty learning communities". For some reason, the query [in quotation marks](https://hub.aashe.org/browse/?search=%22faculty+learning+communities%22) returns slightly fewer results than [without quotation marks](https://hub.aashe.org/browse/?search=faculty+learning+communities).

To help users find relevant resources more quickly, the search tool should interpret quotation marks in the same way as Google and only show results that include the exact term in quotation marks.

The ticket is a complement to #289, which is focused on making sure other punctuation doesn't break the search.

**Comment by juliandsmith** [comment]
"General education" is a terrific example of a query where recognizing quotation marks could really make a difference. "General education" refers to a very specific thing in higher education and getting every result that contains the words "general" and "education" isn't very helpful.

**Comment by monika-aashe** [comment]
Closed in favor of #281 which will cover this.
