### ISSUE TITLE
Provide a way to uncheck a discipline or office via admin

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#354]
Currently, if a resource is incorrectly assigned a Academic Discipline or Office(s) or Department during submission, there is no way to unassign a discipline or office via the admin interface. It is possible to select a _different_ discipline or office, but not to remove the office or discipline entirely if none actually fit.

**Comment by monika-aashe** [comment]
I have had success in changing the academic discipline and/or office info in the admin, but maybe I'm missing something? Same approach as changing topic. I use command/control to edit/add more than one.

**Comment by juliandsmith** [comment]
Changing between disciplines or offices is no problem. What isn't possible is selecting to _no_ discipline or office. For example, if someone has submitted a resource that they incorrectly said was related to Environmental Studies when it actually isn't associated with any discipline at all, there's no way to make it so that no discipline is associated with that resource.

**Comment by monika-aashe** [comment]
I'm able to uncheck all by holding down the command/control button (or the Windows button on a Microsoft keyboard) and clicking the checked field with my mouse. Does that not work for you?

**Comment by juliandsmith** [comment]
Huh. I thought I tried that but it did seem to do the trick this time. Thanks! I'll close the ticket.
