### ISSUE TITLE
Image placement randomly skips spaces on certain resources

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#355]
Seems to happen randomly. See [example](https://hub.aashe.org/browse/photograph/14956/Vassar-College-and-Earth-Month)

**Comment by baronvonvaderham** [comment]
Finally figured this out. The height of each block is variable, based on how long the text blurbs under the images were. The first item in the second row tries being placed as high on the page as possible, prioritizing that over being as far left as possible. If the first item in the first row is the tallest, then it gets bumped to the right to accomplish this, leaving that blank space.

The solution was setting these blocks to a fixed height so they're all the same, which has the added benefit of making sure all images in each row are aligned (I think that looks nicer).
