### ISSUE TITLE
Filter: Publications

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#36]
1. Filter for "release date" missing 
UPDATE: we decided to change name of filter to "Year Published"

2. Filter for "Type of Publication" missing - here are the final dropdown options:
Book
Book chapter
Journal article
News or magazine article
Blog article
Published report
Student thesis/dissertation
Other student research

**Comment by monika-aashe** [comment]
The priority level for "release date" filter is high; priority level for "type of material" is medium.

**Comment by monika-aashe** [comment]
Type of Material is also high priority, for AASHE awards and the ability to view recently submitted resources.

**Comment by juliandsmith** [comment]
As part of this ticket has been superseded by #284, I'm closing this ticket and adding a new one focused only on Type of Material filter for clarity.
