### ISSUE TITLE
Feature submitter name on resources

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#364]
We've discussed doing this for Phase 3, adding to inbox for discussion after seeing the [PLAN resource center](http://www.postlandfill.org/resource-center/)

**Comment by dodget** [comment]
This should be simple, and I'd like to roll this feature into the next deploy.

Any preference on where this is placed? Should we explore if this can be clickable, which would lead to a list of all the resources submitted by this submitter? Or, is that not useful?

**Comment by monika-aashe** [comment]
It would be good to discuss - one of my concerns is that this will underline the fact that so many of our resources are submitted by AASHE staff rather than the campus sustainability community at large.

**Comment by dodget** [comment]
Cued up for this week's deploy.

**Comment by dodget** [comment]
Deployed to production. Closing, now.
