### ISSUE TITLE
Create AASHE only access level for resources

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#365]
From Jessica: It would be helpful to have an AASHE only access level so that we could include photos and other materials for internal use that aren't useful for members (e.g., conference photos). The goal is to be able to have all of our photos in one place.

**Comment by monika-aashe** [comment]
I think this is addressed by our Image features milestone but should confirm.

**Comment by juliandsmith** [comment]
To my knowledge, the planned image features don't provide for an AASHE only access level for photos that aren't intended for sharing with members.

**Comment by juliandsmith** [comment]
We no longer think this is worth pursuing; closing for now.
