### ISSUE TITLE
Add ability to update submitter in Admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#373]
This field seems to be editable in the admin but it isn't. 

This would be useful when a user submits a valid resource under the wrong Content Type, so we resubmit on their behalf. Will also become a factor when we add/highlight submitter information to the resources.

**Comment by baronvonvaderham** [comment]
Marking as wontfix, this is actually already a feature. Click the magnifying glass next to the submitter field and it will pop out a selector window where you can search for the user you want (probably via email address) and then click the link at the far left (_drupal_uid_###). Then it should automatically update that field for you with the necessary database key.

**Comment by monika-aashe** [comment]
Okay, thanks for verifying and providing the steps. I thought I'd checked for this and it didn't seem to work, but maybe I did something wrong. I went in and updated those that I had marked to update submitter info.
