### ISSUE TITLE
Search button labels aren't as clear as they could be

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#375]
The labels on the two buttons next to the search box - "Go" and "All Resources" - are potentially confusing to users. If they wish to search from within all resources, they might choose to click the "All Resources" button instead of "Go", which will not produce the desired result. 

To make the different purposes of these buttons clear, relabel "Go" as "Search" and "All Resources" as "Browse All".

![image](https://cloud.githubusercontent.com/assets/15839046/17785935/b2e1da02-6550-11e6-98df-a240fbebd4ce.png)

**Comment by monika-aashe** [comment]
Ben: All resources should be different al together (e.g. text link below search)
