### ISSUE TITLE
"Login Required" label should be centered above login box.

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#379]
See below.

![screen shot 2016-08-29 at 9 48 01 am](https://cloud.githubusercontent.com/assets/609008/18053518/d9935b78-6dcd-11e6-8acd-5afa98cbd2e8.png)

**Comment by jamstooks** [comment]
Sorry, but this doesn't feel like a bug... just a visual preference. In fact, it's in-line with the styles we're inheriting from the unify theme, so I'm refusing to "fix" it :sweat_smile:
