### ISSUE TITLE
Filter headings

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#38]
The following filter headings should be renamed:
Organization -> Organization(s)
Institution Size -> Student FTE
Published -> Year Posted
Country -> Country/ies
State or Province -> State(s) or Province(s)
Sort by: 
Publish Date -> Most Recent

**Comment by monika-aashe** [comment]
In addition, we'd like to make a few minor changes to the look of the filter's section:
Change text "Filter Results" to "Filters" - keep font style the same.
Make "Sort by" match the font style of "Filters" above

**Comment by rerb** [comment]
Moving "change font of 'Sort' to be like 'Filters'" to its own ticket.  The other tasks in this issue have been addressed, and changing the font of "Sort" without changing the font of all filter labels is not trivial.

Moved to #66.
