### ISSUE TITLE
Mechanism for counting states is off

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#385]
The counter on the content type landing pages seems a little off, considering that there are only 50 US states: 

![image](https://cloud.githubusercontent.com/assets/15839046/18217362/560b48dc-712a-11e6-8e1d-821da8598435.png)

**Comment by juliandsmith** [comment]
That's what I'm guessing is happening. If that's the case and we want to keep it that way, the label on the counter should probably say "U.S. States and Territories" or something so that it doesn't look silly.

**Comment by monika-aashe** [comment]
Checked the report I ran earlier in the week, and it looks like there are about 60 "states" that we count for US, and they are the territories. Example: PR and PW are Puerto Rico and Palau.

If that is indeed the case, updating to U.S. States & Territories would probably be best.

**Comment by juliandsmith** [comment]
While we're changing labels on the counter, we should change "Campuses" to either "Organizations" or "Institutions", depending on whether the count includes businesses, non-profits as well as higher-ed institutions.

**Comment by baronvonvaderham** [comment]
Renamed "Campuses" to "Organizations", and changed "U.S. States" to "U.S. States & Territories". We weren't filtering organizations to just get campus, so no change needed there.
