### ISSUE TITLE
Images with spaces are not thumb-nailed properly

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#388]
It seems that the url strings generated (perhaps by S3Direct) have "+" characters instead of the spaces. This seems to break the thumbnailing because ImageFile.read() returns an 403 error.

**Comment by monika-aashe** [comment]
Oops, I opened a similar ticket (#391) before realizing this was already there. Adding to images milestone per Scott's suggestion.

**Comment by jamstooks** [comment]
This is fixed going forward, but I still need to go through and rename all the existing files.

**Comment by jamstooks** [comment]
This will be a several-step process that I will do in the evening either tonight or tomorrow:

 - [ ] deploy to production
 - [ ] run migrations
 - [ ] run the `rename_images` management command to fix images with "+" or " " in them
 - [ ] run the `create_thumbnails` command to create any thumbnails that need to be created
 - [ ] quality control

**Comment by jamstooks** [comment]
Ran into a few issues, but those can be resolved in #398.
