### ISSUE TITLE
Filter expand/collapse

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#39]
Along with "show all", would like to include a "hide all" so that all filters are collapsable and expandable

**Comment by bartTC** [comment]
We should come up with a different term or probably UI. *Hide all*, I dont want to hide my selected items, I want to see them. It should mean "Hide unchecked" but that sounds nerdy. 

I am also not sure if this is useful from a UI perspective. I mean, I select my stuff, and then I submit the form, then all the unchecked items are collapsed again anyway. Why would I want to hide the list? To get a better overview?

**Comment by monika-aashe** [comment]
What about "expand/collapse"? From a UI perspective it's it's not great that after you expand the filters to see what the choices are, you have a very long list that can't be shortened unless you exit and come back. I think it's fine to hide something you've checked, as long as you can toggle back and forth between expand/collapse.

**Comment by monika-aashe** [comment]
Actually, we are thinking we want to do away with the check boxes and go back to a scroll bar with improved functionality. FYI, I'm going to close this ticket and open a new one.
