### ISSUE TITLE
Issues with images with same file name

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#390]
I received some photo resources from a submitter that had uploaded images that were all labeled "image.jpg". Upon approval, I noticed that certain resources had incorrect images associated, and I'm assuming this is due to the fact that all of the photos have the same file name.  

I've renamed these images and re-uploaded, but it would be great if there is a (relatively straightforward) fix to avoid this in the future (or we add error message to submission form and/or help text)

**Comment by jamstooks** [comment]
Would you mind duplicating this on the [stage site](http://aashe-hub-stage.herokuapp.com/) so that we can see this in action?

**Comment by jamstooks** [comment]
Hi @monika-aashe, could you provide an example somewhere?
