### ISSUE TITLE
Add conference name to conference presentation resources

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#393]
We have a "Conference Name" field associated with every conference presentation, but the conference name doesn't actually appear anywhere in the published resource. For example, 
[this presentation](https://hub.aashe.org/browse/presentation/15511/Making-an-Impact-with-STARS-Benchmarking) is associated with the Smart & Sustainable Campuses Conference on the back end, but the visitor would have no way to know that from looking at the resource. 

As we're trying to encourage other orgs to use the Hub as a repository for their presentations, making this information visible is pretty important.  Ideally, this information would appear somewhere in the top block with presentation date/tags etc.

**Comment by monika-aashe** [comment]
Similar to #285
