### ISSUE TITLE
Linkcheck interval val not parsed correctly

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#398]
All env vars are pased as strings, so the `LINKCHECK_EXTERNAL_RECHECK_INTERVAL` is backlogging our processes with errors:

    FOUND: https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/Inventory+of+Samples+in+-80+degree+freezer.jpg (894)
    	/browse/casestudy/15346/Icebox-Detox-Challenge
    copying uploads/Inventory+of+Samples+in+-80+degree+freezer.jpg to uploads/Inventory-of-Samples-in--80-degree-freezer.jpg 
    Exception in thread Thread-7:
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/app/.heroku/python/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/app/.heroku/python/lib/python2.7/site-packages/linkcheck/listeners.py", line 76, in do_check_instance_links
        u.check_url()
      File "/app/.heroku/python/lib/python2.7/site-packages/linkcheck/models.py", line 185, in check_url
        self._check_external(tested_url, external_recheck_interval)
      File "/app/.heroku/python/lib/python2.7/site-packages/linkcheck/models.py", line 279, in _check_external
        external_recheck_datetime = now() - timedelta(minutes=external_recheck_interval)
    TypeError: unsupported type for timedelta minutes component: str

This isn't crashing servers, but does seem to be raising a lot of errors.

**Comment by jamstooks** [comment]
Hey @baronvonvaderham - is there a quick way to temporarily disable the link-checker? When I'm going through and bulk-setting the new thumbnails, I'm finding that these keep getting kicked off.

Maybe moving to celery for the linkchecker would work too.

**Comment by baronvonvaderham** [comment]
Do you want me to just disable the scheduled task, or remove it from the app entirely? The former's simple, the latter we'd need to go in and gut it from the settings, url, and admin files.

**Comment by jamstooks** [comment]
Adding the `LINKCHECK_DISABLE` env var was good enough for my needs, so I'll close this. The [issue](https://github.com/DjangoAdminHackers/django-linkcheck/issues/61) @baronvonvaderham opened will hopefully happen on the linkcheck end;
