### ISSUE TITLE
Add tags to search

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#406]
In ContentType.save(), 

```python
self.keywords_search_data = " ".join([str(kw) for kw in self.keywords])
# when creating search_vector, include self.keywords_search_data
```

**Comment by monika-aashe** [comment]
Would need to clarify whether search for "water bottles" would recognize a similar tag, "bottled water"

**Comment by monika-aashe** [comment]
Bob will deploy the search engine fix first, will decide later if contractor is needed.
