### ISSUE TITLE
Content: Fix uploaded documents

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#41]
Error message instead:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>uploads/16145548887_72f2c144aa_o.jpg</Key>
<RequestId>E3DBC384DCD056C9</RequestId>
<HostId>
DPwd0U3nnOqxOvwHJUbsIUoG8TDmS43Qk+U9nlXQlLXbRMt4wmjUQICO6QaBnf1q
</HostId>
</Error>

**Comment by bartTC** [comment]
No this is actually all working. The missing files you're seeing are those, where the documents came from my local instance. I only copied the database to Heroku, not the uploaded files. 

You should either re-upload those files, or delete the instances.

I've uploaded new files and they're working fine.

**Comment by jamstooks** [comment]
I can confirm this is resolved. I just tested by uploading a photograph resource and it worked.
