### ISSUE TITLE
Issue with Long URLs showing up as bad links

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#416]
It looks like there is a character limit for the URL field in the Hub, so web pages with really long URLs are incomplete and therefore become bad links. 

See Admin page for this resource: https://hub.aashe.org/_ad/content/publication/16522/change/

The 2nd URL field should include the following link but the last part has been cut off: https://www.cambridge.org/core/journals/australian-journal-of-environmental-education/article/div-classtitleeducation-for-sustainability-graduate-capabilities-professional-employment-how-they-all-connectdiv/34C1D8A3F55711ECA4DE1C84C03F1637

**Comment by unbracketed** [comment]
Available on staging.
https://aashe-hub-stage.herokuapp.com/_ad/content/
Edit a content item and set its website URL to something more than 200 chars to verify. 

Here's a long URL I made for testing:
https://requestb.in/x8uh7ix8?12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
