### ISSUE TITLE
Some AASHE 2016 conference presentation files seem corrupted and aren't accessible

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#417]
Last week I received a notification from a user about a corrupted presentation file on a 2016 conference presentation in the Hub. I received a similar request today. It seems that some, but not all, conference presentation files are corrupted, with an error message such as this:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>088457F203318371</RequestId>
<HostId>
PMr2Ct6oLvjbBTfUOu81r6cvl6vTWEbqoRRGfl1JDW3xGh2Xs9GWnzLmm5AeK2aIWgOOkSA/LbI=
</HostId>
</Error>

Here are links to a few that I found, but I'm sure there are many more:

- https://hub.aashe.org/browse/presentation/16192/transitioning-dining-hall-pulped-waste-to-post-consumer-compost-challenges-and-lessons-learned-at-appalachian-state-university
- https://hub.aashe.org/browse/presentation/15820/green-funds-how-students-use-their-money-to-build-a-better-campus-and-community
- https://hub.aashe.org/browse/presentation/15822/community-partnerships-for-stormwater-management

I spot-checked and so far it only seems to be happening to AASHE 2016 sessions. Please resolve ASAP.

**Comment by jamstooks** [comment]
There is an existing desk.com ticket right now. We are working with Attendee Interactive to get these remaining files.
