### ISSUE TITLE
"Membership Required" label is confusing people

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#418]
On a HEASC call today, an APPA representative thought that the "Membership Required" label on several APPA resources in the Hub was indicating that the resource was only available to APPA members. Second Nature has also said that their constituents have been confused about the Membership Required label as well. 

To reduce confusion, I'd like to replace the "Membership Required" label with a simple lock icon that when one hovers over it would say "The information page about this resource is accessible only to AASHE members."

**Comment by dodget** [comment]
To make sure I am looking at the correct label, it appears in the resource list (under the resource title) for users who are not logged in?

**Comment by rerb** [comment]
Yeah, the orange box.  Shows when user is not logged in and also when user is logged in but not an AASHE member.

**Comment by dodget** [comment]
@juliandsmith I believe this issue can be closed?

**Comment by juliandsmith** [comment]
Yes, looks great. Thanks!!
