### ISSUE TITLE
Can't upload a photo on the admin side

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#420]
I just tried to add an image of the cover of one of our publications already posted in the Hub but, as you can see in the screenshot, it won't let me do it on the admin side without also entering URLs for the small and medium thumbnail. On the front end, these are created automatically based on the photo you select so I have no idea how to figure out what to put in these fields. It would be a lot better if they could be created automatically as on the front end.

![image](https://cloud.githubusercontent.com/assets/15839046/23611145/c68c5740-0243-11e7-8dcc-4f06718fd8a0.png)

**Comment by rerb** [comment]
I believe this was discussed and the solution agreed on was to upload images through the front end.  Is that a sufficient solution for this ticket?

**Comment by juliandsmith** [comment]
You might be thinking of the conversation about exports where we agreed that it's not necessary to have export functionality on both admin and public sides since staff could just use the public export tool.

However, that same logic doesn't apply in the photo upload situation (which this ticket is about) because it's not possible to access the "front end" again after a photo has been submitted. At a result, we'd still have the problem of not being able to add an image to an already published resouce (unless we resubmit the resource from scratch entirely and delete the original posting, which is super time-consuming).

**Comment by rerb** [comment]
I see.  Thanks for the clarification.


-- 
 

Registration rates 
<http://conference.aashe.org/registration/registration-rates/> for the 2017 
AASHE Conference & Expo, themed "Stronger in Solidarity," are now available 
to help you budget for your participation. Registration opens in the spring.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
Is this particular ticket going to be time-consuming, @rerb ? I will have to go through many of the AASHE publications in the Hub in the next week or so and update their URLs and files before the new site launches so we don't have broken links. It would be great if I can also update the image files then so I don't have to go through them again one-by-one.

**Comment by rerb** [comment]
Haven't investigated in detail yet, so can't give much of a time estimate.  I'll check it out and get back to you.  My gut says it won't take too long and I'll get to it next week.

**Comment by rerb** [comment]
Ha.  Issue [420](https://www.google.com/?q=420#safe=off&q=420).

**Comment by monika-aashe** [comment]
A lot of folks are asking to edit their images for the ones that are coming in. Because of this bug, I can't make any edits, so it would be great to put this near the top of the priorities list. Thanks!
Monika

**Comment by rerb** [comment]
Scott - assigning this one to you since I haven't been able to get to it.  Please consider it along with the other high priority issues when you choose which (and in what order) to address.

**Comment by jamstooks** [comment]
I've fixed this and issued a pull request. @rerb can accept and release and then close this ticket when it's up. @rerb, let me know if that's a good method for QC...

In order to get deployment to work, I had to downgrade the release of the ISS being used... from @master to @2.4. I created [a release](https://github.com/AASHE/iss/releases/tag/v2.4) to match the version bump before the last two commits that broke migrations and added a [related issue](https://github.com/AASHE/iss/issues/16) to the iss.

**Comment by rerb** [comment]
Deployed last night.
