### ISSUE TITLE
Remove Multiview Ad on Curriculum Toolkit

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#421]
Multiview hasn't been able to sell ads on the Hub and is no longer interested in doing so. As a result, we'd like to remove the placeholder ad box currently on the Curriculum toolkit page.

**Comment by monika-aashe** [comment]
The ad on this page has been replaced with one from ASU. Need to check with M&M to see if this is a legit ad that needs to stay. Added "Decision Needed" tag for now.

**Comment by dodget** [comment]
This is now one of two issues with 'medium' priority in 'hub-sprint.' Does this require attention, or can we close it?

**Comment by juliandsmith** [comment]
This does still need to happen. The ad blocks are present on both the [curriculum](https://hub.aashe.org/browse/topics/curriculum/) and [energy](https://hub.aashe.org/browse/topics/energy/) pages and can be removed. The ads we are seeing are all just placeholders - we aren't actually getting any money from them and Multiview doesn't think it can sell those spots.

**Comment by dodget** [comment]
Ok, thanks. I've issued a Pull Request with these changes. I'll wait until the end of the week before deploying, in case we can bundle some changes together.

**Comment by dodget** [comment]
These changes were included in today's deploy.

Closing this issue. Please, reopen if anything appears wrong.
