### ISSUE TITLE
Link check improvement: Add Internal notes to main views

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#423]
Add the internal notes field to the main views (we use this to track status on questionable resources over time, so seeing this up front rather than clicking on the resource each time would be helpful and a big time saver). 

Example: On The [CSINE program](https://hub.aashe.org/_ad/content/centerandinstitute/5041/change/), the internal note says:
10/31/16 - URL no longer works. Alternative seems to be password protected. Check back to see if program still exists.
1/23/17 - still not working

Having this show up in the [main list](https://hub.aashe.org/_ad/linkcheck/) will let us know that it is an old issue.

**Comment by unbracketed** [comment]
Notes will appear like: 

![screenshot 2017-07-25 10 29 09](https://user-images.githubusercontent.com/17127/28585168-3d7cd998-7124-11e7-9842-5754fad45428.png)

**Comment by monika-aashe** [comment]
Looks good to me! Have you looked into the higher prio issue of access to link check not working? https://github.com/AASHE/hub/issues/436
