### ISSUE TITLE
Link Check Improvement: Ignored Links should be removable if they now work

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#424]
It seems that the [Ignored Links page](https://hub.aashe.org/_ad/linkcheck/?filters=ignored) updates periodically, and several of the links that once didn't work are now working. However, there appears to be no way to update the status for those that are now okay (you can only update the status for those that still don't appear to work. 

In addition, it would be good to have a more permanent fix to avoid false negatives (all of these links were marked "ignore" because at one point in time, they showed up under "Bad" but still worked. 

Also, what happens when a link is moved to the "Ignore" list because it is actually working, but over time, that link becomes legitimately bad???

**Comment by unbracketed** [comment]
I have changes in a [branch](https://github.com/AASHE/hub/tree/linkcheck-enhancements) to address allowing good links to be processed:

![screenshot 2017-07-24 17 43 55](https://user-images.githubusercontent.com/17127/28550696-ae5185d4-7097-11e7-9bac-0be357cd6841.png)

There is a job that runs on the site once per day to check all of the external links and will update their status accordingly in the database. This ensures that broken links will be identified.  It also leads to the possibility of some false negatives as you've seen. I've glanced at the code that does the checking and it isn't the most robust networking code If the false negatives are frequent we can replace the link checking code with something more stable.
