### ISSUE TITLE
Remove ElasticSearch Resource from Production Server

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#426]
For whatever reason, we are still connecting to the ElasticSearch service, which I thought we had removed in favor of PG full-text search...

**Comment by rerb** [comment]
Nope - still using ElasticSearch, PostgreSQL full-text search branch was never deployed.  This was an oversight.  The PostgreSQL full-text search branch should be updated, tested, then merged into master.  *Then* remove ElasticSearch from aashe-hub-prod.
