### ISSUE TITLE
"I am an author" auto-population

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#43]
"I am an author" should show up for first author field only. Checking the box would auto populate the author fields for the first author with the individuals name, email, and organization. This is basically a short-cut feature.

**Comment by bartTC** [comment]
This is in. There's a new box 'I am an author' and if checked, the current logged in user is copied as an 'Author'.

At least for now I'm not able to put this checkbox into the 'Author' tab, where it would make more sense, since it's a different form.  But that can be improved.

Also only the `name` and `email` is copied over from the user account to the `Authors` list of the object. I'd need a real `user.aasheuser` to see if there's more related data.

![](http://d.pr/i/1hmYn+)

**Comment by bartTC** [comment]
@monika-aashe please check wording of that field help text

**Comment by monika-aashe** [comment]
Wording is okay, however when I tested this on the dev site, checking the box did not result in my information auto-filling. Is this a bug or a limitation on the feature?

**Comment by monika-aashe** [comment]
Re-opening because "I am an author" does not auto-populate the first author field.

**Comment by bartTC** [comment]
@monika-aashe that's not how it works (right now). If you check it, you get assigned, in the background, you don't need to type your data in.

**Comment by monika-aashe** [comment]
Okay, thanks for clarifying - I'll try submitting a few like this and see if it shows up in the admin. 

It would be optimal for the information to auto-populate right in the form - otherwise I'm afraid folks would type their info in anyway duplicate things on the backend. Is this feature a lot of work or are there performance issues with doing it this way?

**Comment by monika-aashe** [comment]
Tested and works okay. However I'm still concerned that folks will check the box and type their info in, resulting in duplication on the backend. Would it be possible for this to auto-populate directly in the form?

**Comment by jamstooks** [comment]
I have a workable solution for this. Will commit soon.

**Comment by jamstooks** [comment]
I have added an "I am an Author" button that populates an inline form based on information we have for the authenticated user. If that data is incomplete or not up-to-date they can update it. Take a look and let me know what you think.

Example: https://aashe-hub-dev.herokuapp.com/submit-resource/academicprogram/#authors

If you like it, please close this ticket.
