### ISSUE TITLE
Org Type filter is broken.

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#432]
Not sure exactly how or why, but it broke when we turned on the MemberSuite sync.  Might be blocked by django-membersuite-auth [#7](https://github.com/AASHE/django-membersuite-auth/issues/7).

**Comment by rerb** [comment]
Dupe of #840

**Comment by monika-aashe** [comment]
Bob, I'm not seeing a duplicate #820 ticket. I think this needs to stay open as a result?
