### ISSUE TITLE
Hub site formatting broken

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#434]
Not sure if this is due to the website launch issues, but the formatting and design of the entire Hub site is off. 

![screen shot 2017-04-16 at 8 37 58 pm](https://cloud.githubusercontent.com/assets/15214797/25075534/db515d76-22e4-11e7-8a42-fea8dc8541c2.png)

**Comment by monika-aashe** [comment]
FYI, same issue on the admin side.

**Comment by monika-aashe** [comment]
Formatting was sort of fixed, but it is still off. May have Hub team call this week to talk about adjusting the styles back to what we had.

https://hub.aashe.org/browse/publication/12271/Transdisciplinary-research-in-sustainability-science-practice-principles-and-challenges

**Comment by monika-aashe** [comment]
We will need to update the Footer section to once again link to the [Hub flat pages](https://hub.aashe.org/_ad/flatpages/flatpage/), since there is no other link for now.

**Comment by rerb** [comment]
Is this all set now?  CSS wasn't loading when the issue was created; it is now.

**Comment by rerb** [comment]
Meeting scheduled to discuss integration of new site look and feel into Hub.
