### ISSUE TITLE
Summary maps are not displaying

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#437]
Reported by Julian.  I don't know what summary maps are.  Hoping Scott does.

**Comment by juliandsmith** [comment]
These are the maps on many of the content type home pages (like in the second tab at the bottom of  https://hub.aashe.org/browse/types/academicprogram/)

**Comment by rerb** [comment]
Looks like they're showing, but with only 1 pin, when they should have . . . more than 1.

**Comment by baronvonvaderham** [comment]
Yes. There's either a Javascript issue, or there's a data thing where they don't have lat/long data. That data was there (specifically requested) a few weeks ago, but maybe they re-dropped it on the final import.

**Comment by monika-aashe** [comment]
When fixed, make sure Conf. Pres and Publications maps are working (see closed ticket #422

**Comment by unbracketed** [comment]
When I view the Summary Map [here](https://hub.aashe.org/browse/types/academicprogram/) I see many pins showing on the map and the map controls seem to work as expected.

Are there examples elsewhere showing the reported behavior?

**Comment by monika-aashe** [comment]
I believe that the issue now is that only some of the pins show up for the maps. If there are over 1,000 resources from 564 organizations, then there should be at least 564 pins (I believe the pins link to that content type and organization name, rather than each individual resource for an organization that has multiple of the same)

**Comment by monika-aashe** [comment]
This is tied to the ISS database, which @rerb can hopefully point you to.

**Comment by unbracketed** [comment]
Hello from Github  (testing Slack)

**Comment by unbracketed** [comment]
hello again from github!

**Comment by unbracketed** [comment]
Using a recent production database backup, I can see that only 63 rows are being selected into the map data for the example page we're looking at. Our query is (sensibly) dropping any rows for which an Organization has an empty `latitude`, however in the data I can see that only a very small percent of the orgs have a value for `latitude`.

Since almost every organization has a valid street address, one potential solution is to do a one-time geocoding on all the Organization addresses and update the table with the lat, lng coordinates.  Any concerns with this approach?

**Comment by juliandsmith** [comment]
Thanks for looking into this Brian. This issue has come up before and, my understanding is that we do actually have latitude and longitude data for way more than 63 organizations in Membersuite but I guess it isn't coming through for some reason . Here are some notes from a previous conversation that may be helpful:

> It looks like Membersuite has two variables that can store lat/lng data:
> 
> ['Mailing_Address']['GeocodeLat'] or ['Latitude__c']
> 
> I'm not sure how the GeocodeLat data works, but there are a few Orgs who have data there, so I've set our system (ISS) up to check that field first and then check our Latitude__c field (which came over from Salesforce).
> 
> It probably makes sense to figure out how the GeocodeLat data gets populated by MemberSuite, but in the interim, this should work.

That was the last I heard on the issue so I'm guessing that the change that is described was never actually implemented.

**Comment by unbracketed** [comment]
Thanks for the update @juliandsmith.  Is there a regular sync of data between Membersuite and the site database? If so then maybe we can start pulling those in correctly, but at a glance I don't see anything that looks like import code in this codebase. 

I'm guessing that connecting all the dots for the geo coords in Membersuite might be a slow process (or not), but I could still do a one-time geocode on the address data you currently have and use that in the meantime.  It is possible that my geocoding would end up with very slightly different coords for some organizations than what is in Membersuite but that doesn't seem like a problem in my opinion.

**Comment by monika-aashe** [comment]
Decision on Hub team call: 
Make sure lat and long is pulling from latitude__c and longitude__c instead of the Geocode fields.

**Comment by unbracketed** [comment]
Summarizing from weekly tech meeting:

It looks like this all may be an external side effect of two other problems:

* the sync process having been out of operation for some time
* some code updates that hadn't yet been deployed

Once the sync is restored we'll check back on the database and expect to see lat/lng values for the Organizations

**Comment by unbracketed** [comment]
The upstream syncing fixes seem to be working: 
![screenshot 2017-08-01 10 53 49](https://user-images.githubusercontent.com/17127/28839201-b7b7067e-76a7-11e7-877c-dd07f5562123.png)
