### ISSUE TITLE
Set up error and maintenance pages

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#441]
https://devcenter.heroku.com/articles/error-pages#customize-pages

**Comment by rerb** [comment]
We're gonna need some content here.  Header and footer from the site, then just "Sorry, The HUB is down for maintenance." or the error number and pithy explanation?

**Comment by dodget** [comment]
I need to find a way to test this on the staging server, but this issue should be resolved. I'll update when it's fully tested.

**Comment by dodget** [comment]
Unfortunately, this was thoroughly tested in production, today. This issue is resolved.
