### ISSUE TITLE
Partner Panels are empty

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#442]
E.g.:

> On this page (http://www.aashe.org/membership/member-types/businesses/), we reference the Partners Panel and link to https://hub.aashe.org/browse/topics/energy/#partners-panel. There are no Partners listed, but it should include all the partners here: http://partners.aashe.org/?search_terms=&category=Energy&category=&submit=Search

**Comment by baronvonvaderham** [comment]
Fixed, needed to migrate to the new URL patterns since we switched to a subdomain.
