### ISSUE TITLE
Fork aashe-hub-prod into aashe-hub-stage

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#444]
I can't:

```bash
$ heroku fork --from aashe-hub-prod --to aashe-hub-stage
 ▸    Couldn't find that slug.
```

(Rm'ed aashe-hub-stage so it would stop complaining about elasticsearch errors.)

**Comment by baronvonvaderham** [comment]
Submitted a ticket to heroku, this seems to be an error on their side of things.

**Comment by baronvonvaderham** [comment]
https://help.heroku.com/sharing/2eaba1a8-7b60-41f8-849e-0012eb36de5f

**Comment by baronvonvaderham** [comment]
Done.
