### ISSUE TITLE
Organizations Deleted in MemberSuite Should be Deleted in Hub (see "Macalester College duplicate record")

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#450]
Membersuite only shows one record for Macalester College, but there are two records in the Hub.

https://hub.aashe.org/browse/?search=&gallery_view=list&organizations=17149&country=
https://hub.aashe.org/browse/?search=&gallery_view=list&organizations=92293&country=

Are these not syncing properly?

Check on whether second Bowling Green State entry dissapears, since we took it out of Membersuite.

**Comment by monika-aashe** [comment]
There is also a duplicate record for Florida Gulf Coast University, although there only appears to be one record for them in the AMS. 

UPDATE: There are still two Bowling Green State entries in the Hub, indicating that there is a syncing issue, since we removed the duplicate in Membersuite.

**Comment by rerb** [comment]
I suspect the institutions sync doesn't account for institution deletion, which is what happens when 2 MemberSuite orgs are merged.  The institution sync, in fact, usually syncs only institutions that have changed within the last 7 days.  Deleted orgs aren't synced because they're not coming from MemberSuite.  To track deleted orgs, we need to download *all* orgs from MemberSuite, then compare to the list of all institutions, and delete those in list 2 but not list 1.

**Comment by juliandsmith** [comment]
I'm not sure about all of the impacts but the most problematic issue is that both organizations appear as options when submitting a resource associated with that organization and the submitter has no idea which one of the options is the "correct" one. Over time, that means resources may starting getting associated with the "wrong" one, thus adding complexity and confusion.  

The other problems are:

- if an incorrect organization gets added to Membersuite, there's no way to then remove it from the Hub.
- both organizations show up as filtering options, which is confusing for users.

**Comment by rerb** [comment]
Ah.  Definite problems.  Right now the institution data is loaded from MemberSuite every 30 minutes, shortly before the subscription sync runs.  It only loads data from institutions modified in the last 7 days, though, so can't figure which institutions aren't there.  Need to load all institutions to do that, which takes some time, so maybe another job, just to handle deleted institutions, is called for.

**Comment by monika-aashe** [comment]
Discussion from 5/17/17: Figure out a way to merge records in the Hub automatically when they are merged in AMS.

**Comment by monika-aashe** [comment]
Hub team call decision: In the unlikely case that an organization is deleted in the AMS, IF it has resources associated with it in the Hub, set up some kind of alert sent to resources@ email indicating that those resources need to be updated. In the Hub, that organization name will become disassociated, but the resource would stay published.

**Comment by unbracketed** [comment]
I think this should represent the set of duplicate organizations: https://docs.google.com/spreadsheets/d/1efj4Wj4I5NgbYH5C5A-ZaiDKwkNFqzirvJS51fos7N0/edit#gid=1795319890

Fortunately not too many to deal with.  If the merging rules are more complicated than "delete all rows missing `salesforce_id`" then go ahead and edit the spreadsheet down to the desired data.

**Comment by rerb** [comment]
Some of the organizations w/o a salesforce_id might be keepers -- any organization created after our initial migration will have a blank salesforce_id.

**Comment by monika-aashe** [comment]
Possible short-term improvement: Include a "Number of published resources" counter that is displayed on the organization field in the Admin (example: https://hub.aashe.org/_ad/metadata/organization/15172/change/?_changelist_filters=q%3DAllegheny%2BCollege)

**Comment by monika-aashe** [comment]
Hey @unbracketed , just a quick update. I have to reconcile some things with our Membership Team before sending you the updated lists of orgs that can be deleted from the ISS. Maybe tomorrow, but possibly next week.

**Comment by unbracketed** [comment]
@monika-aashe Can you clarify on how the 'merge' should work? I've taken [one example](https://docs.google.com/spreadsheets/d/1efj4Wj4I5NgbYH5C5A-ZaiDKwkNFqzirvJS51fos7N0/edit#gid=1795319890&range=8:9) from the set of dupes where the instructions are to merge `19844` into `16258`.  Could you look at the additional sheet I've added and specify what row `16258` will be after the merge?

**Comment by monika-aashe** [comment]
I don't believe anything needs to be merged. These can just be straight-up deleted. I already moved all of the resources out of those institutions into the correct duplicate orgs, so we just need to delete them. Does that help clarify?

**Comment by unbracketed** [comment]
Yes, thank you

**Comment by unbracketed** [comment]
Reconciliation changes have been applied to the production database. Just prior to applying the changes a database snapshot was made with ID = `b458`

For reference this SQL was applied directly to the database:

```
UPDATE content_author SET organization_id = 16739 WHERE organization_id = 92292;
UPDATE content_author SET organization_id = 16258 WHERE organization_id = 19844;
UPDATE content_author SET organization_id = 17859 WHERE organization_id = 92346;

UPDATE content_contenttype_organizations set organization_id = 16739 WHERE organization_id = 92292;

DELETE FROM iss_organization WHERE account_num IN
      (92362, 92313, 92366, 19844, 92301, 92332, 92302, 92329, 92292, 92338, 92303, 92374, 92293, 92309, 92376, 92346, 92314, 92316, 92379, 92340, 92371, 92330, 92353, 92306, 92317, 92311, 92322, 92295, 92325, 92298, 92334, 92307, 92315, 92345, 92355, 19022, 92357);
```
