### ISSUE TITLE
Immediate fix requested for 3 photograph resources in Hub that can't be approved

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#454]
There is an existing IT support ticket for this. I just want to add it here to make sure we track along with other Hub bugs. See IT ticket with subject line "NYU Earth Day image submission in Hub can't be approved" There is also a related ticket for the overall fix (#420), but getting these three resources working properly may be a separate (easier) task than the overall fix. 

NYU submitted a resource (https://hub.aashe.org/_ad/content/photograph/16832/change/) which I tried to approve per the usual path. For some reason, the issue we identified in Github Ticket #420 made it impossible for me to approve the resource. This is strange, because this issue previously only impacted images that are edited in the Admin, but in this case, I was simply trying to approve the images that were submitted with no editing. FYI, I also tried renaming the image files and resubmitting the resource on their behalf. Still no luck. 

This occurred to two other resources: 
https://hub.aashe.org/_ad/content/photograph/16941/change/
https://hub.aashe.org/_ad/content/photograph/16944/change/

**Comment by jamstooks** [comment]
This issue will be fixed when #420 is fixed, so I'm going to close this.
