### ISSUE TITLE
Counters are broken

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#455]
All of the location based counters on the content type homepages are broken. For example, the [Academic Programs homepage](https://hub.aashe.org/browse/types/academicprogram/) says 0 States are represented in our academic programs database, which is definitely incorrect. I'm guessing that the country counts are off too (for the same reasons the country filters aren't working, #446) , but this is less obvious to users.

**Comment by rerb** [comment]
Looks like Ben's work with the country codes has solved this issue.
