### ISSUE TITLE
Admin URL redirects to ... Admin URL

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#457]
go to hub.aashe.com/_ad and if you're not logged in, it'll get stuck as it apparently tries to forward your request to . . . itself?

**Comment by dodget** [comment]
@rerb - I've been trying this out locally. If you let this run, it will eventually bring you to the admin login page, which accepts AASHE credentials. It takes much longer than the 30 second timeout.

If you try the same sequence on STARS, it redirects to admin login almost immediately. I wonder what the difference is?

**Comment by rerb** [comment]
This is working now.  I.e., it's not broken.
