### ISSUE TITLE
Institution.is_member needs to handle subscriptions with overlapping dates

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#458]
institution.subscription_set.filter(`$today and range`).order_by("-access_level")[0]

**Comment by monika-aashe** [comment]
This could be a mistake in Membersuite. There isn't a good reason to have dates overlap. If you renew a month before your subscription, it should get tacked on to the end, not overlap. Bob will talk to Jessica about this issue to see if there is a mistake in how membership is handled in the AMS.

**Comment by juliandsmith** [comment]
Fixed on membersuite side.
