### ISSUE TITLE
Filter out "exclude from AASHE website" in ISS

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#46]
Relevant to Organization(s) tab: To ensure that only valid institutions and organizations appear in the organization type lists. Need to ensure that entities in Salesforce that have the box checked for "Exclude Account from AASHE Website" are not included in the filter options. 
Examples that need to be removed: "Rex, Emilie", "Testing", "test skyelar", "Sam Test Company", "AASHE Test Campus"

**Comment by monika-aashe** [comment]
There will be some considerable clean-up within Salesforce for AASHE IT or other depts. tied to this milestone.

**Comment by monika-aashe** [comment]
Is there is a way to exclude a country for which there are no resources? (i.e., if nothing in the hub is related to Brazil, if shouldn't appear in the list)

**Comment by jamstooks** [comment]
We need to remove orgs, like "AASHE Test Campus" and others.

- [ ] use the `exclude_from_website` flag

**Comment by jamstooks** [comment]
I think AASHE is listed as exclude. We should probably drop that.

**Comment by monika-aashe** [comment]
Yes, there will be lot's of AASHE resources going into this so whatever you think we should do to ensure that AASHE is included in the list.

**Comment by jamstooks** [comment]
Hey, @rerb. I took care of the first two pieces. When you get a chance, could you look into either consolidating the Country dupes in the iss_sync or providing a report so it can be done in Salesforce?

**Comment by jamstooks** [comment]
@rerb - would you mind setting up a scheduled task to update from the ISS every night too?

**Comment by monika-aashe** [comment]
FYI, it looks like the organization(s) dropdown no longer includes "AASHE", but does include "AASHE test campus" - we should reverse that. For now, I will submit my test resources under Test Campus though.

**Comment by rerb** [comment]
@jamstooks -- jobs to update the ISS scheduled to run daily.

**Comment by rerb** [comment]
@monika-aashe 
> FYI, it looks like the organization(s) dropdown no longer includes "AASHE", but does include "AASHE test campus"

Which "organization(s) dropdown"?  Can you tell me where I can find that?  What I thought you were talking about doesn't seem to include AASHE or AASHE Test Campus.

**Comment by monika-aashe** [comment]
Sure, this is in the filters - see example link and screenshot:
https://aashe-hub-dev.herokuapp.com/browse/topics/curriculum/#resources-panel

<img width="321" alt="screen shot 2016-02-01 at 3 28 01 pm" src="https://cloud.githubusercontent.com/assets/15214797/12730146/69b6bad6-c8f8-11e5-85a3-28aa5e67ac12.png">

**Comment by monika-aashe** [comment]
Whenever I am filling out a submission form and select "I am an author", I get the following: 
<img width="742" alt="screen shot 2016-02-01 at 3 32 39 pm" src="https://cloud.githubusercontent.com/assets/15214797/12730238/0e31e928-c8f9-11e5-983b-706163507bb9.png">

But when I log in under my old AASHE account at Frostburg State, I the organization name autofills correctly: 

<img width="752" alt="screen shot 2016-02-01 at 3 33 58 pm" src="https://cloud.githubusercontent.com/assets/15214797/12730279/404ebab2-c8f9-11e5-83aa-f3fa291e61f8.png">

AASHE staff will be submitting a lot of resources, so it would be good if this would show up.

**Comment by rerb** [comment]
Created new ticket (https://github.com/AASHE/hub/issues/189) to track logically duplicate Countries.

**Comment by rerb** [comment]
Added --include-aashe-in-website flag to ISS upsert_iss_organizations command to force `exclude_from_website` field on iss.Organization representing AASHE to be 'False' (e.i, 0).

Set up scheduled daily upsert_iss_organizations task to use --include-aashe-in-website.

AASHE now shows in Organizations drop down.

https://github.com/AASHE/hub/issues/141 is a separate ticket that addresses the lack of Organization pre-fill for AASHE staff when clicking the "I am an Author" button.

**Comment by monika-aashe** [comment]
FYI, since AASHE can now be selected from the dropdown, we have a workaround. While it would be nice for AASHE to automatically autopopulate when staff are submitting a resource, we can simply add the AASHE in later. I'm fine with delaying this fix until a later milestone.
