### ISSUE TITLE
"Finding Resources" page not showing up in the Hub Footer Anymore

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#464]
It was there once, but I think we lost it when we updated the Footers following the new website changes. 

We'd like to add a link in the Footer titled [Finding Resources](https://hub.aashe.org/finding-resources/), after About and before Submission Guidelines.

**Comment by monika-aashe** [comment]
@rerb - let me know if this should get added to the Contractor list.

**Comment by dodget** [comment]
Submitted a pull request for this issue. Tested across browsers, it was a simple fix.

**Comment by dodget** [comment]
@monika-aashe - I believe this issue can now be closed.
