### ISSUE TITLE
Summary charts break when filters are applied

### ISSUE THREAD

**Issue by unbracketed** [AASHE/hub#467]
When filters are applied in the resource list views for a content type, the bar chart in the Summary panel will often show an error message instead of the chart.  Here is an example after setting a filter in the Academic Program list and then switching to summary view:

![academic-program-chart](https://user-images.githubusercontent.com/17127/30990684-0fd31208-a457-11e7-8ced-85ec815bb31e.png)

https://hub.aashe.org/browse/types/academicprogram/?search=&content_type=academicprogram&country=&program_type=4#summary-panel

My guess is that there is a piece of code that is switching the active view panel(s) based on the URL and it is malfunctioning when filters are present in the URL.

**Comment by monika-aashe** [comment]
Two options:
1. Have charts in Summary Tab recognize the filter selection in the Resources Tab (will need to add some guiding language that certain filters have been applied).
2. Always only display unfiltered results in Summary Tab charts.

**Comment by dodget** [comment]
This is a strange one. From what I can see the data is still there to be displayed, which is good. As you can see in Brian's screenshot, when you navigate back to the 'summary' tab, it is the 'summary map' display that appears active, but the chart's text is showing. That's weird. I should be able to solve this with some simple JavaScript, but it's proving a little challenging.

**Comment by dodget** [comment]
I've come to the realization that this problem is baked into the cake. Solving it well would take a lot of effort for a very small return.

However, I've come up with a hack that will solve it poorly. We can talk about it at our next meeting.

**Comment by dodget** [comment]
The fix has been deployed to the staging site. Everything looks good to me, but feel free to test. I'll probably deploy to production tomorrow.

**Comment by dodget** [comment]
The fix has been deployed to development, and it looks fine. If you see any issues, please reopen this issue. Closing.
