### ISSUE TITLE
Two resources have incorrect post dates causing a bug in the Year Posted filter

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#469]
The dataset for Green Power Projects had two installations where Date Posted was formatted MM/DD/YY instead of MM/DD/YYYY, which resulted in the Year being treated as 0016 instead of 2016. As a result, the Year Posted filter universally includes the earliest years, plus everything in between. I cannot adjust the Year Posted in Admin, so I believe this will need to be fixed by IT to resolve the issue. 

The resources that need to be adjusted:
https://hub.aashe.org/browse/greenpowerproject/17426/539-kW-Rooftop-Array-Res-Rec
https://hub.aashe.org/browse/greenpowerproject/17770/22-kW-Rooftop-Array-Partners-I-Building

It's not clear why all the years after the earliest (0016) are included as options, but if you select one and apply the filter, there are zero resources. Would be good to set the filter up so that only years where resources are applied show up. This appears to be how the filters work under "Year created, published, or presented". 

Also, would be good if both date filters showed up consistent in terms of chronological year (either earliest to latest, or latest to earliest). Right now, the first starts with earliest, but the second starts with most recent.

**Comment by juliandsmith** [comment]
@rerb Do you think you could fix the date posted manually on these two? Monika and I can't change date posted through the regular admin function but I imagine it should only take you a few minutes

**Comment by monika-aashe** [comment]
https://docs.google.com/spreadsheets/d/1X9YYA86om5ndzWBdDo20aUavQxgsmKvePQMtyHcPUoU/edit#gid=1783883752

See row 5, Column AQ for example of formatting issue in EDITS: Solar and Wind Green Power Projects

**Comment by unbracketed** [comment]
I updated the dates for those entries directly via the database. Still working on the year filter, looks like some more rows need attention.

**Comment by unbracketed** [comment]
The `Year Posted` filter looks correct on production now. 

Tech note: I had to restart the web services in order for the filter to be correct.  Not sure where the content is cached for that part of the page, but I had expected it to get flushed out by now.

**Comment by monika-aashe** [comment]
Looks great! The final piece for this particular ticket: Can we order the years for Year Posted and Year created, published, or presented to be consistent in terms of chronology? The former currently displays oldest first, while the latter displays earliest first. 

If this is a relatively quick fix, great. But if it's particularly time-intensive, it may not be worth the trouble. 

Thanks!
