### ISSUE TITLE
Submit a Resource Default emails

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#47]
The email copy can be found here: https://docs.google.com/document/d/1RBJyC8F0yejv6qdx3qtXwDxEK1_4P4JI_ufHrRCivbU/edit

Note that we decided we would like an auto-email for "your resource has been declined", which means that we will have to add a "declined" status under Admin.

**Comment by bartTC** [comment]
The best hookup point for this is the `submit.save` method.

https://github.com/AASHE/hub/blob/master/hub/apps/submit/forms.py#L33-L41

**Comment by rerb** [comment]
@monika-aashe - In the emails that begin "Dear <first-name>," what would you like to do when the user hasn't provided a first name?  (There are lots of existing Drupal users that haven't provided a first name.)  Substitute "Hello!"?

**Comment by monika-aashe** [comment]
I'm fine with updating from "Dear" to "Hello" across the board, but maybe a
comma instead of an exclamation point so we're not implying that we're
excited to let you know that your resource has been declined.

So in other words:

   - Hello Jane,
   - Hello,


On Wed, Dec 16, 2015 at 12:26 PM, Robert Erb <notifications@github.com>
wrote:

> @monika-aashe <https://github.com/monika-aashe> - In the emails that
> begin "Dear 'first-name'," what would you like to do when the user hasn't
> provided a first name? (There are lots of existing Drupal users that
> haven't provided a first name.) Substitute "Hello!"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/47#issuecomment-165183385>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

<http://www.aashe.org>
------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
@rerb - do you know the status on this? I haven't ever gotten any emails to resources@aashe.org, so my guess is this hasn't been implemented yet or we're waiting until it's on the hub.aashe.org server.

**Comment by rerb** [comment]
@monika-aashe this was implemented back in December.  You're not getting any messages because the email environmental variables haven't been set on the server.  I'll enter a new issue for that.

**Comment by monika-aashe** [comment]
Related to #204 and #219
