### ISSUE TITLE
Add feature to Sort Green Power Projects by project size

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#471]
User request - since this was displayed in old Solar PV database

**Comment by dodget** [comment]
@monika-aashe - Project Size already exists as a filter. Would this be some sort of button that would sort the list from largest to smallest, or smallest to largest, rather than newest to oldest?

**Comment by monika-aashe** [comment]
Tylor,
We already have sort built into the Hub (see "Sort by:" right below the filters), but this would be the first instance where a different sort option is included on the Content Type resource listing. It can simply appear as the last sort option. 

I'm also realizing that the way the unique filters currently display (below the Sort by section) may not be optimal, so I may submit a ticket for the Inbox to fix that.

Let me know if you have any additional questions!

**Comment by dodget** [comment]
@monika-aashe - I have this working on a local branch. However, I have some technical concerns that I'd like to review with Bob before I submit a pull request. Would you like the filter to go from largest to smallest, or smallest to largest?
