### ISSUE TITLE
Upload AASHE 2017  Conference Presentations 

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#472]
We are ready to upload the AASHE 2017 Conference presentations to the Hub.  This is a top priority ticket until complete - lets discuss tomorrow at noon. 

[Link to the data ](https://docs.google.com/spreadsheets/d/1Pjg6GIVpmQJi199WiAkKfink_HrcZURHdt6K_XGqS0E/edit#gid=0)

You will also need the link to the [uploaded proposal files](https://files.aievolution.com/ash1701/docs/ash1701_presentations_20171114.zip). Note: This is a very large zip file and may take hours to download. Please check to see that you're able to start the download ahead of time. The file names are already provided in the spreadsheet (see columns BF-BI).

I included the Membersuite IDs for all organizations. There is only one individual that doesn't have an organization associated with them. Hopefully that won't be an issue (organization is required on the submission form).

We went above the limit for number of organizations and authors allowed within the submission form, but hopefully that is not going to be a problem.

**Comment by monika-aashe** [comment]
Forgot to mention: As with all resources, there is a "Date Created, Published or Presented" as well as a "Date Posted" field. For the former, please use what is in the spreadsheet (column W). For Date Posted, you can use the date of the actual import.

**Comment by unbracketed** [comment]
This is be ready for QA.  New presentations can be viewed on the staging site:

https://aashe-hub-stage.herokuapp.com/browse/types/presentation/

One caveat with the data on staging is that the recently added Orgs are not yet in the staging database and so won't be added to those presentation records.   The production database appears to contain all the new Orgs already.

The files are already uploaded onto the production S3 bucket, so it is just a matter of running the import process to create the new presentation records there when we're ready.

**Comment by unbracketed** [comment]
@monika-aashe staging now has my copy of the database with all the current Orgs and the new presentations imported.

**Comment by unbracketed** [comment]
New presentations are now live on the site.  Here is an example with a file attached:  https://hub.aashe.org/browse/presentation/18611/Closing-Keynote-Heather-Hackman-A-Deeper-Solidarity-Sustainability-Through-a-Social-Justice-Lens

**Comment by monika-aashe** [comment]
Looks great! Closing the ticket and updating in project.
