### ISSUE TITLE
Move Unique Filters to be located ABOVE "Sort by" section, but below the standard filters

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#485]
Having the Sort section in the middle of the filters isn't optimal. 

This applies to all content types that have unique filters, which currently includes:
[Green Power Projects](https://hub.aashe.org/browse/types/greenpowerproject/#resources-panel)
[Academic Programs](https://hub.aashe.org/browse/types/academicprogram/#resources-panel)
[Conference Presentations](https://hub.aashe.org/browse/types/presentation/#resources-panel)
[Course Materials](https://hub.aashe.org/browse/types/material/#resources-panel)
[Publications](https://hub.aashe.org/browse/types/publication/#resources-panel)

**Comment by dodget** [comment]
These changes were included in today's deploy. Tackled it today because I thought it would be simple. Turned out more challenging than I thought! Nevertheless, it's done.

Closing this issue. Please, reopen if anything is wrong.
