### ISSUE TITLE
Linkcheck URL field size needs to be extended to handle Website.url

### ISSUE THREAD

**Issue by unbracketed** [AASHE/hub#490]

**Comment by monika-aashe** [comment]
Should this get reassigned to Tylor?

**Comment by unbracketed** [comment]
> Should this get reassigned to Tylor?

Yes. During my research I found this setting which, if used, should resolve the problem: https://github.com/DjangoAdminHackers/django-linkcheck#linkcheck_max_url_length

For some context: a few months ago we made a change in the `Website.url` field to extend the length beyond 255 chars. Linkcheck keeps its own copy of the URL and I noticed errors in the linkcheck processing log because we now have some Website(s) with longer URLs.

**Comment by dodget** [comment]
Environment variable for this setting is set to '500.' That is the correct length of characters. 

Closing this issue. Will reopen if it appears to remain an issue in the linkcheck processing log.
