### ISSUE TITLE
Spelling mistake in green power project pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#494]
As you can see in [this example](https://hub.aashe.org/browse/greenpowerproject/18123/52-MW-Capital-Partners-Solar-Project), the resource detail page for green power projects includes a field label with a misspelling: "Describe the cost savings the **instituion** expects to generate through this project, including how these savings were calculated". 

I assume changing instituion to institution is a quick fix but I can't edit it myself. Note that this mistake doesn't appear on the submission form, only the field label on the resource detail page.

**Comment by dodget** [comment]
I will roll this into my next pull request.
