### ISSUE TITLE
Project Size field on Green Power Projects submission form should only allow numeric response

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#502]
We currently have a filter for Green Power Projects based on size categories. The field should only allow for numeric responses (no commas, decimals okay). However, based on a [recent submission](https://hub.aashe.org/_ad/content/greenpowerproject/18787/change/) from another user, it appears that text data is also accepted. Not sure how this will impact the filter and whether it will cause issues, so I'm holding off on approving for now.

**Comment by dodget** [comment]
Yeah, when I was working on GPP project size filters I saw that the database field is defined as text. I don't know why it was defined that way. I imagine it was because there wasn't agreement on units (mwh vs kwh). This is not ideal, and we should look into updating.

**Comment by monika-aashe** [comment]
It should be in kilowatts, not kwh. There is an optional kwh field that I suppose should also require numeric responses only.

**Comment by dodget** [comment]
Regardless of the unit designation, the field was defined as text. That makes the values difficult to work with, and allows potential invalid inputs, as we see here. There are two possible routes as I see it:

First route, change the database field to a 'float.' This would require going over all previous entires and casting the values from text to float. This would be the more difficult, but more accurate path moving forward.

Second route, Manipulate form input validation to only accept float like inputs. This would be a front-end change only. It would be the simpler path, but leaves a potentially inaccurate data type on the back end.

**Comment by unbracketed** [comment]
That was probably me.  If I remember correctly I may have made a few fields into text fields that should have been other types mainly because the form abstraction rendering for the base content types wasn't rendering those fields in manner consistent with how the other fields were working.  If you end up changing the field types (the best technical solution), you may need to set aside some time to update the base form and widgets as appropriate.  I went briefly down that path but it looked it was going to be out of scope with the budget I had available.

**Comment by juliandsmith** [comment]
I would support reformatting all existing data in this field as a number and requiring it going forward via the submission form. This particular submission can just be split in two - one submission for the wind turbine and another for the solar system.

**Comment by dodget** [comment]
I've successfully migrated and reformatted the data locally. I will now be turning to all front end aspects to update accordingly.

Note - we will need to resolve the 'project size' of GPP resource "Powerhouse Vertical Axis Wind Turbines and Solar Array" before I can migrate the data in production. No rush on this.

**Comment by dodget** [comment]
Data migration and change of field type has been deployed to the [staging site](https://aashe-hub-stage.herokuapp.com/). There were no issues.

Please, feel free to test filters, resource submission, or any front end aspects. Once I have the go-ahead, deploying to production should not be an issue.

**Comment by dodget** [comment]
The migration has been applied, and everything looks good! I did it off-hours in case there were any issues, but there appears to be none. I'll leave this open until the end of the week in the event that we find anything wrong.

**Comment by dodget** [comment]
Closing, for now.
