### ISSUE TITLE
Bug - Long tags break

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#503]
Filters for long tags don't seem work. For example, [this resource](https://hub.aashe.org/browse/publication/16948/Assessment-of-undergraduate-students-environmental-stewardship-reasoning-and-knowledge) is tagged with "Environmental Stewardship Reasoning and Knowledge Assessment (ESRKA)". If you click [the link](https://hub.aashe.org/browse/?tagfilter=environmental-stewardship-reasoning-and-knowledge-) to view all resources with this tag, you get zero results (there should be 3). Similarly formatted tags, e.g. [New Ecological Paradigm (NEP)](https://hub.aashe.org/browse/?search=&gallery_view=list&tagfilter=new-ecological-paradigm-nep&country=) and [Assessment of Sustainability Knowledge (ASK)](https://hub.aashe.org/browse/?tagfilter=assessment-of-sustainability-knowledge-ask), seem to work so I assume length is the issue.

I know it is long, but I'd like to keep this tag as is if possible since it refers to the name of a particular tool. Is there a way to get this work?

**Comment by dodget** [comment]
I am not able to reproduce this bug. When I click the "Environmental Stewardship Reasoning and Knowledge Assessment (ESRKA)" tag on that resource detail page, the results give me three resources, not zero. I tested it in both chrome, and firefox. 

Do you still experience the same behavior that you describe? I can try to track down the Heroku error logs from 2/26 if we need to dig further.

**Comment by juliandsmith** [comment]
That's so weird! It totally works now. I wonder if it was just some kind of caching thing (it was a brand new tag).  Oh well, closing for now.
