### ISSUE TITLE
Longer search queries result in access denied message!

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#508]
Hi all,

The changes we just implemented to search seem to be causing some problems with longer queries. For example, [this search](https://hub.aashe.org/browse/?search=Institute+of+Environment+Sustainable+Development) results in this message: "AccessDeniedAccess DeniedF8A2B09A36E0C23CeM0EfupqpWYkreLD6JVwWxjBl9ov0fTIKzjLe9JzZYLgpE3GmP+cp9PyxIh4HGBjkU0FRLd3esk="

I did some testing. It seems that one word searches work as normal but each additional word seems to slow things down significantly, to the point that searches of more than 4 words seem to time out and generate an access denied error like the one above. I don't think this is an acceptable tradeoff. Can we rollback and try to reconfigure to get around this problem?

Thanks!

Julian

**Comment by dodget** [comment]
Changes to search functionality have been deployed to production. It seems to be working well, with no errors.
