### ISSUE TITLE
Add rate limiting around login POST and API calls

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#51]
We should add rate limiting around certain elements on the site:

- [x] Login Form
- [x] Search Form
- [x] Filtering in General?
- [x] Every API call

**Comment by monika-aashe** [comment]
@jamstooks - making this a 1c milestone but feel free to change.

**Comment by jamstooks** [comment]
[Django-ratelimit](http://django-ratelimit.readthedocs.org/en/latest/) looks promising.
