### ISSUE TITLE
Add "Date Posted" to Case Studies list in Admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#521]
All of the other Content types admin pages have Date Posted. When approving large amounts of resources, it's hard to tell which were already approved unless this is listed. It would help if a "Date Posted" column was added to the Case Studies Page.

[Case Studies list in Admin](https://hub.aashe.org/_ad/content/casestudy/)
[Example that includes "Date Posted"](https://hub.aashe.org/_ad/content/publication/)

**Comment by monika-aashe** [comment]
Low priority until next year's Awards deadline (2019).

**Comment by dodget** [comment]
Ready to go for this week's deploy.

**Comment by dodget** [comment]
This has been deployed. Closing.
