### ISSUE TITLE
Add confirmation email for successfully submitted resources

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#525]
From Julian:
Currently, submitters get a confirmation email when/if their submission is approved. Approval of submissions typically doesn't happen immediately, which means folks sometimes get concerned that we didn't get the submission and then call or email us to make sure we received their submission. This is particularly an issue around the awards deadline since people want to make sure we received their submission prior to the deadline. I'd like to set it up so that folks get an immediate confirmation that their submission has been received and then get a second message when/if their submission is approved.

From Crystal:
Each year, the most frequent email I get about the awards is, "Can you confirm that my application/submission was received?" So if this could be added, that would be fantastic! 

A Confirmation Email is already set up, but currently only goes to resources@aashe.org. We may have to tweak the language slightly since it will no longer be internal only. 

Email Subject: Resource Submitted for Review

Body: 
A new resource has been submitted and is ready for review:

- Resource title: There is No Such Thing as Free Higher Education: A Global Perspective on the (Many) Realities of Free Systems
- Content type: Publications
- Submitted by:
- Name: Crystal Simmons
- Email: crystal.simmons@aashe.org
- Date and time submitted: May 21, 2018, 9:02 p.m.

This resource can be moderated at the following link:

https://hub.aashe.org/_ad/content/publication/19701/change/

Please review and decide within 2 business days. Happy moderating!

**Comment by monika-aashe** [comment]
Email edits:

Instead of 
"This resource can be moderated at the following link:
https://hub.aashe.org/_ad/content/publication/19701/change/
Please review and decide within 2 business days. Happy moderating!

Lets say:
"This resources is currently in moderation and will be reviewed by the AASHE Resources team within 1-3 business days. Stay tuned for further confirmation!"

**Comment by dodget** [comment]
Ok, these changes are ready, and have passed all tests. It will be in cue for next week's deploy.

**Comment by dodget** [comment]
This has been deployed. Closing now. Please, reopen if there are any issues.
