### ISSUE TITLE
Remove Date Created field from case study view pages

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#530]
Case studies view pages show both a "Date Created" and "Date Posted" field that for case studies are always identical. To reduce redundancy, we should hide the Date created field from case study pages.

Note that for other content types, these fields often differ - date created is when an article or tool was published/released (separate from the Hub) while date posted is the time the page about the article or tool actually appeared in the Hub.  It's only because case studies are unique to the Hub that the date created field has no additional value. Please don't hide date created on any other content types.

**Comment by dodget** [comment]
Done. Closing.
