### ISSUE TITLE
Some institutions not showing up correctly in Filters

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#531]
From Crystal:
This [case study](https://hub.aashe.org/browse/casestudy/19534/Progress-toward-90-waste-diversion-goal) from Olds and Bow College doesn't show up in a Hub search using the filters "case study" for content type, and "associate" for Institution type. But both of these institutions are listed as Associate schools in the Hub. [Another example](https://hub.aashe.org/browse/casestudy/19665/The-Nova-Scotia-Community-Colleges-NSCC-Waste-Management-Improvement-Project) is this case study from Nova Scotia Community College. 

From Monika:
I checked all three institutions and they are correctly labeled "Associate" in the AMS as well as the ISS. I also was able to recreate the issue that Crystal referenced. I haven't done more widespread testing to see if other institutions are impacted.

**Comment by dodget** [comment]
Wow, nice find! I was able to correct the issue locally, and I should have the fix deployed this week.

It appears to simply be an error in the filtering logic.

**Comment by dodget** [comment]
Fix passes all tests, and behaves as expected on the staging server. Will be merged tomorrow.

**Comment by dodget** [comment]
Deployed to production. Passing all tests, and returns expected results. Closing now.

Please, reopen if there are any issues.
