### ISSUE TITLE
Bug with Institution Type filter for all Doctoral/Research Institutions

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#539]
All, one of our users pointed out an issue with how University of South Dakota was displaying in the Hub filtered views. Upon further research, it appears to be tied with the Institution Type filter for Doctoral/Research Institutions. 

As you can see from the filtered view of [All resources from Doctoral/Research institutions](https://hub.aashe.org/browse/?search=&gallery_view=list&institution_types=Doctorate&country), zero resources come up (there should be 1,000 or more). 

Please let me know if this is something that can be fixed soonish. Also, I seem to recall a [similar bug](https://github.com/AASHE/hub/issues/531) a few months back so I linked it here in case it's related. 

Thanks in advance!

**Comment by dodget** [comment]
Thanks, Monika!

I have a hunch of what is happening, especially because it seems that the bug is isolated to Doctoral/Research schools. I'll try to get it fixed asap.

**Comment by dodget** [comment]
Fix working on staging site, and passing all tests. Moving to production.

**Comment by dodget** [comment]
@monika-aashe - It looks like this is fixed. I'm closing now, but if you see any issues, please reopen!

**Comment by monika-aashe** [comment]
Yes! Thanks for fixing in record time! I'm sure Meghann from University of South Dakota will be happy we were able to prioritize fixing the issue she helped identify.
