### ISSUE TITLE
add standard AASHE navigation to Hub header

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#54]
At the top left-hand corner of every page in the Hub, we need to add the following: 
aashe  |  stars  |  conference  |  bulletin  |  hub

Each of these would be linked to that particular section of the website. This should be consistent across all AASHE websites - See the [AASHE homepage](http://www.aashe.org).

**Comment by monika-aashe** [comment]
We also need to ensure that the "Submit a Resource" button is on every page in the Hub, so making this standard in the header would be good.

**Comment by monika-aashe** [comment]
See what Review Team says about the logo in the heading.

**Comment by jamstooks** [comment]
While you're at it, Bob, could you look at the [bulletin](http://bulletin.aashe.org/) header? I think the font is a bit bigger there than the [home page](http://www.aashe.org/). It'd be awesome if we could match the styles exactly...

**Comment by rerb** [comment]
@monika-aashe back in November you commented, 

>See what Review Team says about the logo in the heading.

Where might I go to see what the Review Team said?

**Comment by monika-aashe** [comment]
The two comments from the Review team were:
- When clicking on the aashe logo from the CSH site, it should direct to aashe.org. Currently it goes to the CSH site.
- Make aashe logo bigger

All review team comments can be found here: https://docs.google.com/spreadsheets/d/11FcK2NO2F799a9NWlOiQ3ccZVWEf-0VBVItxjlWW9nQ/edit#gid=81264102

**Comment by rerb** [comment]
Clicking on AASHE logo leads to www.aashe.org.

As far as I know, we don't have a clearer, bigger logo.  The image on the hub is the same one that's been on www.aashe.org for a long time.

Since this ticket is titled, "add standard AASHE navigation to Hub header" and that's done, I'll open a new ticket expressing the need for a bigger logo.
