### ISSUE TITLE
Ordering of Featured Resources doesn't work

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#540]
related to closed #64 , a feature that was added but is not currently working.

The ability to sort a resource so it shows up in a precise order is not functioning. 
 
On the [Coordination & Planning Toolkit page](https://hub.aashe.org/browse/topics/coordination-planning/), we want to highlight the 2017 Staffing Survey as the top featured resource. 

However, updating the Order on the [Admin page](https://hub.aashe.org/_ad/metadata/sustainabilitytopic/18/change/) does not change the order. I even tried deleting the existing rows and adding new ones in the order that we wanted, and they still reordered on the live site.

**Comment by dodget** [comment]
Fixed locally. Will go out in next deploy.

**Comment by dodget** [comment]
Deployed to production, closing.
