### ISSUE TITLE
Resource PDF upload includes XML file error

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#548]
The [Energy STAR - STARS resource](https://hub.aashe.org/browse/tool/20828/AASHE-STARS-Credits-through-ENERGY-STAR-r) was approved, but the uploaded PDF results in an XML file error. I tried downloading the PDF from t[heir site](https://www.energystar.gov/buildings/tools-and-resources/aashe_stars_credits_through_energy_star%C2%AE) myself and uploading in the Admin, but the same error resulted.

**Comment by dodget** [comment]
Thanks, Monika.

I just looked into this, and it appears that the `+` in the pdf file name is messing things up.

It seems to me that AWS is changing the `+` to `%2B` when the file is uploaded, but the link we provide keeps the `+` in place. You can see the successfully uploaded file:

https://hub-media.aashe.org/uploads/AASHE_STARS%2BENERGYSTAR_FINAL.pdf

I'd bet AWS is doing this for security purposes. I should be able to fix this no sweat. I'll try to get to it this afternoon.

**Comment by monika-aashe** [comment]
Thanks Tylor!

**Comment by dodget** [comment]
Ok, this is now resolved. I've seen a number of issues come up with file uploads. I think it is worth investigating. This issue is resolved, however, so I'll close.
