### ISSUE TITLE
Updates to installation doc

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#55]
Pillow 3.0.0 pre-requisites: zlib and jpeg libs required now, else `pip install -r requirements.txt` will fail

https://pillow.readthedocs.org/en/3.0.0/installation.html#os-x-installation
https://pillow.readthedocs.org/en/3.0.0/installation.html#linux-installation

**Comment by rerb** [comment]
Also, on OS X, requires (latest?) Xcode command line tools, installed via `xcode-select --install`

**Comment by rerb** [comment]
List required environment vars (e.g., AASHE_DRUPAL_URI)

**Comment by rerb** [comment]
Note requirement that elasticsearch be installed

**Comment by jamstooks** [comment]
I agree that documenting the required environment variables is a good idea. I don't think we need to indicate the requirements for Pillow, OSX and elasticsearch in the main readme. I could see a server-specific readme that indicates what packages should be installed on the server and elasticsearch should be available.

**Comment by monika-aashe** [comment]
@jamstooks and @rerb - I'm making this a 1c milestone but feel free to change as needed - it's all greek to me!
