### ISSUE TITLE
Another resource with XML download error

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#551]
A Hub User emailed us to let us know that the uploaded files under the resource titled, [Example RFP and Scorecard for Procurement/Advisory Services for Large Scale Renewable Energy](https://hub.aashe.org/browse/tool/18929/Example-RFP-and-Scorecard-for-Procurement-Advisory-Services-for-Large-Scale-Renewable-Energy) can't be accessed. I experienced the same issue on my end, the result being an XML error. For some reason, the file can be downloaded on the Admin side.

**Comment by monika-aashe** [comment]
Weird, a second user pointed out the same issue.

**Comment by dodget** [comment]
Thanks, Monika. On it. I'll ping you when it's resolved.

**Comment by dodget** [comment]
@monika-aashe - I just deployed a fix to resolve the issue. Thanks!

**Comment by monika-aashe** [comment]
Thank you Tylor!

**Comment by monika-aashe** [comment]
Tylor,
Here is another XML error issue! See upload to Survey Questions:
https://hub.aashe.org/browse/publication/17291/2017-Higher-Education-Sustainability-Staffing-Survey

**Comment by dodget** [comment]
Thanks Monika. I've resolved the issue. I'll need to do more research into how AWS escapes special characters, and how uploading was implemented in the Hub.
