### ISSUE TITLE
New Campus Green Funds Content Type ready to launch

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#553]
Note: Not a high priority to complete before launch of STARS Benchmarking Tool and new website!!!

The new **Campus Green Funds** content type is ready to add to the Hub. Please include a link to it under the [Content Types landing page](https://hub.aashe.org/#contenttypes-panel) (list in alpha order). 

[Submission Form Details](https://docs.google.com/spreadsheets/d/1LgYSPMCnwgUUOHKc4wDdUYxn5_RLbWBgBznHGymubtk/edit#gid=2108724385)
This sheet outlines the following:
- Fields to include on the Submission form in the order we would like them to appear;
- Whether fields are standard (asked elsewhere in Hub and in common filters), versus unique fields for this content type only; 
- Any relevant helptext;
- Whether fields should be Required or Optional;
- Defaults (form should always list "Investment & Finance" as one of Sustainability Topics, and should always include "green funds" as a tag.
- Filter and Sort - Detail on which unique fields should be added to the Content Type Resource Listing

[Data for Import](https://docs.google.com/spreadsheets/d/1LgYSPMCnwgUUOHKc4wDdUYxn5_RLbWBgBznHGymubtk/edit#gid=2100532977)
You can disregard the columns for Record ID and Status; the rest should align with the info we ask in the form.

[Summary Page](https://docs.google.com/spreadsheets/d/1LgYSPMCnwgUUOHKc4wDdUYxn5_RLbWBgBznHGymubtk/edit#gid=981672190)
Note that we do NOT need to add any Summary Charts at this time, but would like to include the Summary map.

Any questions, please let me know!

**Comment by monika-aashe** [comment]
Tylor,
It means the latter. It’s a new field type for just this content type, whereas we have several fields (e.g. title, description, academic discipline, etc.) that apply to multiple content types in the Hub. Hope that helps.
Sent from my iPhone

> On Jan 3, 2019, at 8:25 AM, Tylor Dodge <notifications@github.com> wrote:
> 
> @monika-aashe - I am starting to review all of this. I have one question so far regarding the submission form sheet.
> 
> I see in the type of field column, several are denoted as UNIQUE. When I hear that a field should be unique, it means that a resource's value for that field should never be repeated in the database. It is typically used for primary keys, and IDs of different sorts. That doesn't seem to be right for fields like Primary funding source(s). Or does the UNIQUE in this case mean that this field is unique to the Green Funds content type?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 










Share ideas, ask questions, and network with your peers in AASHE 
Connect <http://community.aashe.org>, your new online community!

Connect 
with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

**Comment by dodget** [comment]
@monika-aashe - A lot of progress today. I'm nearing the data upload stage, locally. One question:

For student fee, and annual budget, do we care about cents, or can I keep it whole dollar amounts? It looks nicer that way.

**Comment by monika-aashe** [comment]
Whole dollars works for me!

**Comment by dodget** [comment]
If the user attempts to enter cents, it asks the user to revise their entry.

**Comment by dodget** [comment]
@monika-aashe - One more question.

It is much easier for me to include a graph on the summary page, than it is to remove it. I spun up a graph of the resources based on their Primary Funding Source types. Is that ok? It's kind of cool from my perspective.

**Comment by monika-aashe** [comment]
I think that's fine, especially if it's easier to include a graph!

**Comment by dodget** [comment]
@monika-aashe - Sorry for all the questions, but I believe this is the last one.

I'm onto creating the custom filters, and everything is pretty straight forward except for Student Fee, and Annual Budget. 

Sorting on those fields is easy, but questions arise around filtering. As far as I see it, there are two options:

1. I detect the min and max of those fields dynamically (by values in the database), and set up four or five ranges in between the min and max to filter on.

2. You give me ranges to hard-code in to filter on (just like the Green Power Projects "Project Size" filter).

The question is, which one would you prefer?

**Comment by monika-aashe** [comment]
Great question! I should have been more specific on the ranges - that's totally my fault! 
Here is a [new tab](https://docs.google.com/spreadsheets/d/1LgYSPMCnwgUUOHKc4wDdUYxn5_RLbWBgBznHGymubtk/edit#gid=289026701) in the main Google sheet that provides the ranges I recommend.

**Comment by dodget** [comment]
Looks perfect. Thanks!

**Comment by dodget** [comment]
All filters added and working. I'll be moving on to the data upload script tomorrow. If all goes well, there should be a finished product to review on the dev server tomorrow afternoon.

**Comment by dodget** [comment]
@monika-aashe - I'm onto the data upload, and it's going smooth. There is one snag, however.

The `Primary Funding Source` field is listed as required, but some rows in the spreadsheet are blank for that value, which throws off the import. See cell J:24 for example.

Would you like me to encode those blank funding sources as `Other` or would you like me to wait for the data to be filled in?

**Comment by dodget** [comment]
I went ahead assuming blank funding sources should be `Other` for now. I can always update the script before it's run in production.

I deployed my work to the staging server (https://aashe-hub-stage.herokuapp.com/) and ran the upload script. Looks fairly well buttoned up to me :)

I know you must be busy getting ready for the bootcamp, but after you have a chance to check everything out, please let me know. Then I can deploy to the production server!

**Comment by monika-aashe** [comment]
Sorry for the delay, Tylor! 
Looking really good so far! - a few things that come up:
- Some content is missing on the Resource detail pages for unique fields - for example, [Student Sustainability Committee Fund](https://aashe-hub-stage.herokuapp.com/browse/greenfund/20564/Student-Sustainability-Committee-Fund) (row 80 in data file) doesn't display Typical Annual Fee per Student (US Dollars) and Approximate Annual Budget (US Dollars), even though those fields are filled out. I haven't run across any resource that includes this info. If this info isn't blank, it should show up under the Resource detail (before or after Primary Funding Source and Revolving Fund)
- Sort - I don't think the Sort By...Student Fee and ...Annual Budget are working correctly (may be related to above issue). When I sort by Annual Budget, the first item listed is [TRU Sustainability Grant Fund](https://aashe-hub-stage.herokuapp.com/browse/greenfund/20536/TRU-Sustainability-Grant-Fund). However, they don't have the highest annual budget (it should be [Students Green Fund (Inactive)](https://aashe-hub-stage.herokuapp.com/browse/greenfund/20566/Students-Green-Fund-Inactive), which is much further down on the list.  Similarly, sorting by Student Fee brings up [Earth Keepers Mini Grants](https://aashe-hub-stage.herokuapp.com/browse/greenfund/20486/Earthkeepers-Mini-Grants), which is the first item in the spreadsheet, but their student fee is only a dollar, so there are several that have higher fees.  



- The filters for Typical Annual Fee per Student and Approximate Annual Budget always generate zero results for me - both with a single selection and with multiple (ideally, multiple selections would pull any of the choices). 
- There is one resources from an institution in the UK. Any idea why it shows up as the third "country" on the summary page, but doesn't show up in the map as a pin? 
- Under Primary Funding Source(s), it looks like the list is alphabetized, so Other pops up in the middle on the Submission Form and Filters. Would it be possible to list it last?

**Comment by dodget** [comment]
Thanks Monika. It looks like the majority of the issues you listed were due to a partially failed import. I've fixed it, and have the changes on the staging site. Sorry for wasting your time!

To Sum up:
    I've update the sort label for Student Fee and Annual Budget to include "(Largest)."

    Sorting and filtering issues resolved.

    To put "Other" at the bottom of the Primary Funding Source(s) choices, I had to hard-code the choices in. That means if there is ever an additional choice added, it will also need to be added to the filter. It's easy.

    When a pin doesn't show on the map, it's because the organization is missing Lat and Lon data in the ISS. You can see that [here](https://aashe-hub-stage.herokuapp.com/_ad/iss/organization/91210/change/?_changelist_filters=q%3DNational%2BUnion).  

Let me know if you think this is ready to rip! Thanks.

**Comment by monika-aashe** [comment]
Thanks Tylor! Everything I marked as an issue is now fixed - and thanks for updating the ordering for "Other". 
Thanks for letting me know about ISS data not showing up. That is tied to another Github issue, #534 , which is for another day. 
I'm happy with how this has come together. Good to go with deploying when you are ready!

**Comment by dodget** [comment]
Ok, I'll deploy it tonight and update this ticket once it's done.

**Comment by dodget** [comment]
Deployed. Thanks to you Monika and everyone who worked on it for another simple project! Closing now, please re-open if you see an issue.

**Comment by monika-aashe** [comment]
Thanks Tylor for all of your work on this! All looks great. I will inform the M&M team that we can start announcing the new resource.
