### ISSUE TITLE
Hub search doesn't seem to be indexing new resources

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#559]
I noticed today that several resources that I approved last Friday still aren't showing up in Hub search results. For example, [this resource](https://hub.aashe.org/browse/publication/21385/Self-operated-vs-corporate-contract-A-study-of-food-procurement-at-two-universities-in-Manitoba) is live, but it doesn't appear in the [search results for Manitoba](https://hub.aashe.org/browse/?search=Manitoba).

This issue seems to go back at least a couple of weeks since [this article](https://hub.aashe.org/browse/publication/21368/Seeking-sustainability-competence-and-capability-in-the-ESD-and-HESD-literature-an-international-philosophical-hermeneutic-analysis) approved at the end of February, doesn't appear in [search results for hermeneutic](https://hub.aashe.org/browse/?search=hermeneutic). 

Interestingly, both of these examples do appear in the browse all view, suggesting that it may be an issue of just certain fields not getting indexed.

**Comment by juliandsmith** [comment]
@rerb @dodget Just bumping this back into your inbox. The issue is still present and it's a pretty serious limitation to the effectiveness of search.

**Comment by juliandsmith** [comment]
Hey guys. This bug is continuing to present a challenge for finding things in the Hub. Any chance someone could look into this sometime this week?

**Comment by dodget** [comment]
I have some open time today, so I'll dig into it.

**Comment by dodget** [comment]
Ok, index rebuilt and the search function appears to be behaving properly. If this continues to be an issue, I will investigate further. Closing.
