### ISSUE TITLE
Organization name field in admin - change from numerical to text

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#56]
Organization name doesn't show up once selected, only 5-digit code. Need to have org name show up when selected to avoid confusion when moderating.

Example:
http://aashe-hub-dev.herokuapp.com/admin/content/casestudy/4/

**Comment by monika-aashe** [comment]
This is also showing up on the Author Organization section. Here is an example with both issues: http://aashe-hub-dev.herokuapp.com/admin/content/material/16/

**Comment by monika-aashe** [comment]
"Submitted by" also shows up with submitter id only. Would be useful to list both name and id.

**Comment by jamstooks** [comment]
@bartTC - do you have any suggestions about this? I've messed with a few options, but I'm thinking this shortcut might need to be expanded to define each content type:

        for _, model in CONTENT_TYPES.items():
            admin.site.register(model, BaseContentTypeAdmin)

Here's what I've tried so far:

http://django-ajax-selects.readthedocs.org/en/latest/
http://django-autocomplete-light.readthedocs.org/
https://djangosnippets.org/snippets/2108/

Did you have anything else in mind here? ...before I go building admin forms for each content type.

Thanks!

**Comment by bartTC** [comment]
Two options. 

- Use the widget we use on the frontend. We have everything in place, the widget, the API. It will be exactly the same experience. 

- For a quick solution use [salmonella](https://django-salmonella.readthedocs.org/en/latest/). You'd still see the PK in the field, but the real name aside where you can also delete it. 

For the actual integration, I think you can put the overrides into the BaseAdmin class and don't need to define each Form separately. See https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides
