### ISSUE TITLE
Change submitter on this resource

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#561]
The Submitter for [this resource](https://hub.aashe.org/_ad/content/casestudy/21755/change/) has to be updated. The new submitter should be Christie Nairn, christie.nairn@umanitoba.ca

Crystal needs this edit soon for Awards judging and communications. Note that we have a ticket request to allow us to edit submitter info in the admin - #545. 

Let me know if you have any questions.

**Comment by dodget** [comment]
Has Christie ever logged in to the Hub? I am attempting to locate a User record for them so I can set the `submitted_by` value for this resource, but they do not appear to be a Hub User. I believe they could become a Hub User, simply by logging in once.

Until they become a User in the Hub, I cannot set them as the submitter.

**Comment by monika-aashe** [comment]
That's strange. The user says she logged into the Hub under the sustainability@umanitoba.ca email. Do you have that account on record, @dodget ? I can't find it in Membersuite.

**Comment by dodget** [comment]
Hm, no I don't see a User record with that email in the Hub.

**Comment by monika-aashe** [comment]
Weird things are happening!
I will submit a separate ticket about some weird syncing issues.

**Comment by monika-aashe** [comment]
Resolved - closing
