### ISSUE TITLE
Syncing issue with individual accounts in Membersuite and Hub

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#562]
A user created their AASHE account under one email, then decided they wanted to update that email address to a new email in the AMS. They submitted a resource on May 13, and now, that resource is associated with the original email address that they do not wish to use. I'm not 100% sure if the email address was updated in Membersuite before or after the resource was submitted, but based on the breadcrumb trail in the AMS, it appears to have happened on April 25, which is well before the resource was submitted. Is it possible that there is a syncing issue? 

We would like the email address for [this resource](https://hub.aashe.org/_ad/content/casestudy/21759/change/) to be updated to ilieberm@u.rochester.edu, which is what the AMS currently shows as the primary email. 

Thank you!

**Comment by dodget** [comment]
From my understanding, there is no "syncing" process involved. Has the user logged out of the Hub and logged back in since the update in the AMS? If not, I would recommend they try it. They may still be logged in to a session that is using the `acabal@` email address.

**Comment by monika-aashe** [comment]
That makes sense, thanks Tylor. Will recommend logging out and back in.

**Comment by monika-aashe** [comment]
Resolved. Closing
