### ISSUE TITLE
Latest News (Bulletin) feed

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#57]
Three issues:
1. Rename section: "Latest News" -> "Latest News from AASHE Bulletin" and link "AASHE Bulletin" to http://bulletin.aashe.org/
2. The Bulletin feed is currently only showing up under "Curriculum". It should show up under every topic.
3. Need to show only the 5 most recent Bulletin stories by default.

**Comment by monika-aashe** [comment]
Show only 5 per list

**Comment by jamstooks** [comment]
Will rename in the bulletin where possible. Julian will talk with Crystal about consistent naming.

**Comment by monika-aashe** [comment]
Removed the following info and created a new ticket #119 
3. The stories within the feed should align with the sustainability topics. See list here: https://docs.google.com/spreadsheets/d/11FcK2NO2F799a9NWlOiQ3ccZVWEf-0VBVItxjlWW9nQ/edit#gid=1580012357 

Decision on alignment of Bulletin Categories with Hub Topics:
Alignment will mirror perfectly for all except the following: 
Dining Services -> Food & Dining
Coordination Planning & Governance -> Coordination & Planning
Assessments & Ratings -> Coordination & Planning
Funding -> Investment
Campus Sustainability in the Media -> Coordination & Planning
Policy & Legislation -> Public Engagement
