### ISSUE TITLE
AASHE 2019 Conference Presentations Upload

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#576]
We are ready for the upload! All info provided below. 

Link to the [data file](https://docs.google.com/spreadsheets/d/1gPCfqrsLHe4zgKkr5gpyiYh6lwDVSm7Z6dMDyuggQv8/edit#gid=630492119)
Make sure you are on the "Upload Data" tab.

Link to zipped folders with files - According to AI, the links should be available until middle of December:
ppt files: https://files.aievolution.com/ash1901/docs/presentations.zip
pdf files: https://files.aievolution.com/ash1901/docs/pdfs.zip

A few notes:

See last few columns of "UPLOAD DATA" to see which files go with which presentation. There are more files in the zipped folder than what we wish to upload (many users uploaded duplicate files, which we parsed through manually).
All resources should be uploaded under the Permission Level "Member - AASHE Member Status Required"
Submitter can be Monika Urbanski
Organization names always include the AMS ID in addition to the Org name. If there is a discrepancy, please check with me.
Please upload to staging and ask Monika to test before releasing on the live server
I'm happy to answer any questions you may have!

**Comment by dodget** [comment]
Ok, presentations are uploaded to the staging site. It all looks good to me. The only thing to notice is that some presentations weren't able to associate an organization. This is because the staging server's ISS table is not up to date (which is expected). I ran this process locally, with an up to date ISS table, and everything associated fine. The production ISS table is up to date.

All the files were uploaded to S3, and associated with the resources with no issues.

@monika-aashe - If it all checks out for you, I'll be able to run this on production!

**Comment by monika-aashe** [comment]
Thank you for the quick work, @dodget ! Upon first review, everything appears to check out except for one issue: whenever I try to download a .ppt or .pptx file to access the presentation, the download appears as a zipped file instead of a PPT presentation. When I try to click on it, it says "archiving" but does not open as a PPT. Is this an issue with the import, the staging site, or something on my end?

**Comment by monika-aashe** [comment]
Scratch that last comment about PPT not opening. It appears that after upgrading from the Yosemite OS to Catalina OS earlier today, I now have to upgrade Microsoft Office. I'll try the PPTs again once that is done!

**Comment by monika-aashe** [comment]
Just wanted to confirm that PPT files are opening fine for me now - I think we're ready to go live!

**Comment by dodget** [comment]
Ok, the presentations are uploaded to production! There were no issues with associating organizations, and all the files look good.

I'll leave it for you to review and close the issue.

**Comment by monika-aashe** [comment]
Thanks Tylor, I spot checked and everything looks great! I will close.

**Comment by monika-aashe** [comment]
Reopening for now because I'm having an issue with one of the filter options in the Conference Presentations - I'm hoping it's a caching issue and will resolve itself, but wanted to jot it down just in case. 

This only happens some of the time, but when I start at [Conference Presentations](https://hub.aashe.org/browse/types/presentation/#resources-panel) and go to use Year created, published or presented [filter for 2019](https://hub.aashe.org/browse/types/presentation/?search=&gallery_view=list&content_type=presentation&country=&created=2019&order=#resources-panel), sometimes I get zero results and the note, "Select a valid choice. 2019 is not one of the available choices." That choice no longer shows up. It happens more frequently when I combine this with other tags. 

![Screen Shot 2019-12-04 at 12 30 49 PM](https://user-images.githubusercontent.com/15214797/70166113-216c3f80-1692-11ea-872a-688052129ca7.png)

**Comment by dodget** [comment]
I think it may have been a cache issue. I'm not able to reproduce this, although I was able earlier.

**Comment by dodget** [comment]
@monika-aashe - Are you still experiencing issues? I've been checking on and off, and everything seems fine to me. Can this be closed?

**Comment by monika-aashe** [comment]
I have not so it was probably caching. Thank you! Closing.
