### ISSUE TITLE
AWS file name encoding

### ISSUE THREAD

**Issue by dodget** [AASHE/hub#577]
AWS encodes spaces to `+` and plus to `%2b`. This makes it confusing to escape the file name on our end. This can be resolved in two steps:

- Iterate over all the file urls in the Hub, and change their name if they have a certain set of special characters. Copy the file in S3 to new filename and remove the old file.
- Sanitize all new file uploads, removing those special characters from the name, before the file is posted and sent to s3.

**Comment by rerb** [comment]
when do the file names get url-encoded? there’s an option when url-encoding, to handle spaces and pluses as aws does. iirc, url-encoding happens via 3rd party package.

**Comment by dodget** [comment]
I assume the encoding is handled by S3Direct, and S3 itself.

If we can get in the middle of the file submission, like during `form_valid`, we could clean the filename of any of the "Characters that may require special handling" and "Characters to avoid" (found [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)) and replace them with an underscore or something.

The same process could be done as a management command for existing files. This would solve the issue where:
https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/Vasishth-AASHE+Ramapo_Green-2019.ppt cannot be found, but https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/Vasishth-AASHE%2bRamapo_Green-2019.ppt is available.

**Comment by rerb** [comment]
iirc, there’s a custom tag we’re using in the hub during the upload workflow, and in that tag’s code, the url is encoded?  might have been a dream, though.

—
bob

> On Dec 2, 2019, at 12:30 PM, Tylor Dodge <notifications@github.com> wrote:
> 
> I assume the encoding is handled by S3Direct, and S3 itself.
> 
> If we can get in the middle of the file submission, like during form_valid, we could clean the filename of any of the "Characters that may require special handling" and "Characters to avoid" (found here) and replace them with an underscore or something.
> 
> The same process could be done as a management command for existing files. This would solve the issue where:
> https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/Vasishth-AASHE+Ramapo_Green-2019.ppt cannot be found, but https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/Vasishth-AASHE%2bRamapo_Green-2019.ppt is available.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


-- 
Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

**Comment by dodget** [comment]
Looks like there is some escaping happening in the [base settings](https://github.com/AASHE/hub/blob/master/hub/settings/base.py#L305), although it's only been applied to images, and not to files.

That would be simple to implement moving forward, I believe, but the files already in the DB and S3 would need to be corrected.

**Comment by dodget** [comment]
Seems like the best approach to clean characters by using the function in settings, and then finding any files that use those characters, and fixing them where necessary.  I've completed the work for plus and space. I imagine that will be the bulk of the work, but I still need to go through all of the characters to avoid mentioned in [this link](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html).

My process has been:
- Set up a process to clean the characters in the settings file
- Write a script to find all the files and images that use those characters, and return the s3 object urls, and output to a local file. (This is to save compute resources on heroku).
- Using another script, iterate over the output of the local file, using `requests` to check if the url is reachable or not. If not, output the url to a file.
- This reveals only a handful of bad files. I just manually fix them.

**Comment by rerb** [comment]
the problem is that we’re storing an incompatible url-encoded file name in our db, right?  can’t we just url-encode the file name with the flags that escape +, etc., before we upload it to s3 and store the name?  

urllib.quote_plus(string[, safe])
Like quote(), but also replaces spaces by plus signs, as required for quoting HTML form values when building up a query string to go into a URL. Plus signs in the original string are escaped unless they are included in safe. It also does not have safe default to '/'.


—
bob

> On Dec 7, 2019, at 8:08 PM, Tylor Dodge <notifications@github.com> wrote:
> 
> ﻿
> Seems like the best approach to clean characters by using the function in settings, and then finding any files that use those characters, and fixing them where necessary. I've completed the work for plus and space. I imagine that will be the bulk of the work, but I still need to go through all of the characters to avoid mentioned in this link.
> 
> My process has been:
> 
> Set up a process to clean the characters in the settings file
> Write a script to find all the files and images that use those characters, and return the s3 object urls, and output to a local file. (This is to save compute resources on heroku).
> Using another script, iterate over the output of the local file, using requests to check if the url is reachable or not. If not, output the url to a file.
> This reveals only a handful of bad files. I just manually fix them.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

**Comment by dodget** [comment]
I believe the problem, ultimately, is with the S3Direct object. I think it is constructing a url for the file/image based on the bucket and key of the object, rather than just returning the object_url of the S3 "object" itself.

Thats a good idea, Bob. But I think it would be simplest to pass regex to the function in the base settings that is cleaning key names already. I'll hopefully get around to it this week. It is already taking care of plus and space characters (which are the most common offenders) but I'll include the other less common characters (like `#` and others) in that function.

**Comment by dodget** [comment]
Change has been pushed to production which escapes unwanted characters before the file/image is uploaded to S3. I ran scripts to check all of the files with those characters for broken links, and only found a handful. I fixed any links that appeared. This issue should be considered closed.
