### ISSUE TITLE
Include "hide all feature" for filters with check boxes

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#59]
Cancel below. Instead, add a "hide all" feature (to complement "show all" feature already there) so that you can collapse the filters for better usability.

We decided the checkboxes are not ideal in the filters, and would like to transition back to scroll bars but with improved functionality. As long as you can see 5 or more lines of text, the scroll bar will work (the issue before was that the scroll bar was only one line of text, making selecting multiple difficult)

Here is an example of what would be optimal: http://jquery-plugins.net/multiple-select-jquery-plugin-to-select-multiple-elements

**Comment by monika-aashe** [comment]
How will this impact the filtering on smartphone decision?

**Comment by bartTC** [comment]
The term for this is 'select-multiple widgets'.

**Comment by jamstooks** [comment]
@monika-aashe can you elaborate on this decision?

I actually really like the checkboxes. This is obviously just personal preference, but I do think it makes it very clear what has been selected, when a select-multiple with only 5 lines may not have all selected options immediately visible. I also like the collapsing of those that aren't being used to conserve visual space.

**Comment by monika-aashe** [comment]
Sure. I just looked at it again and I think I can definitely be swayed with sticking with checkboxes. However, the biggest issue right now is that the check boxes take up a lot of space vertically. Once you click on "show all", you can't "hide all" once you've made a selection and or decided you don't need that filter. 

I'm updating the initial ticket to say "include hide-all option" for filters that have "show all" and dropdowns

**Comment by jamstooks** [comment]
I added a little "minus" button, like the "check-all" button to collapse any unchecked boxes.
