### ISSUE TITLE
Add hyperlinks in Resource Detail

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#60]
Right now on the Resource detail, only content type is linked. We would like to hyperlink the following as well: 
1) keywords
2) sustainability topic
3) academic discipline
4) office or department
5) organization(s)

UI - If I click on a keyword/topic/discipline/office, it would no longer stay in the scope of that content type. This is okay, as long as "back" navigation works. 

Example: in the following resource all of these should be hyperlinked (http://aashe-hub-dev.herokuapp.com/browse/academicprogram/2/):
- *Michigan Technological University*
- Sustainability Topic: *Curriculum*
- Content Type: *Academic Programs*
- Discipline: *Environmental Studies & Sciences*
- Keywords: *environment*

**Comment by jamstooks** [comment]
So there might be a little issue here. I can't seem to get a direct link to search results without a search query. For example:

http://aashe-hub-dev.herokuapp.com/browse/?&organizations=17306 redirects to /

I tried leaving the search blank, but that doesn't work either:

http://aashe-hub-dev.herokuapp.com/browse/?search=&organizations=17306&country=

The only way I could show the browse view for just an org was if I had a keyword:

http://aashe-hub-dev.herokuapp.com/browse/?search=ecology&organizations=17306&country=

**Comment by monika-aashe** [comment]
That's weird, I thought it worked before, maybe something to ask Martin about?

**Comment by jamstooks** [comment]
Yeah. @rerb, if it's not an immediately obvious fix maybe we'll queue this up for Martin.

**Comment by rerb** [comment]
Fix not immediately obvious to me. :-) 

The BrowseView is explicit about requiring a topic, content type, or search term:
[https://github.com/AASHE/hub/blob/master/hub/apps/browse/views.py#L77-L83](https://github.com/AASHE/hub/blob/master/hub/apps/browse/views.py#L77-L83)

**Comment by jamstooks** [comment]
@rerb I think we're ok [adding more](https://github.com/AASHE/hub/commit/11ffce68fc725e54f2fb3b24c818a285d2e31258#diff-53bac309af9516baa996f5ea784f9af2) GET parameters.

@monika-aashe are there plans to add Academic Discipline and Office/Dept to the filters? If so, let's create other tickets and note that these need to be added to the links in the detail of a resource.

## Fixed

##### sustainability topic

/browse/topics/*topic*/

##### organization(s)
/browse/?organizations=id

##### content type
already linked

## Not fixed

##### keywords
this should probably just be search: browse/?search=keyword
unfortunately this one is trickier and will require some support. I created a [new ticket](https://github.com/AASHE/hub/issues/125) for this one and will talk to Martin about it.

##### academic discipline
not currently in filters so no link possible

##### office or department
not currently in filters so no link possible

**Comment by jamstooks** [comment]
@monika-aashe I'm closing this ticket in favor of getting those new tickets created if necessary.

**Comment by monika-aashe** [comment]
We weren't going to add Academic Disciplines or Office/Department to the filters right away, but there is a chance that we would later. So you're saying the only way we can link those is if there is filter for them? If that's the case, I'm okay with not linking those for now.

**Comment by juliandsmith** [comment]
I would like to make adding these filters and the associated links a requirement for launch. Otherwise there's almost no point to having people associate their resources with a discipline or department.

**Comment by monika-aashe** [comment]
I guess my concern is that the filters are already pretty long - especially in the current format. Perhaps once #59 is addressed, the filters will seem less cumbersome.

**Comment by jamstooks** [comment]
@monika-aashe - That is what I'm saying. :smile: 

@juliandsmith - I don't think I agree with you entirely, that there is no point. Those fields are still available for filtering later on and they are valuable in the context of the specific resource. This, again, is a balancing act between launching a "perfect" product, or launching early and improving the product. I tend to argue for the second one wherever possible.

I'm closing this issue in favor of other issues that can be created for academic discipline and office/department. I'd recommend adding one more milestone for **new features after launch** or something like that. We can then show immediate improvement to our users.

**Comment by juliandsmith** [comment]
I'm okay to leave this issue closed, but not on board with putting this off until after launch. I'll add to agenda for next call.
