### ISSUE TITLE
Navigational breadcrumbs

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#62]
At some point, we would like to add navigational breadcrumbs that follow the Content Type path (and align with URL paths). 

Examples:
hub home - submit a resource - academic programs
hub home - content type - academic program - name of program
hub home - sustainability topic - curriculum - resources (but, clicking on a resource from this list would change the breadcrumbs to: hub home - content type - academic program - name of program)

**Comment by monika-aashe** [comment]
Jessica's comment from 12/4 review team meeting: "Suggest adding a Home button or breadcrumb navigation.  It is not intuitive that clicking the title will take you back home."

**Comment by jamstooks** [comment]
Here are a few unify theme examples:

http://htmlstream.com/preview/unify-v1.8/Shop-UI/shop-ui-inner.html
http://htmlstream.com/preview/unify-v1.8/feature_gallery.html

I particularly like the home icon.

This breadcrumb strategy looks solid. I think I'd recommend a templatetag to do this...

**Comment by baronvonvaderham** [comment]
PR #181
