### ISSUE TITLE
Design of navigation buttons

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#63]
We would like to remove the "two-tone" coloring on the navigation to be a single tone of color - to better align with other AASHE websites that use the Unity theme.

**Comment by monika-aashe** [comment]
Jessica also requested rounded buttons instead of square but there may be limitations due to the Unity bootstrap theme - also may not be consistent with other AASHE sites.

**Comment by juliandsmith** [comment]
Reopening because the submit a resource buttons (http://aashe-hub-dev.herokuapp.com/submit-resource/) still have the two tone color scheme. Looks great otherwise though!
