### ISSUE TITLE
Featured resources - add order field in Admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#64]
Is there a way to change the order of the featured resources (besides deleting and re-adding)?
MM: No, but could add a order field similar to topics.

Decision: We decided it would be ideal to add an order field to make re-ordering easier.

**Comment by rerb** [comment]
@monika-aashe Where does one go to toggle the "favorite" flag on a resource, the flag that determines which resources are "featured"?  I don't see how to do that.  Is that not implemented?

**Comment by juliandsmith** [comment]
@monika-aashe is out so I'll answer for her... Programs staff can edit the featured resources  under the Change Sustainability Topic menus in the admin side (e.g. http://aashe-hub-dev.herokuapp.com/admin/metadata/sustainabilitytopic/15/).

**Comment by peltonc** [comment]
It happens at the sustainability topic level, e.g. http://aashe-hub-dev.herokuapp.com/admin/metadata/sustainabilitytopic/1/

> On 22 Dec 2015, at 21:48, Robert Erb <notifications@github.com> wrote:
> 
> @monika-aashe Where does one go to toggle the "favorite" flag on a resource, the flag that determines which resources are "featured"? I don't see how to do that. Is that not implemented?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

<http://www.aashe.org>
------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
Fixed in https://github.com/AASHE/hub/commit/88a2d81f74fbae81796f7939ffc5029d8218df2e.
