### ISSUE TITLE
Display email in logout link

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#66]
(From #27)

Having the user's email in the logout link might also be useful to help a user know that they are logged in and who they are logged in as... like: `logout, user@domain.xyz`

**Comment by juliandsmith** [comment]
Thanks Ben. Can you remove the comma after logout? It should be "logout XXX" not "logout, XXX".

**Comment by dodget** [comment]
Too simple not to knock off.

**Comment by juliandsmith** [comment]
This warms my heart. Thank you for clearing these tickets Tylor!!

**Comment by dodget** [comment]
Done in production, closing.
