### ISSUE TITLE
Published resources not found

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#68]
Several resources that have been "published" via admin back end are not actually showing up in the front end.  For example, the Interdisciplinary Graduate Certificate in Sustainability academic program and the publications entitled "Key competencies in sustainability: a reference framework for academic program development," and "Harnessing the Sun: A Case Study of Solar Energy Deployment at Agnes Scott College," all show up as published on the admin side. However, they do not appear in the appropriate topic or content type on the front end. Clicking "View on site" button in admin takes me to this page not found error:

![image](https://cloud.githubusercontent.com/assets/15839046/11232772/934f1082-8d84-11e5-8529-011904ecc389.png)

**Comment by bartTC** [comment]
They don't show up because the status is `New` and not `Published`. 

![](http://d.pr/i/1gly8+)

@juliandsmith please post here a link to either the resource or the related admin site, rather than the title. Later with thousands of entries it will be hard to find those.

**Comment by bartTC** [comment]
The 'published' timestamp is automatically filled out once the status becomes 'Published'. To avoid confusion I made this field *read only* and added a help text.

**Comment by monika-aashe** [comment]
It would be useful to continue to be able to edit the timestamp - but I do like that by default, the time that the change to Published is made shows up. Is there a way to add this back in?
