### ISSUE TITLE
Edits to "New Resources" section of Topical Toolkit

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#69]
Three issues we'd like to correct:

- [x] Every resource includes the text "- All Content Types -" instead of the name of the associated content type.
- [x] Would like to limit each list to the top five most recent. 
- [ ] Extra white space above "New Resources" text - white space should align with the white space for "Introduction"

Example:
https://aashe-hub-dev.herokuapp.com/browse/topics/curriculum/

**Comment by jamstooks** [comment]
The only piece I'd push back on is this:

>Extra white space above "New Resources" text - white space should align with the white space for "Introduction"

The text of "Introduction" and the text of "New Resources" align. I'd say that is preferable. If it really bothers more than one of you, I can extend the border around the new resources to go along the top too and that will align with the grey box to the left.

**Comment by juliandsmith** [comment]
Having Introduction and New Resources be aligned is good but I think Monika was talking about the white space *below* the headings, not above it. The text under Introduction is higher than the text associated with the first item under New Resources. This is not a big deal, but it would be nice to align that as well.

**Comment by jamstooks** [comment]
Ok, I see what you're saying. I'll see if I can tweak that.
