### ISSUE TITLE
Case Study submission form - issues 

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#71]
Right now, there is a separate description field and a separate project overview field. We do not need two fields. "Project Overview" essentially is the description, and should be treated as the generic "description field", in that the content from this field should populate the description section under list view. 
- NOTE: this is the only instance where the "description" is required versus optional.

**Comment by monika-aashe** [comment]
When I tried to edit an existing case study, I could not edit in admin because academic discipline is required there. Should the admin override required fields? 

http://aashe-hub-dev.herokuapp.com/admin/content/casestudy/4/

**Comment by jamstooks** [comment]
@monika-aashe how about this solution?

1. Remove the "Project Overview" field
2. Keep description, but label it "Project Overview"
3. Leave the new "Project Overview" field at the second position

This makes displaying this easier down the road. The only concern I thought you might have is that the description/project overview field would be the second field in the form... the normal position for description.

**Comment by monika-aashe** [comment]
The main concern I have is that the "project overview" be treated like the description, so that when you access the a page such as this, (http://aashe-hub-dev.herokuapp.com/browse/topics/energy/#resources-panel), it is the project overview field that provides the descriptive content.

As long as that's the case, your solution above would work.

**Comment by jamstooks** [comment]
Ok, cool. It would :)

**Comment by jamstooks** [comment]
Hey @baronvonvaderham - to do this, you simply override the [`label_overrides`](https://github.com/AASHE/hub/blob/master/hub/apps/content/models.py#L149) for the [Case Study](https://github.com/AASHE/hub/blob/master/hub/apps/content/types/casestudies.py) content type. See the example in [Academic Programs](https://github.com/AASHE/hub/blob/master/hub/apps/content/types/academic.py#L42).

**Comment by baronvonvaderham** [comment]
- Removed original overview field (first field)
- Overriding label on background field to read "Overview"
- Updated migrations to reflect this

**Comment by jamstooks** [comment]
This is almost there, I think we actually want to override the 'description' field's title, not background.

**Comment by baronvonvaderham** [comment]
Ah, I didn't see this was inheriting fields from another model.

**Comment by monika-aashe** [comment]
Can we relabel this field to "Project Overview or Description"? Besides this issue above, there are some additional issues with the submission form that I found in my 1/8/16 review:

The following fields are currently OPTIONAL, but should be REQUIRED:
- Project overview
- Background
- Project goals
- Project implementation
- Project timeline
- Financing
- Project results (or results to date)
- Lessons learned

There is also a minor issue with the authors/I am an author field, but I will submit that as a separate ticket since it relates to more than one content type.

**Comment by jamstooks** [comment]
Reopening to address Monika's additional issues. Working on this now.
