### ISSUE TITLE
Academic Program submission form - issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#72]
- Need to move "websites" up from optional metadata. When it's all said and done, there should be no optional metadata
- Program Type dropdown - must be required (currently optional)

**Comment by bartTC** [comment]
> Delete or hide Authors, Images, and Authors tabs under Optional Metadata - these are not relevant for this content type

Do you think these optional metadata is useful for any content type then? Would it make more sense and generally reduce confusion to remove it everywhere?

**Comment by monika-aashe** [comment]
Some of the fields are required, so we can't just remove them, but I'm thinking we might want to restructure that part to streamline the forms.  - I'll submit a ticket on this separately.

**Comment by jamstooks** [comment]
Fixed with 59f040f3cb88ba5585cccada39410bb9ab4560ec. The rest is addressed in #73, so I'm closing this ticket.
