### ISSUE TITLE
Author information issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#76]
Author fields are often in places they aren't necessary. Remove them from the following Submission forms: 
- Academic Programs, 
- Resource Centers & Institutes, 
- Photos, 
- Outreach Materials 

For the latter two, we are asking photographer/designer credit info in a single text box - please don't remove that.

**Comment by jamstooks** [comment]
Hey, @baronvonvaderham - I think it makes sense to bump you off this one as I'm working on a related issue: #73.

**Comment by baronvonvaderham** [comment]
Makes sense, probably the same solution of deleting forms from the formset inside the view that I was looking at.

**Comment by jamstooks** [comment]
@monika-aashe - what if we simply required at least one (or only one) image? Then we could leave the images in the same place and reduce duplication... that would also have the benefit of making the form more consistent.

**Comment by monika-aashe** [comment]
Will add to our call agenda ;)

**Comment by jamstooks** [comment]
Closed in favor of #140;
