### ISSUE TITLE
Automatically Assigning Sustainability Topic to certain content types

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#78]
There should be pre-selected content on these forms as well that cannot be changed (okay if only shows up in the admin, but then the forms should be set not show these options, and include up to 2 instead of 3):
- Academic Programs - Curriculum should be preselected as a choice under Sustainability Topic(s)
- Course Materials - Curriculum should be preselected as a choice under Sustainability Topic(s)
- Research Centers/Institutes - Research should be preselected as a choice under Sustainability Topic(s)

**Comment by monika-aashe** [comment]
Number 1 above (Academic Disciplines being optional in most content types) is a high priority, since it is messing up how we can submit content.

**Comment by monika-aashe** [comment]
1/8/16 update - no change.

**Comment by jamstooks** [comment]
What do you mean?

**Comment by monika-aashe** [comment]
Basically, we need to classify Academic Programs and Course Materials under the "Curriculum" topic no matter what, even if the user doesn't check "Curriculum" on the form. Same goes for Research Centers and Institutes always falling under the "Research" content type.

**Comment by jamstooks** [comment]
So the way I implemented this was to automatically populate the topic input with the required topic and then disable deletion of that topic, but allow deletion of others. Give it a try...
