### ISSUE TITLE
Submission form - Expand/Collapse file upload, image upload, 

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#79]
Front-end forms should include a single field for the following, but can expand to show a maximum number of fields, as follows:  
- File upload - show first file, expand to 3 (applies to Case Studies, Conference Presentations, Publications, Course Materials, Tools, Outreach Materials)
- Photo upload - show first file, expand to 3 (this is for Case Studies, Conference Presentations, Publications, and Outreach Materials. The Photographs content type should only allow for a single photo upload, so we may want to treat this as a different type of field)
- Author info - show first author, expand up to 5 (applies to Case Studies, Conference Presentations, Publications, Course Materials, Tools, Videos)

See an outline summary in rows 23-26 here: https://docs.google.com/spreadsheets/d/1ADsnCZXKU1lhA4GHc2xhsY5ddLRi7kgvYJLSTHZKlmw/edit#gid=935008516

Note: if more need to be added, this can be addressed on the admin side upon request.

This is something Martin and I discussed would be doable as a solution to keep the forms from getting to complex; however it appears it was never implemented.

**Comment by monika-aashe** [comment]
Added the decision needed label in case there's a way to add multiple uploads under photos - however, this would mean associating a caption with each photo, and making the "default description" be the first caption.

**Comment by jamstooks** [comment]
@monika-aashe - can you confirm this is ready to close? The validation of quantity is also there, but I'm addressing and testing that in #140.

**Comment by monika-aashe** [comment]
I say it's ready to close!
