### ISSUE TITLE
Warning help-text on submission forms

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#80]
When required fields are not filled out properly, it would be helpful to display a warning in red at the top of the page saying "Required content not provided - please update information in red below". Right now, the page just refreshes and you have to search the fields to figure out what's wrong. And sometimes, it is difficult to figure out where the issue is (particularly in the tabbed section).

Ideally, all issues would also be displayed at the top as well, for example:
"Required content not provided - please update information for the following fields: 
- File upload or website - at least one must be provided, 
- sustainability topic(s) - at least one must be selected
- etc." -

**Comment by jamstooks** [comment]
Will be fixed when the latest branch hits.
