### ISSUE TITLE
Conference Presentation Submission Forms

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#84]
- We decided to change the "Presentation Type" download options from 3 to 2. Need to change everything classified as "Presentation (2 or more speakers)" and "Presentation (1 speaker) to simply "Presentation". There should only be two options on this dropdown:
     - Poster
     - Presentation

- File upload in Optional metadata not necessary, since the upload is provided above (though would be good to allow up to three file uploads). On the detail page (http://aashe-hub-dev.herokuapp.com/browse/presentation/9/A-Balancing-Act-St-Louis-Higher-Education-Sustainability-Consortium), uploaded files also show up in two places. All uploaded files should be in one place.

**Comment by jamstooks** [comment]
Fixed in 4f500597021141b11f9ef66201dfb27cfd4692fa. Closing as the second bullet point is addressed in #73.

**Comment by monika-aashe** [comment]
Has the first bullet been addressed? I'm not seeing the change on the dev site.

**Comment by jamstooks** [comment]
Fixed in the code, not deployed yet.
