### ISSUE TITLE
Academic Disciplines should be optional

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#85]
Academic Disciplines should be optional on all content types EXCEPT Academic Programs, Research Centers & Institutes, and Course Materials, where they must be required.

Also, the Academic Discipline requirement cannot be overridden in Admin. My thinking is we should allow for overrides for required fields in admin for greater flexibility in the future.

**Comment by rerb** [comment]
Waiting for PR112 to be accepted and merged.

**Comment by monika-aashe** [comment]
@rerb - did you mean to close this? I'm still seeing Academic Disciplines as required when I checked today.

**Comment by monika-aashe** [comment]
Maybe because #112 was created?

**Comment by rerb** [comment]
It's fixed, it's just that the latest code hasn't been deployed to the dev
server yet.

On Wed, Dec 2, 2015 at 3:05 PM, monika-aashe <notifications@github.com>
wrote:

> Reopened #85 <https://github.com/AASHE/hub/issues/85>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/85#event-480630623>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

<http://www.aashe.org>
------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
Latest code deployed to server.  Still fixed.

**Comment by monika-aashe** [comment]
Yep, looks fixed to me now, thanks!
