### ISSUE TITLE
Outreach Material submission form issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#86]
Main Issue:
When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/outreach/39/UC-Davis-Sustainability-Map - it does show up in admin. 

Also:
- Academic discipline needs to be optional. 
- Affirmation of ownership is required even if a file was not uploaded
- Need to remove all optional metadata and "I am an author" checkbox - it is all redundant and unnecessary

**Comment by jamstooks** [comment]
Most of this was fixed in #140. I added a test URL to this resource just to confirm.
