### ISSUE TITLE
Transition to Tags Instead of Keywords

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#88]
Along with including a hyperlink to keywords on the resource detail pages (e.g. http://aashe-hub-dev.herokuapp.com/browse/center/7/The-Institute-for-Sustainable-Cities), (already included this in another ticket). We'd like to request the following features related to keywords to improve functionality.

- Auto-complete feature - as you begin typing a keyword, a list of already existing keywords shows up, so you can select one of the pre-existing words rather than creating a word that is slightly different (e.g. "AASHE2016" rather than "AASHE 2016")
- Index of keywords - in the keyword help-text, we'd like to link to a keyword index that displays all keywords and updates automatically - ideally, clicking on a single word would take you to the list of resources tagged with that keyword. 
- Add space after comma between keywords (e.g. http://aashe-hub-dev.herokuapp.com/browse/video/57/Introduction-Dorm-vs-Dorm-Sustainability-Competitions)

**Comment by jamstooks** [comment]
Hey, @bartTC. What do you think about switching to something like [django-tagulous](https://github.com/radiac/django-tagulous). We could use the auto-complete feature and a bunch of the others...

**Comment by jamstooks** [comment]
Note: I'll have to update elasticsearch to include this relation.

**Comment by jamstooks** [comment]
Ok, this is fixed in the admin. Take a peek and let me know if it needs any tweaks...

**Comment by juliandsmith** [comment]
Reopening because:
* Tags don't seem to be clickable links that take you to other resources with the same tag. Example: http://aashe-hub-dev.herokuapp.com/browse/outreachmaterial/105/Shut-the-Sash-Sticker
* Tags don't seem to auto complete in submission forms or on admin side.

Also, the previous system allowed for tags with multiple words (e.g., "bottled water" or "fume hood") but this one doesn't seem to. It closes the tag as soon as you hit space. This isn't necessarily a deal breaker but we'll have to change the help text because it currently uses "bottled water" as the example tag.

Finally,

**Comment by monika-aashe** [comment]
Would creating a filter for the keyword/tags be a possible solution for the first issue Julian mentioned?

**Comment by jamstooks** [comment]
Sorry, that was a late-night commit. I should have waited until morning. I changed the name of the field to "tags" at first and forgot to change it back to "keywords," so that caused some problems.

So here's how it works:

1. Keywords will now concatenate themselves when you add a comma(",") during submission
2. Once tags have been added, they will then auto-complete for further resources
3. Tags are now linked in the detail view

NOTE: Until #176 is resolved, these keyword links might not work immediately. We re-index the search every hour, but are working on a way to incrementally update it for each newly approved resource.

**Comment by jamstooks** [comment]
@monika-aashe I didn't create another filter, just used them as search terms.

**Comment by juliandsmith** [comment]
Thanks Ben! It's seems to be working well now! However, the key word tool on the admin side still concatenates when you hit space so it doesn't seem to be possible to add multi word tags once a resource has been submitted. Sorry to open this ticket again!

**Comment by jamstooks** [comment]
Ok, I'll see what I can do on the admin side of things.

**Comment by jamstooks** [comment]
Modifying the admin is proving to be pretty tricky and could be a bit of a rabbit hole. Can you give me a sense of the priority of this feature? I may want to build a workaround or just push this back a phase or two...

**Comment by monika-aashe** [comment]
We can add to the project team call tomorrow.


On Tue, Jan 19, 2016 at 4:57 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> Modifying the admin is proving to be pretty tricky and could be a bit of a
> rabbit hole. Can you give me a sense of the priority of this feature? I may
> want to build a workaround or just push this back a phase or two...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/88#issuecomment-173000996>.
>



-- 
Monika Urbanski
Data & Content Manager
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | monika.urbanski@aashe.org | (888) 347-9997 ext. 26

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals and 
reviewers now open <https://ww4.aievolution.com/ash1601>!

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment]
Decision: rename to "tags" and add an auto-complete filter for tags;

**Comment by juliandsmith** [comment]
Here's a perfect example of why just searching for the tag text is suboptimal: clicking on the "labs" tag (http://aashe-hub-stage.herokuapp.com/browse/?search=labs) ends up also including a bunch of resources with the "living labs" tag, which refers to something that is mostly unrelated to laboratories.

**Comment by rerb** [comment]
But, if I was looking for living labs stuff, wouldn't I click on the "labs"
tag?

On Fri, Feb 19, 2016 at 12:58 PM, juliandsmith <notifications@github.com>
wrote:

> Here's a perfect example of why just searching for the tag text is
> suboptimal: clicking on the "labs" tag (
> http://aashe-hub-stage.herokuapp.com/browse/?search=labs) ends up also
> including a bunch of resources with the "living labs" tag, which refers to
> something that is mostly unrelated to laboratories.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/88#issuecomment-186332689>.
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. Call for proposals & reviewers 
extended until Feb. 22! Submit your proposal today 
<https://ww4.aievolution.com/ash1601>!


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by juliandsmith** [comment]
Not really. You'd click on the "living labs" tag. This is especially true because you are most likely to see the tag when you are already on a resource with that tag. If you were looking at a living labs resource, you wouldn't even see a "labs" tag.

**Comment by juliandsmith** [comment]
A related issue is that multi-word tags seem to split into separate tags for each word when accessing a resource via admin. For example, I just submitted a resource with a tag of "civic engagement". When I accessed the same resource in the admin side, the tag had been split into separate tags for "civic" and "engagement". It is possible to delete these two and reapply the original tag manually but obviously it would be better not have to remember to double check the tags. 

Note that this issue doesn't seem to happen consistently. Multiword tags for some resources appear to stay whole.

**Comment by monika-aashe** [comment]
Is this not deployed yet? Clicking on tags still sends you to a search page instead of a filtered set of results. 

Also, there is a new problem in admin: before, I could select a two-word tag that was added during migration and it would show up correctly in the front-end. But now, selecting a previously used two-word tag breaks it into two separate tags.

**Comment by jamstooks** [comment]
Ok, I have performed the following and tested them:
- [x] added a filter for tags to the search view
- [x] updated the links in a specific resource to point to the page filtering on that tag
- [x] fixed the issue with multi-word tags being split up

This was a *tough* one! Closing now.

**Comment by monika-aashe** [comment]
Thanks Ben, I love how this works and can't wait to start using it when someone asks, "where can I find..."! 
I added a 1d ticket for updating "Search results" to "Filter results", but that's pretty minor. 

Nice work!
