### ISSUE TITLE
Remove "Capitalize First Word" for titles

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#91]
Be default, all titles are displayed as "Capitalize First Word", regardless of how they are entered. The proper title display should be:
- "Capitalize all words in titles of publications and documents, except a, an, and, as, at, but, by, for, in, of, on, or, nor, the, to, up, with"

http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html#Jr41tjHfoTUWSRYB.99

If this rule is too complex, we can simply set the titles to display as entered, and provide help text about proper title names - and staff can make edits in the admin.

**Comment by jamstooks** [comment]
I'm betting there's a way to do this with some sort of django filter...
