### ISSUE TITLE
Remove recolor lightning icon under "Request a Change"

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#92]
We would like to change the icon from a lightning bolt (which signifies instant results) to something else: 1st choice: Delta symbol; 2nd choice: lightbulb icon. Also, please update the color of the icon to be the same shade of green used throughout the hub (e.g. hyperlink text and "go" button after search)

**Comment by monika-aashe** [comment]
The review team pointed out that the "download" button (example here: http://aashe-hub-dev.herokuapp.com/browse/material/16/Sustainable-Design) and "apply filters" button at the bottom of all filter pages do not match the green that is throughout. 

Please also check that the blue used for the blue icons used for "authors" and "website" are one of the AASHE blue brand approved colors. (example: http://aashe-hub-dev.herokuapp.com/browse/material/16/Sustainable-Design)

**Comment by jamstooks** [comment]
Matching the colors is addressed in a different ticket: #129.

For the content, let's use [django-block-content](https://github.com/AASHE/django-block-content). It's used on the homepage, if you want an example.

**Comment by monika-aashe** [comment]
Re-opening due to Jessica's comment: I was actually requesting that we use the same shade of green throughout instead of having multiple shades of green. I was suggesting that we use the same shade of green that is used on the tabs at the top. (toolkit, resources, STARS, etc.) The "Download" button, "Request a Change" buttion and "Apply Filters" buttons all appear to be different shades of green. Could you make them the same green used throughout the hub.

**Comment by baronvonvaderham** [comment]
Can someone give me a link to a page where this Download button occurs? I can't seem to find any to test with.

The rest are fixed, but I might as well get all of them at once.

**Comment by baronvonvaderham** [comment]
Disregard, figured it out. But to clarify, do we want to change those icons to be green or leave them blue @jamstooks?

**Comment by monika-aashe** [comment]
Where I see this icon, it is already green. We want the green to match the green lettering on most pages. See screenshot below. 
<img width="983" alt="screen shot 2016-05-11 at 10 30 19 am" src="https://cloud.githubusercontent.com/assets/15214797/15184493/6b262438-1763-11e6-8d57-7bfcc891b65c.png">

**Comment by jamstooks** [comment]
From a UI standpoint, that Request a Change area, isn't super friendly. Could we make it all one button? Right now it's a weird-looking oval that isn't clickable. Is there any way we could make it all one button
[Request a Change] with the light bulb icon embedded?

**Comment by baronvonvaderham** [comment]
Yeah that's really strange actually, it looked way different locally. I agree, making it all one button is way better.

**Comment by baronvonvaderham** [comment]
Re-fixed finally. Will piggyback on next PR.

**Comment by baronvonvaderham** [comment]
I need to pass this off to @jamstooks, I need to troubleshoot why styling is behaving differently in production than on my local machine. Screenshots:

Local: http://i.imgur.com/Qpd7Vnl.png
Production: http://i.imgur.com/4AC4U52.png

**Comment by baronvonvaderham** [comment]
Fixed for real this time!
