### ISSUE TITLE
Photograph Submission Form issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#94]
Several issues:
- Image upload is currently optional. This field must be required. 
- Academic Discipline is currently required. Should be optional.
- "Description" field should be renamed "Caption or Description" - get rid of the second "Caption" field.

**Comment by monika-aashe** [comment]
Ideally, an image thumbnail would show up in list view and search results as well.

**Comment by monika-aashe** [comment]
Ideally, the cover image would appear to the right of the following info right below the title and org:
Date Published: Nov. 22, 2015
Last Updated: Nov. 22, 2015
Sustainability Topic: Wellbeing & Work
Content Type: Publications
Discipline: Agriculture
Release Date: Sept. 1, 2015
Publisher: AASHE

It shows up really low on the page, and isn't noticeable unless you scroll. http://aashe-hub-dev.herokuapp.com/browse/publication/47/2015-Sustainability-Staffing-Survey

**Comment by monika-aashe** [comment]
Also, we need to set some size limitations on this page. An image that is 300x388 pixels is perfect (http://aashe-hub-dev.herokuapp.com/browse/publication/47/2015-Sustainability-Staffing-Survey). Here, it is too large (http://aashe-hub-dev.herokuapp.com/browse/publication/49/Sustainable-Development-and-Quality-Assurance-in-Higher-Education)

**Comment by jamstooks** [comment]
Closing in favor of: #140

I believe we also decided that a caption and a description would be ok, so we'll leave the description field as is.
