### ISSUE TITLE
Research Centers & Institutes submission form

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#97]
- "Research" should be a pre-selected sustainability topic for all research centers & institutes - that cannot be modified.
- Need to remove "I am an author" and all optional metadata - not necessary and confusing.
- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/center/50/Australian-Centre-for-Environmental-Law - it does show up in admin.

**Comment by jamstooks** [comment]
- "Research" should be a pre-selected sustainability topic for all research centers & institutes - that cannot be modified.

This is duplicated by: #78

- Need to remove "I am an author" and all optional metadata - not necessary and confusing.

There are several content types that have the same requirements so I have consolidated them in #113

- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/center/50/Australian-Centre-for-Environmental-Law - it does show up in admin.

This applies to multiple content types, so I have broken it out as one ticket: #114
