### ISSUE TITLE
Course Materials submission form

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#98]
- "Curriculum" should be a pre-selected sustainability topic for all course materials - that cannot be modified.
- Need to remove "I am an author" and all optional metadata - not necessary and confusing.
- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved:http://aashe-hub-dev.herokuapp.com/browse/material/16/Sustainable-Design - it does show up in admin.
- Need to remove all optional metadata - not needed. Move Author info and doc upload fields up, only one website field.

**Comment by jamstooks** [comment]
I am closing this ticket and have broken out any necessary tickets. See below.

- "Curriculum" should be a pre-selected sustainability topic for all course materials - that cannot be modified.

This is duplicated by: #78

- Need to remove "I am an author" and all optional metadata - not necessary and confusing

There are several content types that have the same requirements so I have consolidated them in #113

- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved:http://aashe-hub-dev.herokuapp.com/browse/material/16/Sustainable-Design - it does show up in admin.

This applies to multiple content types, so I have broken it out as one ticket: #114 

- Need to remove all optional metadata - not needed. Move Author info and doc upload fields up, only one website field.

This is addressed in #73.

**Comment by monika-aashe** [comment]
Sounds good - I was unsure about what the best way to separate issues in tickets would be so for that reason, there is some duplication. Thanks for separating these!

**Comment by jamstooks** [comment]
Thanks, @monika-aashe. I think a good rule of thumb would be to report the issue once as an issue and then indicate the places where it applies. The alternative, reporting the places where a problem occurs could get pretty cluttered. Additionally, if we know that a particular problem applies to multiple content types, our solution may be different than if it applies in multiple places.
