### ISSUE TITLE
Tools Submission Form

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#99]
- Affirmation of ownership has to be checked even if you don't upload a file. This should only be required if uploading files.
- Academic Discipline is currently required - this should be optional. 
- ~~Need to remove "I am an author" and all optional metadata - not necessary and confusing. Move author info up.~~

**Comment by jamstooks** [comment]
@monika-aashe @juliandsmith Can you confirm that we have, in fact, decided that no one can submit a tool without declaring ownership of it? What about AASHE staff who find useful tools out there? We don't want to hound people to submit their own tools. Of course, I may have missed a lot of discussion on this and if this makes sense to you, then just say so and we will make it happen...

**Comment by monika-aashe** [comment]
Based on what we discussed, the Author info fields would be optional for Tools, so folks can definitely submit without declaring ownership if they want. In cases where a program website is the tool, it wouldn't make sense to include author info. In other cases, such as the SIP toolkit that Emilie Rex created (https://aashe-hub-dev.herokuapp.com/browse/tool/55/Sustainability-Internship-Program-SIP-Toolkit), it would be nice to be able to give the authors credit.

**Comment by monika-aashe** [comment]
The Summary tab in our Fields by Content Type document may be useful for figuring out where there are similarities/differences between content types (especially rows 23 - 26). This is modeled after the version that @jamstooks created. https://docs.google.com/spreadsheets/d/1ADsnCZXKU1lhA4GHc2xhsY5ddLRi7kgvYJLSTHZKlmw/edit#gid=935008516&vpid=B11

**Comment by jamstooks** [comment]
Pieces that are duplicated elsewhere:

- Need to remove "I am an author" and all optional metadata - not necessary and confusing. Move author info up.

This is addressed in #73.

- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/tool/52/Campus-Solar-Photovoltaic-Installations-Database - it does show up in admin.

This applies to multiple content types, so I have broken it out as one ticket: #114

**Comment by jamstooks** [comment]
Ok, great. Thanks. That makes sense.

**Comment by monika-aashe** [comment]
Closing this ticket because all these issues are found elsewhere: #75, #85, #73
